/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiDefinitionsGetCollection200ResponseHydraView model module.
 * @module model/ApiDefinitionsGetCollection200ResponseHydraView
 * @version v0.8.7
 */
class ApiDefinitionsGetCollection200ResponseHydraView {
    /**
     * Constructs a new <code>ApiDefinitionsGetCollection200ResponseHydraView</code>.
     * @alias module:model/ApiDefinitionsGetCollection200ResponseHydraView
     */
    constructor() { 
        
        ApiDefinitionsGetCollection200ResponseHydraView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiDefinitionsGetCollection200ResponseHydraView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiDefinitionsGetCollection200ResponseHydraView} obj Optional instance to populate.
     * @return {module:model/ApiDefinitionsGetCollection200ResponseHydraView} The populated <code>ApiDefinitionsGetCollection200ResponseHydraView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiDefinitionsGetCollection200ResponseHydraView();

            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('hydra:first')) {
                obj['hydra:first'] = ApiClient.convertToType(data['hydra:first'], 'String');
            }
            if (data.hasOwnProperty('hydra:last')) {
                obj['hydra:last'] = ApiClient.convertToType(data['hydra:last'], 'String');
            }
            if (data.hasOwnProperty('hydra:previous')) {
                obj['hydra:previous'] = ApiClient.convertToType(data['hydra:previous'], 'String');
            }
            if (data.hasOwnProperty('hydra:next')) {
                obj['hydra:next'] = ApiClient.convertToType(data['hydra:next'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiDefinitionsGetCollection200ResponseHydraView</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiDefinitionsGetCollection200ResponseHydraView</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@id'] && !(typeof data['@id'] === 'string' || data['@id'] instanceof String)) {
            throw new Error("Expected the field `@id` to be a primitive type in the JSON string but got " + data['@id']);
        }
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['hydra:first'] && !(typeof data['hydra:first'] === 'string' || data['hydra:first'] instanceof String)) {
            throw new Error("Expected the field `hydra:first` to be a primitive type in the JSON string but got " + data['hydra:first']);
        }
        // ensure the json data is a string
        if (data['hydra:last'] && !(typeof data['hydra:last'] === 'string' || data['hydra:last'] instanceof String)) {
            throw new Error("Expected the field `hydra:last` to be a primitive type in the JSON string but got " + data['hydra:last']);
        }
        // ensure the json data is a string
        if (data['hydra:previous'] && !(typeof data['hydra:previous'] === 'string' || data['hydra:previous'] instanceof String)) {
            throw new Error("Expected the field `hydra:previous` to be a primitive type in the JSON string but got " + data['hydra:previous']);
        }
        // ensure the json data is a string
        if (data['hydra:next'] && !(typeof data['hydra:next'] === 'string' || data['hydra:next'] instanceof String)) {
            throw new Error("Expected the field `hydra:next` to be a primitive type in the JSON string but got " + data['hydra:next']);
        }

        return true;
    }


}



/**
 * @member {String} @id
 */
ApiDefinitionsGetCollection200ResponseHydraView.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
ApiDefinitionsGetCollection200ResponseHydraView.prototype['@type'] = undefined;

/**
 * @member {String} hydra:first
 */
ApiDefinitionsGetCollection200ResponseHydraView.prototype['hydra:first'] = undefined;

/**
 * @member {String} hydra:last
 */
ApiDefinitionsGetCollection200ResponseHydraView.prototype['hydra:last'] = undefined;

/**
 * @member {String} hydra:previous
 */
ApiDefinitionsGetCollection200ResponseHydraView.prototype['hydra:previous'] = undefined;

/**
 * @member {String} hydra:next
 */
ApiDefinitionsGetCollection200ResponseHydraView.prototype['hydra:next'] = undefined;






export default ApiDefinitionsGetCollection200ResponseHydraView;

