/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DefinitionJsonldDefinitionReadContext from './DefinitionJsonldDefinitionReadContext';
import EntityJsonldDefinitionRead from './EntityJsonldDefinitionRead';

/**
 * The DefinitionJsonldDefinitionRead model module.
 * @module model/DefinitionJsonldDefinitionRead
 * @version v0.8.7
 */
class DefinitionJsonldDefinitionRead {
    /**
     * Constructs a new <code>DefinitionJsonldDefinitionRead</code>.
     * 
     * @alias module:model/DefinitionJsonldDefinitionRead
     * @param jsonSchema {Object} 
     */
    constructor(jsonSchema) { 
        
        DefinitionJsonldDefinitionRead.initialize(this, jsonSchema);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jsonSchema) { 
        obj['jsonSchema'] = jsonSchema;
    }

    /**
     * Constructs a <code>DefinitionJsonldDefinitionRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DefinitionJsonldDefinitionRead} obj Optional instance to populate.
     * @return {module:model/DefinitionJsonldDefinitionRead} The populated <code>DefinitionJsonldDefinitionRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DefinitionJsonldDefinitionRead();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = DefinitionJsonldDefinitionReadContext.constructFromObject(data['@context']);
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('jsonSchema')) {
                obj['jsonSchema'] = ApiClient.convertToType(data['jsonSchema'], Object);
            }
            if (data.hasOwnProperty('parentEntity')) {
                obj['parentEntity'] = EntityJsonldDefinitionRead.constructFromObject(data['parentEntity']);
            }
            if (data.hasOwnProperty('isOwnedByCurrentUser')) {
                obj['isOwnedByCurrentUser'] = ApiClient.convertToType(data['isOwnedByCurrentUser'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DefinitionJsonldDefinitionRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DefinitionJsonldDefinitionRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DefinitionJsonldDefinitionRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `@context`
        if (data['@context']) { // data not null
          DefinitionJsonldDefinitionReadContext.validateJSON(data['@context']);
        }
        // ensure the json data is a string
        if (data['@id'] && !(typeof data['@id'] === 'string' || data['@id'] instanceof String)) {
            throw new Error("Expected the field `@id` to be a primitive type in the JSON string but got " + data['@id']);
        }
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // validate the optional field `parentEntity`
        if (data['parentEntity']) { // data not null
          EntityJsonldDefinitionRead.validateJSON(data['parentEntity']);
        }

        return true;
    }


}

DefinitionJsonldDefinitionRead.RequiredProperties = ["jsonSchema"];

/**
 * @member {module:model/DefinitionJsonldDefinitionReadContext} @context
 */
DefinitionJsonldDefinitionRead.prototype['@context'] = undefined;

/**
 * @member {String} @id
 */
DefinitionJsonldDefinitionRead.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
DefinitionJsonldDefinitionRead.prototype['@type'] = undefined;

/**
 * @member {String} id
 */
DefinitionJsonldDefinitionRead.prototype['id'] = undefined;

/**
 * @member {String} slug
 */
DefinitionJsonldDefinitionRead.prototype['slug'] = undefined;

/**
 * @member {Object} jsonSchema
 */
DefinitionJsonldDefinitionRead.prototype['jsonSchema'] = undefined;

/**
 * @member {module:model/EntityJsonldDefinitionRead} parentEntity
 */
DefinitionJsonldDefinitionRead.prototype['parentEntity'] = undefined;

/**
 * @member {Boolean} isOwnedByCurrentUser
 */
DefinitionJsonldDefinitionRead.prototype['isOwnedByCurrentUser'] = undefined;






export default DefinitionJsonldDefinitionRead;

