/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DefinitionJsonldDefinitionReadContext from './DefinitionJsonldDefinitionReadContext';
import DefinitionJsonldEntityReadEntityReadParent from './DefinitionJsonldEntityReadEntityReadParent';

/**
 * The EntityJsonldEntityReadEntityReadParent model module.
 * @module model/EntityJsonldEntityReadEntityReadParent
 * @version v0.8.7
 */
class EntityJsonldEntityReadEntityReadParent {
    /**
     * Constructs a new <code>EntityJsonldEntityReadEntityReadParent</code>.
     * 
     * @alias module:model/EntityJsonldEntityReadEntityReadParent
     */
    constructor() { 
        
        EntityJsonldEntityReadEntityReadParent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityJsonldEntityReadEntityReadParent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityJsonldEntityReadEntityReadParent} obj Optional instance to populate.
     * @return {module:model/EntityJsonldEntityReadEntityReadParent} The populated <code>EntityJsonldEntityReadEntityReadParent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityJsonldEntityReadEntityReadParent();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = DefinitionJsonldDefinitionReadContext.constructFromObject(data['@context']);
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('definition')) {
                obj['definition'] = DefinitionJsonldEntityReadEntityReadParent.constructFromObject(data['definition']);
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = EntityJsonldEntityReadEntityReadParent.constructFromObject(data['parent']);
            }
            if (data.hasOwnProperty('private')) {
                obj['private'] = ApiClient.convertToType(data['private'], 'Boolean');
            }
            if (data.hasOwnProperty('isOwnedByCurrentUser')) {
                obj['isOwnedByCurrentUser'] = ApiClient.convertToType(data['isOwnedByCurrentUser'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EntityJsonldEntityReadEntityReadParent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EntityJsonldEntityReadEntityReadParent</code>.
     */
    static validateJSON(data) {
        // validate the optional field `@context`
        if (data['@context']) { // data not null
          DefinitionJsonldDefinitionReadContext.validateJSON(data['@context']);
        }
        // ensure the json data is a string
        if (data['@id'] && !(typeof data['@id'] === 'string' || data['@id'] instanceof String)) {
            throw new Error("Expected the field `@id` to be a primitive type in the JSON string but got " + data['@id']);
        }
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // validate the optional field `definition`
        if (data['definition']) { // data not null
          DefinitionJsonldEntityReadEntityReadParent.validateJSON(data['definition']);
        }
        // validate the optional field `parent`
        if (data['parent']) { // data not null
          EntityJsonldEntityReadEntityReadParent.validateJSON(data['parent']);
        }

        return true;
    }


}



/**
 * @member {module:model/DefinitionJsonldDefinitionReadContext} @context
 */
EntityJsonldEntityReadEntityReadParent.prototype['@context'] = undefined;

/**
 * @member {String} @id
 */
EntityJsonldEntityReadEntityReadParent.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
EntityJsonldEntityReadEntityReadParent.prototype['@type'] = undefined;

/**
 * @member {String} id
 */
EntityJsonldEntityReadEntityReadParent.prototype['id'] = undefined;

/**
 * @member {String} slug
 */
EntityJsonldEntityReadEntityReadParent.prototype['slug'] = undefined;

/**
 * @member {Object} data
 */
EntityJsonldEntityReadEntityReadParent.prototype['data'] = undefined;

/**
 * @member {module:model/DefinitionJsonldEntityReadEntityReadParent} definition
 */
EntityJsonldEntityReadEntityReadParent.prototype['definition'] = undefined;

/**
 * @member {module:model/EntityJsonldEntityReadEntityReadParent} parent
 */
EntityJsonldEntityReadEntityReadParent.prototype['parent'] = undefined;

/**
 * @member {Boolean} private
 */
EntityJsonldEntityReadEntityReadParent.prototype['private'] = undefined;

/**
 * @member {Boolean} isOwnedByCurrentUser
 */
EntityJsonldEntityReadEntityReadParent.prototype['isOwnedByCurrentUser'] = undefined;






export default EntityJsonldEntityReadEntityReadParent;

