/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntityJsonldEntityCreate model module.
 * @module model/EntityJsonldEntityCreate
 * @version v0.8.7
 */
class EntityJsonldEntityCreate {
    /**
     * Constructs a new <code>EntityJsonldEntityCreate</code>.
     * 
     * @alias module:model/EntityJsonldEntityCreate
     */
    constructor() { 
        
        EntityJsonldEntityCreate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityJsonldEntityCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityJsonldEntityCreate} obj Optional instance to populate.
     * @return {module:model/EntityJsonldEntityCreate} The populated <code>EntityJsonldEntityCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityJsonldEntityCreate();

            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('definition')) {
                obj['definition'] = ApiClient.convertToType(data['definition'], 'String');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = EntityJsonldEntityCreate.constructFromObject(data['parent']);
            }
            if (data.hasOwnProperty('private')) {
                obj['private'] = ApiClient.convertToType(data['private'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EntityJsonldEntityCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EntityJsonldEntityCreate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['definition'] && !(typeof data['definition'] === 'string' || data['definition'] instanceof String)) {
            throw new Error("Expected the field `definition` to be a primitive type in the JSON string but got " + data['definition']);
        }
        // validate the optional field `parent`
        if (data['parent']) { // data not null
          EntityJsonldEntityCreate.validateJSON(data['parent']);
        }

        return true;
    }


}



/**
 * @member {String} slug
 */
EntityJsonldEntityCreate.prototype['slug'] = undefined;

/**
 * @member {Object} data
 */
EntityJsonldEntityCreate.prototype['data'] = undefined;

/**
 * @member {String} definition
 */
EntityJsonldEntityCreate.prototype['definition'] = undefined;

/**
 * @member {module:model/EntityJsonldEntityCreate} parent
 */
EntityJsonldEntityCreate.prototype['parent'] = undefined;

/**
 * @member {Boolean} private
 */
EntityJsonldEntityCreate.prototype['private'] = undefined;






export default EntityJsonldEntityCreate;

