/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DefinitionJsonldDefinitionReadContext from './DefinitionJsonldDefinitionReadContext';

/**
 * The Oauth2JsonldOauth2Read model module.
 * @module model/Oauth2JsonldOauth2Read
 * @version v0.8.7
 */
class Oauth2JsonldOauth2Read {
    /**
     * Constructs a new <code>Oauth2JsonldOauth2Read</code>.
     * 
     * @alias module:model/Oauth2JsonldOauth2Read
     */
    constructor() { 
        
        Oauth2JsonldOauth2Read.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Oauth2JsonldOauth2Read</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Oauth2JsonldOauth2Read} obj Optional instance to populate.
     * @return {module:model/Oauth2JsonldOauth2Read} The populated <code>Oauth2JsonldOauth2Read</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Oauth2JsonldOauth2Read();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = DefinitionJsonldDefinitionReadContext.constructFromObject(data['@context']);
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('accessToken')) {
                obj['accessToken'] = ApiClient.convertToType(data['accessToken'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Oauth2JsonldOauth2Read</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Oauth2JsonldOauth2Read</code>.
     */
    static validateJSON(data) {
        // validate the optional field `@context`
        if (data['@context']) { // data not null
          DefinitionJsonldDefinitionReadContext.validateJSON(data['@context']);
        }
        // ensure the json data is a string
        if (data['@id'] && !(typeof data['@id'] === 'string' || data['@id'] instanceof String)) {
            throw new Error("Expected the field `@id` to be a primitive type in the JSON string but got " + data['@id']);
        }
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['accessToken'] && !(typeof data['accessToken'] === 'string' || data['accessToken'] instanceof String)) {
            throw new Error("Expected the field `accessToken` to be a primitive type in the JSON string but got " + data['accessToken']);
        }

        return true;
    }


}



/**
 * @member {module:model/DefinitionJsonldDefinitionReadContext} @context
 */
Oauth2JsonldOauth2Read.prototype['@context'] = undefined;

/**
 * @member {String} @id
 */
Oauth2JsonldOauth2Read.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
Oauth2JsonldOauth2Read.prototype['@type'] = undefined;

/**
 * @member {String} accessToken
 */
Oauth2JsonldOauth2Read.prototype['accessToken'] = undefined;






export default Oauth2JsonldOauth2Read;

