/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Oauth2Oauth2Read model module.
 * @module model/Oauth2Oauth2Read
 * @version v0.8.7
 */
class Oauth2Oauth2Read {
    /**
     * Constructs a new <code>Oauth2Oauth2Read</code>.
     * 
     * @alias module:model/Oauth2Oauth2Read
     */
    constructor() { 
        
        Oauth2Oauth2Read.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Oauth2Oauth2Read</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Oauth2Oauth2Read} obj Optional instance to populate.
     * @return {module:model/Oauth2Oauth2Read} The populated <code>Oauth2Oauth2Read</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Oauth2Oauth2Read();

            if (data.hasOwnProperty('accessToken')) {
                obj['accessToken'] = ApiClient.convertToType(data['accessToken'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Oauth2Oauth2Read</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Oauth2Oauth2Read</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['accessToken'] && !(typeof data['accessToken'] === 'string' || data['accessToken'] instanceof String)) {
            throw new Error("Expected the field `accessToken` to be a primitive type in the JSON string but got " + data['accessToken']);
        }

        return true;
    }


}



/**
 * @member {String} accessToken
 */
Oauth2Oauth2Read.prototype['accessToken'] = undefined;






export default Oauth2Oauth2Read;

