/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Oauth2Oauth2Write model module.
 * @module model/Oauth2Oauth2Write
 * @version v0.8.7
 */
class Oauth2Oauth2Write {
    /**
     * Constructs a new <code>Oauth2Oauth2Write</code>.
     * 
     * @alias module:model/Oauth2Oauth2Write
     */
    constructor() { 
        
        Oauth2Oauth2Write.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Oauth2Oauth2Write</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Oauth2Oauth2Write} obj Optional instance to populate.
     * @return {module:model/Oauth2Oauth2Write} The populated <code>Oauth2Oauth2Write</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Oauth2Oauth2Write();

            if (data.hasOwnProperty('grantType')) {
                obj['grantType'] = ApiClient.convertToType(data['grantType'], 'String');
            }
            if (data.hasOwnProperty('clientId')) {
                obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Oauth2Oauth2Write</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Oauth2Oauth2Write</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['grantType'] && !(typeof data['grantType'] === 'string' || data['grantType'] instanceof String)) {
            throw new Error("Expected the field `grantType` to be a primitive type in the JSON string but got " + data['grantType']);
        }
        // ensure the json data is a string
        if (data['clientId'] && !(typeof data['clientId'] === 'string' || data['clientId'] instanceof String)) {
            throw new Error("Expected the field `clientId` to be a primitive type in the JSON string but got " + data['clientId']);
        }
        // ensure the json data is a string
        if (data['clientSecret'] && !(typeof data['clientSecret'] === 'string' || data['clientSecret'] instanceof String)) {
            throw new Error("Expected the field `clientSecret` to be a primitive type in the JSON string but got " + data['clientSecret']);
        }

        return true;
    }


}



/**
 * @member {module:model/Oauth2Oauth2Write.GrantTypeEnum} grantType
 */
Oauth2Oauth2Write.prototype['grantType'] = undefined;

/**
 * @member {String} clientId
 */
Oauth2Oauth2Write.prototype['clientId'] = undefined;

/**
 * @member {String} clientSecret
 */
Oauth2Oauth2Write.prototype['clientSecret'] = undefined;





/**
 * Allowed values for the <code>grantType</code> property.
 * @enum {String}
 * @readonly
 */
Oauth2Oauth2Write['GrantTypeEnum'] = {

    /**
     * value: "client_credentials"
     * @const
     */
    "client_credentials": "client_credentials"
};



export default Oauth2Oauth2Write;

