/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserUserSendResetPassword model module.
 * @module model/UserUserSendResetPassword
 * @version v0.8.7
 */
class UserUserSendResetPassword {
    /**
     * Constructs a new <code>UserUserSendResetPassword</code>.
     * 
     * @alias module:model/UserUserSendResetPassword
     * @param email {String} 
     */
    constructor(email) { 
        
        UserUserSendResetPassword.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
        obj['email'] = email;
    }

    /**
     * Constructs a <code>UserUserSendResetPassword</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserUserSendResetPassword} obj Optional instance to populate.
     * @return {module:model/UserUserSendResetPassword} The populated <code>UserUserSendResetPassword</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserUserSendResetPassword();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('resetPasswordLink')) {
                obj['resetPasswordLink'] = ApiClient.convertToType(data['resetPasswordLink'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserUserSendResetPassword</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserUserSendResetPassword</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserUserSendResetPassword.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['resetPasswordLink'] && !(typeof data['resetPasswordLink'] === 'string' || data['resetPasswordLink'] instanceof String)) {
            throw new Error("Expected the field `resetPasswordLink` to be a primitive type in the JSON string but got " + data['resetPasswordLink']);
        }

        return true;
    }


}

UserUserSendResetPassword.RequiredProperties = ["email"];

/**
 * @member {String} email
 */
UserUserSendResetPassword.prototype['email'] = undefined;

/**
 * @member {String} resetPasswordLink
 */
UserUserSendResetPassword.prototype['resetPasswordLink'] = undefined;






export default UserUserSendResetPassword;

