/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserJsonldUserResetPassword model module.
 * @module model/UserJsonldUserResetPassword
 * @version v0.8.7
 */
class UserJsonldUserResetPassword {
    /**
     * Constructs a new <code>UserJsonldUserResetPassword</code>.
     * 
     * @alias module:model/UserJsonldUserResetPassword
     * @param password {String} 
     * @param token {String} 
     */
    constructor(password, token) { 
        
        UserJsonldUserResetPassword.initialize(this, password, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password, token) { 
        obj['password'] = password;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>UserJsonldUserResetPassword</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserJsonldUserResetPassword} obj Optional instance to populate.
     * @return {module:model/UserJsonldUserResetPassword} The populated <code>UserJsonldUserResetPassword</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserJsonldUserResetPassword();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserJsonldUserResetPassword</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserJsonldUserResetPassword</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserJsonldUserResetPassword.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }


}

UserJsonldUserResetPassword.RequiredProperties = ["password", "token"];

/**
 * @member {String} password
 */
UserJsonldUserResetPassword.prototype['password'] = undefined;

/**
 * @member {String} token
 */
UserJsonldUserResetPassword.prototype['token'] = undefined;






export default UserJsonldUserResetPassword;

