/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiDefinitionsGetCollection200Response from '../model/ApiDefinitionsGetCollection200Response';
import DefinitionDefinitionRead from '../model/DefinitionDefinitionRead';
import DefinitionDefinitionWrite from '../model/DefinitionDefinitionWrite';
import DefinitionJsonldDefinitionRead from '../model/DefinitionJsonldDefinitionRead';
import DefinitionJsonldDefinitionWrite from '../model/DefinitionJsonldDefinitionWrite';

/**
* Definition service.
* @module api/DefinitionApi
* @version v0.8.7
*/
export default class DefinitionApi {

    /**
    * Constructs a new DefinitionApi. 
    * @alias module:api/DefinitionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Retrieves the collection of definition resources.
     * Retrieves the collection of definition resources.
     * @param {Object} opts Optional parameters
     * @param {String} [qid] Filter by slug/id (partial match)
     * @param {Boolean} [isOwnedByMe] Show only definitions owned by the current user
     * @param {Number} [page = 1)] The collection page number
     * @param {Number} [limit = 10)] The number of items per page
     * @param {Array.<String>} [properties] Allows you to reduce the response to contain only the properties you need. If your desired property is nested, you can address it using nested arrays. Example: properties[]={propertyName}&properties[]={anotherPropertyName}&properties[{nestedPropertyParent}][]={nestedProperty}
     * @param {String} [parentEntity] Filter by parentEntity (uuid)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiDefinitionsGetCollection200Response} and HTTP response
     */
    apiDefinitionsGetCollectionWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'qid': opts['qid'],
        'isOwnedByMe': opts['isOwnedByMe'],
        'page': opts['page'],
        'limit': opts['limit'],
        'properties[]': this.apiClient.buildCollectionParam(opts['properties'], 'multi'),
        'parentEntity': opts['parentEntity']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = ApiDefinitionsGetCollection200Response;
      return this.apiClient.callApi(
        '/api/definitions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieves the collection of definition resources.
     * Retrieves the collection of definition resources.
     * @param {Object} opts Optional parameters
     * @param {String} opts.qid Filter by slug/id (partial match)
     * @param {Boolean} opts.isOwnedByMe Show only definitions owned by the current user
     * @param {Number} opts.page The collection page number (default to 1)
     * @param {Number} opts.limit The number of items per page (default to 10)
     * @param {Array.<String>} opts.properties Allows you to reduce the response to contain only the properties you need. If your desired property is nested, you can address it using nested arrays. Example: properties[]={propertyName}&properties[]={anotherPropertyName}&properties[{nestedPropertyParent}][]={nestedProperty}
     * @param {String} opts.parentEntity Filter by parentEntity (uuid)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiDefinitionsGetCollection200Response}
     */
    apiDefinitionsGetCollection(opts) {
      return this.apiDefinitionsGetCollectionWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Removes the definition resource.
     * Removes the definition resource.
     * @param {String} id definition identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    apiDefinitionsIdDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiDefinitionsIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/definitions/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Removes the definition resource.
     * Removes the definition resource.
     * @param {String} id definition identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    apiDefinitionsIdDelete(id) {
      return this.apiDefinitionsIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieves a definition resource.
     * Retrieves a definition resource.
     * @param {String} id definition identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DefinitionJsonldDefinitionRead} and HTTP response
     */
    apiDefinitionsIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiDefinitionsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = DefinitionJsonldDefinitionRead;
      return this.apiClient.callApi(
        '/api/definitions/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieves a definition resource.
     * Retrieves a definition resource.
     * @param {String} id definition identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DefinitionJsonldDefinitionRead}
     */
    apiDefinitionsIdGet(id) {
      return this.apiDefinitionsIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Updates the definition resource.
     * Updates the definition resource.
     * @param {String} id definition identifier
     * @param {module:model/DefinitionDefinitionWrite} definitionDefinitionWrite The updated definition resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DefinitionJsonldDefinitionRead} and HTTP response
     */
    apiDefinitionsIdPatchWithHttpInfo(id, definitionDefinitionWrite) {
      let postBody = definitionDefinitionWrite;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiDefinitionsIdPatch");
      }
      // verify the required parameter 'definitionDefinitionWrite' is set
      if (definitionDefinitionWrite === undefined || definitionDefinitionWrite === null) {
        throw new Error("Missing the required parameter 'definitionDefinitionWrite' when calling apiDefinitionsIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = ['application/merge-patch+json'];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = DefinitionJsonldDefinitionRead;
      return this.apiClient.callApi(
        '/api/definitions/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Updates the definition resource.
     * Updates the definition resource.
     * @param {String} id definition identifier
     * @param {module:model/DefinitionDefinitionWrite} definitionDefinitionWrite The updated definition resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DefinitionJsonldDefinitionRead}
     */
    apiDefinitionsIdPatch(id, definitionDefinitionWrite) {
      return this.apiDefinitionsIdPatchWithHttpInfo(id, definitionDefinitionWrite)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Creates a definition resource.
     * Creates a definition resource.
     * @param {module:model/DefinitionJsonldDefinitionWrite} definitionJsonldDefinitionWrite The new definition resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DefinitionJsonldDefinitionRead} and HTTP response
     */
    apiDefinitionsPostWithHttpInfo(definitionJsonldDefinitionWrite) {
      let postBody = definitionJsonldDefinitionWrite;
      // verify the required parameter 'definitionJsonldDefinitionWrite' is set
      if (definitionJsonldDefinitionWrite === undefined || definitionJsonldDefinitionWrite === null) {
        throw new Error("Missing the required parameter 'definitionJsonldDefinitionWrite' when calling apiDefinitionsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = ['application/ld+json', 'application/json'];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = DefinitionJsonldDefinitionRead;
      return this.apiClient.callApi(
        '/api/definitions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Creates a definition resource.
     * Creates a definition resource.
     * @param {module:model/DefinitionJsonldDefinitionWrite} definitionJsonldDefinitionWrite The new definition resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DefinitionJsonldDefinitionRead}
     */
    apiDefinitionsPost(definitionJsonldDefinitionWrite) {
      return this.apiDefinitionsPostWithHttpInfo(definitionJsonldDefinitionWrite)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
