/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Oauth2JsonldOauth2Read from '../model/Oauth2JsonldOauth2Read';
import Oauth2JsonldOauth2Write from '../model/Oauth2JsonldOauth2Write';
import Oauth2Oauth2Read from '../model/Oauth2Oauth2Read';
import Oauth2Oauth2Write from '../model/Oauth2Oauth2Write';

/**
* Oauth2 service.
* @module api/Oauth2Api
* @version v0.8.7
*/
export default class Oauth2Api {

    /**
    * Constructs a new Oauth2Api. 
    * @alias module:api/Oauth2Api
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Retrieve an OAuth2 Token
     * This endpoint issues an OAuth2 token using your client credentials.
     * @param {module:model/Oauth2JsonldOauth2Write} oauth2JsonldOauth2Write The new oauth2 resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Oauth2JsonldOauth2Read} and HTTP response
     */
    apiOauth2tokenPostWithHttpInfo(oauth2JsonldOauth2Write) {
      let postBody = oauth2JsonldOauth2Write;
      // verify the required parameter 'oauth2JsonldOauth2Write' is set
      if (oauth2JsonldOauth2Write === undefined || oauth2JsonldOauth2Write === null) {
        throw new Error("Missing the required parameter 'oauth2JsonldOauth2Write' when calling apiOauth2tokenPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/ld+json', 'application/json'];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = Oauth2JsonldOauth2Read;
      return this.apiClient.callApi(
        '/api/oauth2/token', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieve an OAuth2 Token
     * This endpoint issues an OAuth2 token using your client credentials.
     * @param {module:model/Oauth2JsonldOauth2Write} oauth2JsonldOauth2Write The new oauth2 resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Oauth2JsonldOauth2Read}
     */
    apiOauth2tokenPost(oauth2JsonldOauth2Write) {
      return this.apiOauth2tokenPostWithHttpInfo(oauth2JsonldOauth2Write)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
