/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import User from '../model/User';
import UserJsonld from '../model/UserJsonld';
import UserJsonldUserCreate from '../model/UserJsonldUserCreate';
import UserJsonldUserEmpty from '../model/UserJsonldUserEmpty';
import UserJsonldUserResendActivation from '../model/UserJsonldUserResendActivation';
import UserJsonldUserResetPassword from '../model/UserJsonldUserResetPassword';
import UserJsonldUserSendResetPassword from '../model/UserJsonldUserSendResetPassword';
import UserUserCreate from '../model/UserUserCreate';
import UserUserResendActivation from '../model/UserUserResendActivation';
import UserUserResetPassword from '../model/UserUserResetPassword';
import UserUserSendResetPassword from '../model/UserUserSendResetPassword';
import UserUserUpdate from '../model/UserUserUpdate';

/**
* User service.
* @module api/UserApi
* @version v0.8.7
*/
export default class UserApi {

    /**
    * Constructs a new UserApi. 
    * @alias module:api/UserApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Removes the user resource.
     * Removes the user resource.
     * @param {String} id user identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    apiUsersIdDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiUsersIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/users/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Removes the user resource.
     * Removes the user resource.
     * @param {String} id user identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    apiUsersIdDelete(id) {
      return this.apiUsersIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Updates the user resource.
     * Updates the user resource.
     * @param {String} id user identifier
     * @param {module:model/UserUserUpdate} userUserUpdate The updated user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserJsonldUserEmpty} and HTTP response
     */
    apiUsersIdPatchWithHttpInfo(id, userUserUpdate) {
      let postBody = userUserUpdate;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiUsersIdPatch");
      }
      // verify the required parameter 'userUserUpdate' is set
      if (userUserUpdate === undefined || userUserUpdate === null) {
        throw new Error("Missing the required parameter 'userUserUpdate' when calling apiUsersIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = ['application/merge-patch+json'];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = UserJsonldUserEmpty;
      return this.apiClient.callApi(
        '/api/users/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Updates the user resource.
     * Updates the user resource.
     * @param {String} id user identifier
     * @param {module:model/UserUserUpdate} userUserUpdate The updated user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserJsonldUserEmpty}
     */
    apiUsersIdPatch(id, userUserUpdate) {
      return this.apiUsersIdPatchWithHttpInfo(id, userUserUpdate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Creates a user resource.
     * Creates a user resource.
     * @param {module:model/UserJsonldUserCreate} userJsonldUserCreate The new user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserJsonldUserEmpty} and HTTP response
     */
    apiUsersPostWithHttpInfo(userJsonldUserCreate) {
      let postBody = userJsonldUserCreate;
      // verify the required parameter 'userJsonldUserCreate' is set
      if (userJsonldUserCreate === undefined || userJsonldUserCreate === null) {
        throw new Error("Missing the required parameter 'userJsonldUserCreate' when calling apiUsersPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/ld+json', 'application/json'];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = UserJsonldUserEmpty;
      return this.apiClient.callApi(
        '/api/users', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Creates a user resource.
     * Creates a user resource.
     * @param {module:model/UserJsonldUserCreate} userJsonldUserCreate The new user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserJsonldUserEmpty}
     */
    apiUsersPost(userJsonldUserCreate) {
      return this.apiUsersPostWithHttpInfo(userJsonldUserCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Resend activation email
     * This endpoint resends the activation email to the user.
     * @param {module:model/UserJsonldUserResendActivation} userJsonldUserResendActivation The new user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserJsonld} and HTTP response
     */
    apiUsersresendActivationPostWithHttpInfo(userJsonldUserResendActivation) {
      let postBody = userJsonldUserResendActivation;
      // verify the required parameter 'userJsonldUserResendActivation' is set
      if (userJsonldUserResendActivation === undefined || userJsonldUserResendActivation === null) {
        throw new Error("Missing the required parameter 'userJsonldUserResendActivation' when calling apiUsersresendActivationPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/ld+json', 'application/json'];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = UserJsonld;
      return this.apiClient.callApi(
        '/api/users/resend-activation', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Resend activation email
     * This endpoint resends the activation email to the user.
     * @param {module:model/UserJsonldUserResendActivation} userJsonldUserResendActivation The new user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserJsonld}
     */
    apiUsersresendActivationPost(userJsonldUserResendActivation) {
      return this.apiUsersresendActivationPostWithHttpInfo(userJsonldUserResendActivation)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Reset password (with token)
     * This endpoint resets the password of the user using the token sent by email.
     * @param {module:model/UserJsonldUserResetPassword} userJsonldUserResetPassword The new user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserJsonldUserEmpty} and HTTP response
     */
    apiUsersresetPasswordPostWithHttpInfo(userJsonldUserResetPassword) {
      let postBody = userJsonldUserResetPassword;
      // verify the required parameter 'userJsonldUserResetPassword' is set
      if (userJsonldUserResetPassword === undefined || userJsonldUserResetPassword === null) {
        throw new Error("Missing the required parameter 'userJsonldUserResetPassword' when calling apiUsersresetPasswordPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/ld+json', 'application/json'];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = UserJsonldUserEmpty;
      return this.apiClient.callApi(
        '/api/users/reset-password', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Reset password (with token)
     * This endpoint resets the password of the user using the token sent by email.
     * @param {module:model/UserJsonldUserResetPassword} userJsonldUserResetPassword The new user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserJsonldUserEmpty}
     */
    apiUsersresetPasswordPost(userJsonldUserResetPassword) {
      return this.apiUsersresetPasswordPostWithHttpInfo(userJsonldUserResetPassword)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Send reset password email
     * This endpoint sends a reset password email to the user.
     * @param {module:model/UserJsonldUserSendResetPassword} userJsonldUserSendResetPassword The new user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserJsonldUserEmpty} and HTTP response
     */
    apiUserssendResetPasswordPostWithHttpInfo(userJsonldUserSendResetPassword) {
      let postBody = userJsonldUserSendResetPassword;
      // verify the required parameter 'userJsonldUserSendResetPassword' is set
      if (userJsonldUserSendResetPassword === undefined || userJsonldUserSendResetPassword === null) {
        throw new Error("Missing the required parameter 'userJsonldUserSendResetPassword' when calling apiUserssendResetPasswordPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/ld+json', 'application/json'];
      let accepts = ['application/ld+json', 'application/json'];
      let returnType = UserJsonldUserEmpty;
      return this.apiClient.callApi(
        '/api/users/send-reset-password', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Send reset password email
     * This endpoint sends a reset password email to the user.
     * @param {module:model/UserJsonldUserSendResetPassword} userJsonldUserSendResetPassword The new user resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserJsonldUserEmpty}
     */
    apiUserssendResetPasswordPost(userJsonldUserSendResetPassword) {
      return this.apiUserssendResetPasswordPostWithHttpInfo(userJsonldUserSendResetPassword)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
