/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiDefinitionsGetCollection200Response,
  ConstraintViolation,
  ConstraintViolationJsonld,
  DefinitionDefinitionWriteJsonMergePatch,
  DefinitionJsonhalDefinitionRead,
  DefinitionJsonhalDefinitionWrite,
  ErrorJsonld,
} from '../models/index';
import {
    ApiDefinitionsGetCollection200ResponseFromJSON,
    ApiDefinitionsGetCollection200ResponseToJSON,
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
    ConstraintViolationJsonldFromJSON,
    ConstraintViolationJsonldToJSON,
    DefinitionDefinitionWriteJsonMergePatchFromJSON,
    DefinitionDefinitionWriteJsonMergePatchToJSON,
    DefinitionJsonhalDefinitionReadFromJSON,
    DefinitionJsonhalDefinitionReadToJSON,
    DefinitionJsonhalDefinitionWriteFromJSON,
    DefinitionJsonhalDefinitionWriteToJSON,
    ErrorJsonldFromJSON,
    ErrorJsonldToJSON,
} from '../models/index';

export interface ApiDefinitionsGetCollectionRequest {
    qid?: string;
    owned?: boolean;
    page?: number;
    limit?: number;
    properties?: Array<string>;
    parentEntity?: string;
}

export interface ApiDefinitionsIdDeleteRequest {
    id: string;
}

export interface ApiDefinitionsIdGetRequest {
    id: string;
}

export interface ApiDefinitionsIdPatchRequest {
    id: string;
    definitionDefinitionWriteJsonMergePatch: DefinitionDefinitionWriteJsonMergePatch;
}

export interface ApiDefinitionsPostRequest {
    definitionJsonhalDefinitionWrite: DefinitionJsonhalDefinitionWrite;
}

/**
 * 
 */
export class DefinitionApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiDefinitionsGetCollection without sending the request
     */
    async apiDefinitionsGetCollectionRequestOpts(requestParameters: ApiDefinitionsGetCollectionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['qid'] != null) {
            queryParameters['qid'] = requestParameters['qid'];
        }

        if (requestParameters['owned'] != null) {
            queryParameters['owned'] = requestParameters['owned'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['properties'] != null) {
            queryParameters['properties[]'] = requestParameters['properties'];
        }

        if (requestParameters['parentEntity'] != null) {
            queryParameters['parentEntity'] = requestParameters['parentEntity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/definitions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the collection of definition resources.
     * Retrieves the collection of definition resources.
     */
    async apiDefinitionsGetCollectionRaw(requestParameters: ApiDefinitionsGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDefinitionsGetCollection200Response>> {
        const requestOptions = await this.apiDefinitionsGetCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDefinitionsGetCollection200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the collection of definition resources.
     * Retrieves the collection of definition resources.
     */
    async apiDefinitionsGetCollection(requestParameters: ApiDefinitionsGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDefinitionsGetCollection200Response> {
        const response = await this.apiDefinitionsGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDefinitionsIdDelete without sending the request
     */
    async apiDefinitionsIdDeleteRequestOpts(requestParameters: ApiDefinitionsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDefinitionsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes the definition resource.
     * Removes the definition resource.
     */
    async apiDefinitionsIdDeleteRaw(requestParameters: ApiDefinitionsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiDefinitionsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the definition resource.
     * Removes the definition resource.
     */
    async apiDefinitionsIdDelete(requestParameters: ApiDefinitionsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDefinitionsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiDefinitionsIdGet without sending the request
     */
    async apiDefinitionsIdGetRequestOpts(requestParameters: ApiDefinitionsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDefinitionsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a definition resource.
     * Retrieves a definition resource.
     */
    async apiDefinitionsIdGetRaw(requestParameters: ApiDefinitionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DefinitionJsonhalDefinitionRead>> {
        const requestOptions = await this.apiDefinitionsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefinitionJsonhalDefinitionReadFromJSON(jsonValue));
    }

    /**
     * Retrieves a definition resource.
     * Retrieves a definition resource.
     */
    async apiDefinitionsIdGet(requestParameters: ApiDefinitionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DefinitionJsonhalDefinitionRead> {
        const response = await this.apiDefinitionsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDefinitionsIdPatch without sending the request
     */
    async apiDefinitionsIdPatchRequestOpts(requestParameters: ApiDefinitionsIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDefinitionsIdPatch().'
            );
        }

        if (requestParameters['definitionDefinitionWriteJsonMergePatch'] == null) {
            throw new runtime.RequiredError(
                'definitionDefinitionWriteJsonMergePatch',
                'Required parameter "definitionDefinitionWriteJsonMergePatch" was null or undefined when calling apiDefinitionsIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DefinitionDefinitionWriteJsonMergePatchToJSON(requestParameters['definitionDefinitionWriteJsonMergePatch']),
        };
    }

    /**
     * Updates the definition resource.
     * Updates the definition resource.
     */
    async apiDefinitionsIdPatchRaw(requestParameters: ApiDefinitionsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DefinitionJsonhalDefinitionRead>> {
        const requestOptions = await this.apiDefinitionsIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefinitionJsonhalDefinitionReadFromJSON(jsonValue));
    }

    /**
     * Updates the definition resource.
     * Updates the definition resource.
     */
    async apiDefinitionsIdPatch(requestParameters: ApiDefinitionsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DefinitionJsonhalDefinitionRead> {
        const response = await this.apiDefinitionsIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDefinitionsPost without sending the request
     */
    async apiDefinitionsPostRequestOpts(requestParameters: ApiDefinitionsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['definitionJsonhalDefinitionWrite'] == null) {
            throw new runtime.RequiredError(
                'definitionJsonhalDefinitionWrite',
                'Required parameter "definitionJsonhalDefinitionWrite" was null or undefined when calling apiDefinitionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/hal+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/definitions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DefinitionJsonhalDefinitionWriteToJSON(requestParameters['definitionJsonhalDefinitionWrite']),
        };
    }

    /**
     * Creates a definition resource.
     * Creates a definition resource.
     */
    async apiDefinitionsPostRaw(requestParameters: ApiDefinitionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DefinitionJsonhalDefinitionRead>> {
        const requestOptions = await this.apiDefinitionsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefinitionJsonhalDefinitionReadFromJSON(jsonValue));
    }

    /**
     * Creates a definition resource.
     * Creates a definition resource.
     */
    async apiDefinitionsPost(requestParameters: ApiDefinitionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DefinitionJsonhalDefinitionRead> {
        const response = await this.apiDefinitionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
