/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiEntitiesGetCollection200Response,
  EntityEntityUpdate,
  EntityJsonapi,
  EntityJsonhalEntityCreate,
  EntityJsonhalEntityReadEntityReadParent,
} from '../models/index';
import {
    ApiEntitiesGetCollection200ResponseFromJSON,
    ApiEntitiesGetCollection200ResponseToJSON,
    EntityEntityUpdateFromJSON,
    EntityEntityUpdateToJSON,
    EntityJsonapiFromJSON,
    EntityJsonapiToJSON,
    EntityJsonhalEntityCreateFromJSON,
    EntityJsonhalEntityCreateToJSON,
    EntityJsonhalEntityReadEntityReadParentFromJSON,
    EntityJsonhalEntityReadEntityReadParentToJSON,
} from '../models/index';

export interface ApiEntitiesGetCollectionRequest {
    qid?: string;
    _private?: boolean;
    owned?: boolean;
    page?: number;
    limit?: number;
    properties?: Array<string>;
    definition?: string;
    parent?: string;
}

export interface ApiEntitiesIdDeleteRequest {
    id: string;
}

export interface ApiEntitiesIdGetRequest {
    id: string;
}

export interface ApiEntitiesIdPatchRequest {
    id: string;
    entityEntityUpdate: EntityEntityUpdate;
}

export interface ApiEntitiesPostRequest {
    entityJsonhalEntityCreate: EntityJsonhalEntityCreate;
}

/**
 * 
 */
export class EntityApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiEntitiesGetCollection without sending the request
     */
    async apiEntitiesGetCollectionRequestOpts(requestParameters: ApiEntitiesGetCollectionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['qid'] != null) {
            queryParameters['qid'] = requestParameters['qid'];
        }

        if (requestParameters['_private'] != null) {
            queryParameters['private'] = requestParameters['_private'];
        }

        if (requestParameters['owned'] != null) {
            queryParameters['owned'] = requestParameters['owned'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['properties'] != null) {
            queryParameters['properties[]'] = requestParameters['properties'];
        }

        if (requestParameters['definition'] != null) {
            queryParameters['definition'] = requestParameters['definition'];
        }

        if (requestParameters['parent'] != null) {
            queryParameters['parent'] = requestParameters['parent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/entities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the collection of entity resources.
     * Retrieves the collection of entity resources.
     */
    async apiEntitiesGetCollectionRaw(requestParameters: ApiEntitiesGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEntitiesGetCollection200Response>> {
        const requestOptions = await this.apiEntitiesGetCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiEntitiesGetCollection200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the collection of entity resources.
     * Retrieves the collection of entity resources.
     */
    async apiEntitiesGetCollection(requestParameters: ApiEntitiesGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEntitiesGetCollection200Response> {
        const response = await this.apiEntitiesGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiEntitiesIdDelete without sending the request
     */
    async apiEntitiesIdDeleteRequestOpts(requestParameters: ApiEntitiesIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiEntitiesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/entities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes the entity resource.
     * Removes the entity resource.
     */
    async apiEntitiesIdDeleteRaw(requestParameters: ApiEntitiesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiEntitiesIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the entity resource.
     * Removes the entity resource.
     */
    async apiEntitiesIdDelete(requestParameters: ApiEntitiesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiEntitiesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiEntitiesIdGet without sending the request
     */
    async apiEntitiesIdGetRequestOpts(requestParameters: ApiEntitiesIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiEntitiesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/entities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a entity resource.
     * Retrieves a entity resource.
     */
    async apiEntitiesIdGetRaw(requestParameters: ApiEntitiesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityJsonhalEntityReadEntityReadParent>> {
        const requestOptions = await this.apiEntitiesIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityJsonhalEntityReadEntityReadParentFromJSON(jsonValue));
    }

    /**
     * Retrieves a entity resource.
     * Retrieves a entity resource.
     */
    async apiEntitiesIdGet(requestParameters: ApiEntitiesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityJsonhalEntityReadEntityReadParent> {
        const response = await this.apiEntitiesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiEntitiesIdPatch without sending the request
     */
    async apiEntitiesIdPatchRequestOpts(requestParameters: ApiEntitiesIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiEntitiesIdPatch().'
            );
        }

        if (requestParameters['entityEntityUpdate'] == null) {
            throw new runtime.RequiredError(
                'entityEntityUpdate',
                'Required parameter "entityEntityUpdate" was null or undefined when calling apiEntitiesIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/entities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EntityEntityUpdateToJSON(requestParameters['entityEntityUpdate']),
        };
    }

    /**
     * Updates the entity resource.
     * Updates the entity resource.
     */
    async apiEntitiesIdPatchRaw(requestParameters: ApiEntitiesIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityJsonhalEntityReadEntityReadParent>> {
        const requestOptions = await this.apiEntitiesIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityJsonhalEntityReadEntityReadParentFromJSON(jsonValue));
    }

    /**
     * Updates the entity resource.
     * Updates the entity resource.
     */
    async apiEntitiesIdPatch(requestParameters: ApiEntitiesIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityJsonhalEntityReadEntityReadParent> {
        const response = await this.apiEntitiesIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiEntitiesPost without sending the request
     */
    async apiEntitiesPostRequestOpts(requestParameters: ApiEntitiesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['entityJsonhalEntityCreate'] == null) {
            throw new runtime.RequiredError(
                'entityJsonhalEntityCreate',
                'Required parameter "entityJsonhalEntityCreate" was null or undefined when calling apiEntitiesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/hal+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/entities`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EntityJsonhalEntityCreateToJSON(requestParameters['entityJsonhalEntityCreate']),
        };
    }

    /**
     * Creates a entity resource.
     * Creates a entity resource.
     */
    async apiEntitiesPostRaw(requestParameters: ApiEntitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityJsonhalEntityReadEntityReadParent>> {
        const requestOptions = await this.apiEntitiesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityJsonhalEntityReadEntityReadParentFromJSON(jsonValue));
    }

    /**
     * Creates a entity resource.
     * Creates a entity resource.
     */
    async apiEntitiesPost(requestParameters: ApiEntitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityJsonhalEntityReadEntityReadParent> {
        const response = await this.apiEntitiesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
