/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Oauth2Jwks200Response,
  Oauth2Metadata200Response,
  Oauth2Register201Response,
  Oauth2Register400Response,
  Oauth2RegisterRequest,
  Oauth2Token200Response,
  Oauth2TokenExchange200Response,
} from '../models/index';
import {
    Oauth2Jwks200ResponseFromJSON,
    Oauth2Jwks200ResponseToJSON,
    Oauth2Metadata200ResponseFromJSON,
    Oauth2Metadata200ResponseToJSON,
    Oauth2Register201ResponseFromJSON,
    Oauth2Register201ResponseToJSON,
    Oauth2Register400ResponseFromJSON,
    Oauth2Register400ResponseToJSON,
    Oauth2RegisterRequestFromJSON,
    Oauth2RegisterRequestToJSON,
    Oauth2Token200ResponseFromJSON,
    Oauth2Token200ResponseToJSON,
    Oauth2TokenExchange200ResponseFromJSON,
    Oauth2TokenExchange200ResponseToJSON,
} from '../models/index';

export interface Oauth2AuthorizeRequest {
    responseType: Oauth2AuthorizeResponseTypeEnum;
    clientId: string;
    redirectUri: string;
    scope: string;
    state: string;
    codeChallenge: string;
    codeChallengeMethod: Oauth2AuthorizeCodeChallengeMethodEnum;
    resource?: string;
    audience?: string;
}

export interface Oauth2RegisterOperationRequest {
    oauth2RegisterRequest: Oauth2RegisterRequest;
}

export interface Oauth2RevokeRequest {
    token: string;
    clientId: string;
    clientSecret?: string;
    audience?: string;
}

export interface Oauth2TokenRequest {
    grantType: Oauth2TokenGrantTypeEnum;
    code: string;
    redirectUri: string;
    clientId: string;
    codeVerifier: string;
}

export interface Oauth2TokenExchangeRequest {
    grantType: string;
    clientId: string;
    subjectToken: string;
    subjectTokenType: string;
    audience: Oauth2TokenExchangeAudienceEnum;
    clientSecret?: string;
    subjectAudience?: string;
}

/**
 * 
 */
export class Oauth2Api extends runtime.BaseAPI {

    /**
     * Creates request options for oauth2Authorize without sending the request
     */
    async oauth2AuthorizeRequestOpts(requestParameters: Oauth2AuthorizeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['responseType'] == null) {
            throw new runtime.RequiredError(
                'responseType',
                'Required parameter "responseType" was null or undefined when calling oauth2Authorize().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling oauth2Authorize().'
            );
        }

        if (requestParameters['redirectUri'] == null) {
            throw new runtime.RequiredError(
                'redirectUri',
                'Required parameter "redirectUri" was null or undefined when calling oauth2Authorize().'
            );
        }

        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling oauth2Authorize().'
            );
        }

        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling oauth2Authorize().'
            );
        }

        if (requestParameters['codeChallenge'] == null) {
            throw new runtime.RequiredError(
                'codeChallenge',
                'Required parameter "codeChallenge" was null or undefined when calling oauth2Authorize().'
            );
        }

        if (requestParameters['codeChallengeMethod'] == null) {
            throw new runtime.RequiredError(
                'codeChallengeMethod',
                'Required parameter "codeChallengeMethod" was null or undefined when calling oauth2Authorize().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['responseType'] != null) {
            queryParameters['response_type'] = requestParameters['responseType'];
        }

        if (requestParameters['clientId'] != null) {
            queryParameters['client_id'] = requestParameters['clientId'];
        }

        if (requestParameters['redirectUri'] != null) {
            queryParameters['redirect_uri'] = requestParameters['redirectUri'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['codeChallenge'] != null) {
            queryParameters['code_challenge'] = requestParameters['codeChallenge'];
        }

        if (requestParameters['codeChallengeMethod'] != null) {
            queryParameters['code_challenge_method'] = requestParameters['codeChallengeMethod'];
        }

        if (requestParameters['resource'] != null) {
            queryParameters['resource'] = requestParameters['resource'];
        }

        if (requestParameters['audience'] != null) {
            queryParameters['audience'] = requestParameters['audience'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/authorize`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Browser endpoint for Authorization Code with PKCE. Requires a JsonHub session and consent before issuing an authorization code.
     * Start OAuth authorization
     */
    async oauth2AuthorizeRaw(requestParameters: Oauth2AuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.oauth2AuthorizeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Browser endpoint for Authorization Code with PKCE. Requires a JsonHub session and consent before issuing an authorization code.
     * Start OAuth authorization
     */
    async oauth2Authorize(requestParameters: Oauth2AuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.oauth2AuthorizeRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for oauth2Jwks without sending the request
     */
    async oauth2JwksRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/jwks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Publishes public RSA keys for local JWT validation by MCP and other resource servers.
     * Get OAuth signing keys
     */
    async oauth2JwksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Oauth2Jwks200Response>> {
        const requestOptions = await this.oauth2JwksRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Oauth2Jwks200ResponseFromJSON(jsonValue));
    }

    /**
     * Publishes public RSA keys for local JWT validation by MCP and other resource servers.
     * Get OAuth signing keys
     */
    async oauth2Jwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Oauth2Jwks200Response> {
        const response = await this.oauth2JwksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for oauth2Metadata without sending the request
     */
    async oauth2MetadataRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/.well-known/oauth-authorization-server`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Discovery document for ChatGPT/MCP OAuth2 Authorization Code with PKCE, JWKS, revocation, and token exchange.
     * OAuth2 authorization server metadata
     */
    async oauth2MetadataRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Oauth2Metadata200Response>> {
        const requestOptions = await this.oauth2MetadataRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Oauth2Metadata200ResponseFromJSON(jsonValue));
    }

    /**
     * Discovery document for ChatGPT/MCP OAuth2 Authorization Code with PKCE, JWKS, revocation, and token exchange.
     * OAuth2 authorization server metadata
     */
    async oauth2Metadata(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Oauth2Metadata200Response> {
        const response = await this.oauth2MetadataRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for oauth2Register without sending the request
     */
    async oauth2RegisterRequestOpts(requestParameters: Oauth2RegisterOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['oauth2RegisterRequest'] == null) {
            throw new runtime.RequiredError(
                'oauth2RegisterRequest',
                'Required parameter "oauth2RegisterRequest" was null or undefined when calling oauth2Register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/oauth2/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: Oauth2RegisterRequestToJSON(requestParameters['oauth2RegisterRequest']),
        };
    }

    /**
     * Controlled Dynamic Client Registration. Redirect URIs must be HTTPS, except HTTP localhost/127.0.0.1 for development.
     * Register OAuth client
     */
    async oauth2RegisterRaw(requestParameters: Oauth2RegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Oauth2Register201Response>> {
        const requestOptions = await this.oauth2RegisterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Oauth2Register201ResponseFromJSON(jsonValue));
    }

    /**
     * Controlled Dynamic Client Registration. Redirect URIs must be HTTPS, except HTTP localhost/127.0.0.1 for development.
     * Register OAuth client
     */
    async oauth2Register(requestParameters: Oauth2RegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Oauth2Register201Response> {
        const response = await this.oauth2RegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for oauth2Revoke without sending the request
     */
    async oauth2RevokeRequestOpts(requestParameters: Oauth2RevokeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling oauth2Revoke().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling oauth2Revoke().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['token'] != null) {
            formParams.append('token', requestParameters['token'] as any);
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['clientSecret'] != null) {
            formParams.append('client_secret', requestParameters['clientSecret'] as any);
        }

        if (requestParameters['audience'] != null) {
            formParams.append('audience', requestParameters['audience'] as any);
        }


        let urlPath = `/oauth2/revoke`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Revokes the matching consent grant when the token can be validated. Already-issued short-lived JWTs remain valid until expiry.
     * Revoke OAuth consent
     */
    async oauth2RevokeRaw(requestParameters: Oauth2RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.oauth2RevokeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Revokes the matching consent grant when the token can be validated. Already-issued short-lived JWTs remain valid until expiry.
     * Revoke OAuth consent
     */
    async oauth2Revoke(requestParameters: Oauth2RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.oauth2RevokeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for oauth2Token without sending the request
     */
    async oauth2TokenRequestOpts(requestParameters: Oauth2TokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['grantType'] == null) {
            throw new runtime.RequiredError(
                'grantType',
                'Required parameter "grantType" was null or undefined when calling oauth2Token().'
            );
        }

        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling oauth2Token().'
            );
        }

        if (requestParameters['redirectUri'] == null) {
            throw new runtime.RequiredError(
                'redirectUri',
                'Required parameter "redirectUri" was null or undefined when calling oauth2Token().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling oauth2Token().'
            );
        }

        if (requestParameters['codeVerifier'] == null) {
            throw new runtime.RequiredError(
                'codeVerifier',
                'Required parameter "codeVerifier" was null or undefined when calling oauth2Token().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }

        if (requestParameters['code'] != null) {
            formParams.append('code', requestParameters['code'] as any);
        }

        if (requestParameters['redirectUri'] != null) {
            formParams.append('redirect_uri', requestParameters['redirectUri'] as any);
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['codeVerifier'] != null) {
            formParams.append('code_verifier', requestParameters['codeVerifier'] as any);
        }


        let urlPath = `/oauth2/token`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Exchanges a single-use authorization code for a short-lived RS256 JWT access token. Public clients must provide the PKCE verifier.
     * Exchange authorization code
     */
    async oauth2TokenRaw(requestParameters: Oauth2TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Oauth2Token200Response>> {
        const requestOptions = await this.oauth2TokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Oauth2Token200ResponseFromJSON(jsonValue));
    }

    /**
     * Exchanges a single-use authorization code for a short-lived RS256 JWT access token. Public clients must provide the PKCE verifier.
     * Exchange authorization code
     */
    async oauth2Token(requestParameters: Oauth2TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Oauth2Token200Response> {
        const response = await this.oauth2TokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for oauth2TokenExchange without sending the request
     */
    async oauth2TokenExchangeRequestOpts(requestParameters: Oauth2TokenExchangeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['grantType'] == null) {
            throw new runtime.RequiredError(
                'grantType',
                'Required parameter "grantType" was null or undefined when calling oauth2TokenExchange().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling oauth2TokenExchange().'
            );
        }

        if (requestParameters['subjectToken'] == null) {
            throw new runtime.RequiredError(
                'subjectToken',
                'Required parameter "subjectToken" was null or undefined when calling oauth2TokenExchange().'
            );
        }

        if (requestParameters['subjectTokenType'] == null) {
            throw new runtime.RequiredError(
                'subjectTokenType',
                'Required parameter "subjectTokenType" was null or undefined when calling oauth2TokenExchange().'
            );
        }

        if (requestParameters['audience'] == null) {
            throw new runtime.RequiredError(
                'audience',
                'Required parameter "audience" was null or undefined when calling oauth2TokenExchange().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['clientSecret'] != null) {
            formParams.append('client_secret', requestParameters['clientSecret'] as any);
        }

        if (requestParameters['subjectToken'] != null) {
            formParams.append('subject_token', requestParameters['subjectToken'] as any);
        }

        if (requestParameters['subjectTokenType'] != null) {
            formParams.append('subject_token_type', requestParameters['subjectTokenType'] as any);
        }

        if (requestParameters['audience'] != null) {
            formParams.append('audience', requestParameters['audience'] as any);
        }

        if (requestParameters['subjectAudience'] != null) {
            formParams.append('subject_audience', requestParameters['subjectAudience'] as any);
        }


        let urlPath = `/oauth2/token-exchange`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * OAuth 2.0 Token Exchange style endpoint. The MCP backend authenticates as a confidential client and exchanges an MCP-audience subject token for a short-lived downstream token with aud=jsonhub-api.
     * Exchange MCP token for JsonHub API token
     */
    async oauth2TokenExchangeRaw(requestParameters: Oauth2TokenExchangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Oauth2TokenExchange200Response>> {
        const requestOptions = await this.oauth2TokenExchangeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Oauth2TokenExchange200ResponseFromJSON(jsonValue));
    }

    /**
     * OAuth 2.0 Token Exchange style endpoint. The MCP backend authenticates as a confidential client and exchanges an MCP-audience subject token for a short-lived downstream token with aud=jsonhub-api.
     * Exchange MCP token for JsonHub API token
     */
    async oauth2TokenExchange(requestParameters: Oauth2TokenExchangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Oauth2TokenExchange200Response> {
        const response = await this.oauth2TokenExchangeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const Oauth2AuthorizeResponseTypeEnum = {
    Code: 'code'
} as const;
export type Oauth2AuthorizeResponseTypeEnum = typeof Oauth2AuthorizeResponseTypeEnum[keyof typeof Oauth2AuthorizeResponseTypeEnum];
/**
 * @export
 */
export const Oauth2AuthorizeCodeChallengeMethodEnum = {
    S256: 'S256'
} as const;
export type Oauth2AuthorizeCodeChallengeMethodEnum = typeof Oauth2AuthorizeCodeChallengeMethodEnum[keyof typeof Oauth2AuthorizeCodeChallengeMethodEnum];
/**
 * @export
 */
export const Oauth2TokenGrantTypeEnum = {
    AuthorizationCode: 'authorization_code'
} as const;
export type Oauth2TokenGrantTypeEnum = typeof Oauth2TokenGrantTypeEnum[keyof typeof Oauth2TokenGrantTypeEnum];
/**
 * @export
 */
export const Oauth2TokenExchangeAudienceEnum = {
    JsonhubApi: 'jsonhub-api'
} as const;
export type Oauth2TokenExchangeAudienceEnum = typeof Oauth2TokenExchangeAudienceEnum[keyof typeof Oauth2TokenExchangeAudienceEnum];
