/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Oauth2Jsonapi,
  Oauth2JsonhalOauth2Read,
  Oauth2JsonhalOauth2Write,
  Oauth2JsonldOauth2Read,
  Oauth2JsonldOauth2Write,
  Oauth2Oauth2Read,
  Oauth2Oauth2Write,
} from '../models/index';
import {
    Oauth2JsonapiFromJSON,
    Oauth2JsonapiToJSON,
    Oauth2JsonhalOauth2ReadFromJSON,
    Oauth2JsonhalOauth2ReadToJSON,
    Oauth2JsonhalOauth2WriteFromJSON,
    Oauth2JsonhalOauth2WriteToJSON,
    Oauth2JsonldOauth2ReadFromJSON,
    Oauth2JsonldOauth2ReadToJSON,
    Oauth2JsonldOauth2WriteFromJSON,
    Oauth2JsonldOauth2WriteToJSON,
    Oauth2Oauth2ReadFromJSON,
    Oauth2Oauth2ReadToJSON,
    Oauth2Oauth2WriteFromJSON,
    Oauth2Oauth2WriteToJSON,
} from '../models/index';

export interface ApiOauth2tokenPostRequest {
    oauth2JsonldOauth2Write: Oauth2JsonldOauth2Write;
}

/**
 * 
 */
export class Oauth2Api extends runtime.BaseAPI {

    /**
     * This endpoint issues an OAuth2 token using your client credentials.
     * Retrieve an OAuth2 Token
     */
    async apiOauth2tokenPostRaw(requestParameters: ApiOauth2tokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Oauth2JsonldOauth2Read>> {
        if (requestParameters['oauth2JsonldOauth2Write'] == null) {
            throw new runtime.RequiredError(
                'oauth2JsonldOauth2Write',
                'Required parameter "oauth2JsonldOauth2Write" was null or undefined when calling apiOauth2tokenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/ld+json';


        let urlPath = `/api/oauth2/token`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: Oauth2JsonldOauth2WriteToJSON(requestParameters['oauth2JsonldOauth2Write']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Oauth2JsonldOauth2ReadFromJSON(jsonValue));
    }

    /**
     * This endpoint issues an OAuth2 token using your client credentials.
     * Retrieve an OAuth2 Token
     */
    async apiOauth2tokenPost(requestParameters: ApiOauth2tokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Oauth2JsonldOauth2Read> {
        const response = await this.apiOauth2tokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
