/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiMeapiTokensGetCollection200Response,
  ConstraintViolation,
  ConstraintViolationJsonld,
  ErrorJsonld,
  PersonalAccessTokenJsonhalPersonalAccessTokenRead,
  PersonalAccessTokenJsonhalPersonalAccessTokenReadPersonalAccessTokenCreateRead,
  PersonalAccessTokenJsonhalPersonalAccessTokenWrite,
  PersonalAccessTokenPersonalAccessTokenWriteJsonMergePatch,
} from '../models/index';
import {
    ApiMeapiTokensGetCollection200ResponseFromJSON,
    ApiMeapiTokensGetCollection200ResponseToJSON,
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
    ConstraintViolationJsonldFromJSON,
    ConstraintViolationJsonldToJSON,
    ErrorJsonldFromJSON,
    ErrorJsonldToJSON,
    PersonalAccessTokenJsonhalPersonalAccessTokenReadFromJSON,
    PersonalAccessTokenJsonhalPersonalAccessTokenReadToJSON,
    PersonalAccessTokenJsonhalPersonalAccessTokenReadPersonalAccessTokenCreateReadFromJSON,
    PersonalAccessTokenJsonhalPersonalAccessTokenReadPersonalAccessTokenCreateReadToJSON,
    PersonalAccessTokenJsonhalPersonalAccessTokenWriteFromJSON,
    PersonalAccessTokenJsonhalPersonalAccessTokenWriteToJSON,
    PersonalAccessTokenPersonalAccessTokenWriteJsonMergePatchFromJSON,
    PersonalAccessTokenPersonalAccessTokenWriteJsonMergePatchToJSON,
} from '../models/index';

export interface ApiMeapiTokensGetCollectionRequest {
    page?: number;
    limit?: number;
}

export interface ApiMeapiTokensIdDeleteRequest {
    id: string;
}

export interface ApiMeapiTokensIdPatchRequest {
    id: string;
    personalAccessTokenPersonalAccessTokenWriteJsonMergePatch: PersonalAccessTokenPersonalAccessTokenWriteJsonMergePatch;
}

export interface ApiMeapiTokensPostRequest {
    personalAccessTokenJsonhalPersonalAccessTokenWrite: PersonalAccessTokenJsonhalPersonalAccessTokenWrite;
}

/**
 * 
 */
export class PersonalAccessTokenApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiMeapiTokensGetCollection without sending the request
     */
    async apiMeapiTokensGetCollectionRequestOpts(requestParameters: ApiMeapiTokensGetCollectionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/me/api-tokens`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the collection of personal access token resources.
     * Retrieves the collection of personal access token resources.
     */
    async apiMeapiTokensGetCollectionRaw(requestParameters: ApiMeapiTokensGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiMeapiTokensGetCollection200Response>> {
        const requestOptions = await this.apiMeapiTokensGetCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiMeapiTokensGetCollection200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the collection of personal access token resources.
     * Retrieves the collection of personal access token resources.
     */
    async apiMeapiTokensGetCollection(requestParameters: ApiMeapiTokensGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiMeapiTokensGetCollection200Response> {
        const response = await this.apiMeapiTokensGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiMeapiTokensIdDelete without sending the request
     */
    async apiMeapiTokensIdDeleteRequestOpts(requestParameters: ApiMeapiTokensIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMeapiTokensIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/me/api-tokens/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes the personal access token resource.
     * Removes the personal access token resource.
     */
    async apiMeapiTokensIdDeleteRaw(requestParameters: ApiMeapiTokensIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiMeapiTokensIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the personal access token resource.
     * Removes the personal access token resource.
     */
    async apiMeapiTokensIdDelete(requestParameters: ApiMeapiTokensIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMeapiTokensIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiMeapiTokensIdPatch without sending the request
     */
    async apiMeapiTokensIdPatchRequestOpts(requestParameters: ApiMeapiTokensIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMeapiTokensIdPatch().'
            );
        }

        if (requestParameters['personalAccessTokenPersonalAccessTokenWriteJsonMergePatch'] == null) {
            throw new runtime.RequiredError(
                'personalAccessTokenPersonalAccessTokenWriteJsonMergePatch',
                'Required parameter "personalAccessTokenPersonalAccessTokenWriteJsonMergePatch" was null or undefined when calling apiMeapiTokensIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/me/api-tokens/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PersonalAccessTokenPersonalAccessTokenWriteJsonMergePatchToJSON(requestParameters['personalAccessTokenPersonalAccessTokenWriteJsonMergePatch']),
        };
    }

    /**
     * Updates the personal access token resource.
     * Updates the personal access token resource.
     */
    async apiMeapiTokensIdPatchRaw(requestParameters: ApiMeapiTokensIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonalAccessTokenJsonhalPersonalAccessTokenRead>> {
        const requestOptions = await this.apiMeapiTokensIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonalAccessTokenJsonhalPersonalAccessTokenReadFromJSON(jsonValue));
    }

    /**
     * Updates the personal access token resource.
     * Updates the personal access token resource.
     */
    async apiMeapiTokensIdPatch(requestParameters: ApiMeapiTokensIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonalAccessTokenJsonhalPersonalAccessTokenRead> {
        const response = await this.apiMeapiTokensIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiMeapiTokensPost without sending the request
     */
    async apiMeapiTokensPostRequestOpts(requestParameters: ApiMeapiTokensPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['personalAccessTokenJsonhalPersonalAccessTokenWrite'] == null) {
            throw new runtime.RequiredError(
                'personalAccessTokenJsonhalPersonalAccessTokenWrite',
                'Required parameter "personalAccessTokenJsonhalPersonalAccessTokenWrite" was null or undefined when calling apiMeapiTokensPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/hal+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/me/api-tokens`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PersonalAccessTokenJsonhalPersonalAccessTokenWriteToJSON(requestParameters['personalAccessTokenJsonhalPersonalAccessTokenWrite']),
        };
    }

    /**
     * Creates a personal access token resource.
     * Creates a personal access token resource.
     */
    async apiMeapiTokensPostRaw(requestParameters: ApiMeapiTokensPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonalAccessTokenJsonhalPersonalAccessTokenReadPersonalAccessTokenCreateRead>> {
        const requestOptions = await this.apiMeapiTokensPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonalAccessTokenJsonhalPersonalAccessTokenReadPersonalAccessTokenCreateReadFromJSON(jsonValue));
    }

    /**
     * Creates a personal access token resource.
     * Creates a personal access token resource.
     */
    async apiMeapiTokensPost(requestParameters: ApiMeapiTokensPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonalAccessTokenJsonhalPersonalAccessTokenReadPersonalAccessTokenCreateRead> {
        const response = await this.apiMeapiTokensPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
