/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConstraintViolation,
  ConstraintViolationJsonld,
  ErrorJsonld,
  UserJsonhal,
  UserJsonhalUserCreate,
  UserJsonhalUserEmpty,
  UserJsonhalUserRead,
  UserJsonhalUserResendActivation,
  UserJsonhalUserResetPassword,
  UserJsonhalUserSendResetPassword,
  UserUserUpdateJsonMergePatch,
} from '../models/index';
import {
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
    ConstraintViolationJsonldFromJSON,
    ConstraintViolationJsonldToJSON,
    ErrorJsonldFromJSON,
    ErrorJsonldToJSON,
    UserJsonhalFromJSON,
    UserJsonhalToJSON,
    UserJsonhalUserCreateFromJSON,
    UserJsonhalUserCreateToJSON,
    UserJsonhalUserEmptyFromJSON,
    UserJsonhalUserEmptyToJSON,
    UserJsonhalUserReadFromJSON,
    UserJsonhalUserReadToJSON,
    UserJsonhalUserResendActivationFromJSON,
    UserJsonhalUserResendActivationToJSON,
    UserJsonhalUserResetPasswordFromJSON,
    UserJsonhalUserResetPasswordToJSON,
    UserJsonhalUserSendResetPasswordFromJSON,
    UserJsonhalUserSendResetPasswordToJSON,
    UserUserUpdateJsonMergePatchFromJSON,
    UserUserUpdateJsonMergePatchToJSON,
} from '../models/index';

export interface ApiUsersIdDeleteRequest {
    id: string;
}

export interface ApiUsersIdPatchRequest {
    id: string;
    userUserUpdateJsonMergePatch: UserUserUpdateJsonMergePatch;
}

export interface ApiUsersPostRequest {
    userJsonhalUserCreate: UserJsonhalUserCreate;
}

export interface ApiUsersresendActivationPostRequest {
    userJsonhalUserResendActivation: UserJsonhalUserResendActivation;
}

export interface ApiUsersresetPasswordPostRequest {
    userJsonhalUserResetPassword: UserJsonhalUserResetPassword;
}

export interface ApiUserssendResetPasswordPostRequest {
    userJsonhalUserSendResetPassword: UserJsonhalUserSendResetPassword;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiUsersIdDelete without sending the request
     */
    async apiUsersIdDeleteRequestOpts(requestParameters: ApiUsersIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiUsersIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes the user resource.
     * Removes the user resource.
     */
    async apiUsersIdDeleteRaw(requestParameters: ApiUsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiUsersIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the user resource.
     * Removes the user resource.
     */
    async apiUsersIdDelete(requestParameters: ApiUsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiUsersIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiUsersIdPatch without sending the request
     */
    async apiUsersIdPatchRequestOpts(requestParameters: ApiUsersIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiUsersIdPatch().'
            );
        }

        if (requestParameters['userUserUpdateJsonMergePatch'] == null) {
            throw new runtime.RequiredError(
                'userUserUpdateJsonMergePatch',
                'Required parameter "userUserUpdateJsonMergePatch" was null or undefined when calling apiUsersIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserUserUpdateJsonMergePatchToJSON(requestParameters['userUserUpdateJsonMergePatch']),
        };
    }

    /**
     * Updates the user resource.
     * Updates the user resource.
     */
    async apiUsersIdPatchRaw(requestParameters: ApiUsersIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserJsonhalUserEmpty>> {
        const requestOptions = await this.apiUsersIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserJsonhalUserEmptyFromJSON(jsonValue));
    }

    /**
     * Updates the user resource.
     * Updates the user resource.
     */
    async apiUsersIdPatch(requestParameters: ApiUsersIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserJsonhalUserEmpty> {
        const response = await this.apiUsersIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiUsersPost without sending the request
     */
    async apiUsersPostRequestOpts(requestParameters: ApiUsersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userJsonhalUserCreate'] == null) {
            throw new runtime.RequiredError(
                'userJsonhalUserCreate',
                'Required parameter "userJsonhalUserCreate" was null or undefined when calling apiUsersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/hal+json';


        let urlPath = `/api/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserJsonhalUserCreateToJSON(requestParameters['userJsonhalUserCreate']),
        };
    }

    /**
     * Creates a user resource.
     * Creates a user resource.
     */
    async apiUsersPostRaw(requestParameters: ApiUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserJsonhalUserRead>> {
        const requestOptions = await this.apiUsersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserJsonhalUserReadFromJSON(jsonValue));
    }

    /**
     * Creates a user resource.
     * Creates a user resource.
     */
    async apiUsersPost(requestParameters: ApiUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserJsonhalUserRead> {
        const response = await this.apiUsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiUsersresendActivationPost without sending the request
     */
    async apiUsersresendActivationPostRequestOpts(requestParameters: ApiUsersresendActivationPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userJsonhalUserResendActivation'] == null) {
            throw new runtime.RequiredError(
                'userJsonhalUserResendActivation',
                'Required parameter "userJsonhalUserResendActivation" was null or undefined when calling apiUsersresendActivationPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/hal+json';


        let urlPath = `/api/users/resend-activation`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserJsonhalUserResendActivationToJSON(requestParameters['userJsonhalUserResendActivation']),
        };
    }

    /**
     * This endpoint resends the activation email to the user.
     * Resend activation email
     */
    async apiUsersresendActivationPostRaw(requestParameters: ApiUsersresendActivationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserJsonhal>> {
        const requestOptions = await this.apiUsersresendActivationPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserJsonhalFromJSON(jsonValue));
    }

    /**
     * This endpoint resends the activation email to the user.
     * Resend activation email
     */
    async apiUsersresendActivationPost(requestParameters: ApiUsersresendActivationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserJsonhal> {
        const response = await this.apiUsersresendActivationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiUsersresetPasswordPost without sending the request
     */
    async apiUsersresetPasswordPostRequestOpts(requestParameters: ApiUsersresetPasswordPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userJsonhalUserResetPassword'] == null) {
            throw new runtime.RequiredError(
                'userJsonhalUserResetPassword',
                'Required parameter "userJsonhalUserResetPassword" was null or undefined when calling apiUsersresetPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/hal+json';


        let urlPath = `/api/users/reset-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserJsonhalUserResetPasswordToJSON(requestParameters['userJsonhalUserResetPassword']),
        };
    }

    /**
     * This endpoint resets the password of the user using the token sent by email.
     * Reset password (with token)
     */
    async apiUsersresetPasswordPostRaw(requestParameters: ApiUsersresetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserJsonhalUserEmpty>> {
        const requestOptions = await this.apiUsersresetPasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserJsonhalUserEmptyFromJSON(jsonValue));
    }

    /**
     * This endpoint resets the password of the user using the token sent by email.
     * Reset password (with token)
     */
    async apiUsersresetPasswordPost(requestParameters: ApiUsersresetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserJsonhalUserEmpty> {
        const response = await this.apiUsersresetPasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiUserssendResetPasswordPost without sending the request
     */
    async apiUserssendResetPasswordPostRequestOpts(requestParameters: ApiUserssendResetPasswordPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userJsonhalUserSendResetPassword'] == null) {
            throw new runtime.RequiredError(
                'userJsonhalUserSendResetPassword',
                'Required parameter "userJsonhalUserSendResetPassword" was null or undefined when calling apiUserssendResetPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/hal+json';


        let urlPath = `/api/users/send-reset-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserJsonhalUserSendResetPasswordToJSON(requestParameters['userJsonhalUserSendResetPassword']),
        };
    }

    /**
     * This endpoint sends a reset password email to the user.
     * Send reset password email
     */
    async apiUserssendResetPasswordPostRaw(requestParameters: ApiUserssendResetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserJsonhal>> {
        const requestOptions = await this.apiUserssendResetPasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserJsonhalFromJSON(jsonValue));
    }

    /**
     * This endpoint sends a reset password email to the user.
     * Send reset password email
     */
    async apiUserssendResetPasswordPost(requestParameters: ApiUserssendResetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserJsonhal> {
        const response = await this.apiUserssendResetPasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
