/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserJsonapi,
  UserJsonhalUserCreate,
  UserJsonhalUserEmpty,
  UserJsonhalUserRead,
  UserJsonhalUserResendActivation,
  UserJsonhalUserResetPassword,
  UserJsonhalUserSendResetPassword,
  UserJsonldUserCreate,
  UserJsonldUserEmpty,
  UserJsonldUserRead,
  UserJsonldUserResendActivation,
  UserJsonldUserResetPassword,
  UserJsonldUserSendResetPassword,
  UserUserCreate,
  UserUserRead,
  UserUserResendActivation,
  UserUserResetPassword,
  UserUserSendResetPassword,
  UserUserUpdate,
} from '../models/index';
import {
    UserJsonapiFromJSON,
    UserJsonapiToJSON,
    UserJsonhalUserCreateFromJSON,
    UserJsonhalUserCreateToJSON,
    UserJsonhalUserEmptyFromJSON,
    UserJsonhalUserEmptyToJSON,
    UserJsonhalUserReadFromJSON,
    UserJsonhalUserReadToJSON,
    UserJsonhalUserResendActivationFromJSON,
    UserJsonhalUserResendActivationToJSON,
    UserJsonhalUserResetPasswordFromJSON,
    UserJsonhalUserResetPasswordToJSON,
    UserJsonhalUserSendResetPasswordFromJSON,
    UserJsonhalUserSendResetPasswordToJSON,
    UserJsonldUserCreateFromJSON,
    UserJsonldUserCreateToJSON,
    UserJsonldUserEmptyFromJSON,
    UserJsonldUserEmptyToJSON,
    UserJsonldUserReadFromJSON,
    UserJsonldUserReadToJSON,
    UserJsonldUserResendActivationFromJSON,
    UserJsonldUserResendActivationToJSON,
    UserJsonldUserResetPasswordFromJSON,
    UserJsonldUserResetPasswordToJSON,
    UserJsonldUserSendResetPasswordFromJSON,
    UserJsonldUserSendResetPasswordToJSON,
    UserUserCreateFromJSON,
    UserUserCreateToJSON,
    UserUserReadFromJSON,
    UserUserReadToJSON,
    UserUserResendActivationFromJSON,
    UserUserResendActivationToJSON,
    UserUserResetPasswordFromJSON,
    UserUserResetPasswordToJSON,
    UserUserSendResetPasswordFromJSON,
    UserUserSendResetPasswordToJSON,
    UserUserUpdateFromJSON,
    UserUserUpdateToJSON,
} from '../models/index';

export interface ApiUsersIdDeleteRequest {
    id: string;
}

export interface ApiUsersIdPatchRequest {
    id: string;
    userUserUpdate: UserUserUpdate;
}

export interface ApiUsersPostRequest {
    userJsonldUserCreate: UserJsonldUserCreate;
}

export interface ApiUsersresendActivationPostRequest {
    userJsonldUserResendActivation: UserJsonldUserResendActivation;
}

export interface ApiUsersresetPasswordPostRequest {
    userJsonldUserResetPassword: UserJsonldUserResetPassword;
}

export interface ApiUserssendResetPasswordPostRequest {
    userJsonldUserSendResetPassword: UserJsonldUserSendResetPassword;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Removes the user resource.
     * Removes the user resource.
     */
    async apiUsersIdDeleteRaw(requestParameters: ApiUsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiUsersIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the user resource.
     * Removes the user resource.
     */
    async apiUsersIdDelete(requestParameters: ApiUsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiUsersIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Updates the user resource.
     * Updates the user resource.
     */
    async apiUsersIdPatchRaw(requestParameters: ApiUsersIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserJsonldUserEmpty>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiUsersIdPatch().'
            );
        }

        if (requestParameters['userUserUpdate'] == null) {
            throw new runtime.RequiredError(
                'userUserUpdate',
                'Required parameter "userUserUpdate" was null or undefined when calling apiUsersIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserUserUpdateToJSON(requestParameters['userUserUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserJsonldUserEmptyFromJSON(jsonValue));
    }

    /**
     * Updates the user resource.
     * Updates the user resource.
     */
    async apiUsersIdPatch(requestParameters: ApiUsersIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserJsonldUserEmpty> {
        const response = await this.apiUsersIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a user resource.
     * Creates a user resource.
     */
    async apiUsersPostRaw(requestParameters: ApiUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserJsonldUserRead>> {
        if (requestParameters['userJsonldUserCreate'] == null) {
            throw new runtime.RequiredError(
                'userJsonldUserCreate',
                'Required parameter "userJsonldUserCreate" was null or undefined when calling apiUsersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/ld+json';


        let urlPath = `/api/users`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserJsonldUserCreateToJSON(requestParameters['userJsonldUserCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserJsonldUserReadFromJSON(jsonValue));
    }

    /**
     * Creates a user resource.
     * Creates a user resource.
     */
    async apiUsersPost(requestParameters: ApiUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserJsonldUserRead> {
        const response = await this.apiUsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint resends the activation email to the user.
     * Resend activation email
     */
    async apiUsersresendActivationPostRaw(requestParameters: ApiUsersresendActivationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userJsonldUserResendActivation'] == null) {
            throw new runtime.RequiredError(
                'userJsonldUserResendActivation',
                'Required parameter "userJsonldUserResendActivation" was null or undefined when calling apiUsersresendActivationPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/ld+json';


        let urlPath = `/api/users/resend-activation`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserJsonldUserResendActivationToJSON(requestParameters['userJsonldUserResendActivation']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint resends the activation email to the user.
     * Resend activation email
     */
    async apiUsersresendActivationPost(requestParameters: ApiUsersresendActivationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiUsersresendActivationPostRaw(requestParameters, initOverrides);
    }

    /**
     * This endpoint resets the password of the user using the token sent by email.
     * Reset password (with token)
     */
    async apiUsersresetPasswordPostRaw(requestParameters: ApiUsersresetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userJsonldUserResetPassword'] == null) {
            throw new runtime.RequiredError(
                'userJsonldUserResetPassword',
                'Required parameter "userJsonldUserResetPassword" was null or undefined when calling apiUsersresetPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/ld+json';


        let urlPath = `/api/users/reset-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserJsonldUserResetPasswordToJSON(requestParameters['userJsonldUserResetPassword']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint resets the password of the user using the token sent by email.
     * Reset password (with token)
     */
    async apiUsersresetPasswordPost(requestParameters: ApiUsersresetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiUsersresetPasswordPostRaw(requestParameters, initOverrides);
    }

    /**
     * This endpoint sends a reset password email to the user.
     * Send reset password email
     */
    async apiUserssendResetPasswordPostRaw(requestParameters: ApiUserssendResetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userJsonldUserSendResetPassword'] == null) {
            throw new runtime.RequiredError(
                'userJsonldUserSendResetPassword',
                'Required parameter "userJsonldUserSendResetPassword" was null or undefined when calling apiUserssendResetPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/ld+json';


        let urlPath = `/api/users/send-reset-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserJsonldUserSendResetPasswordToJSON(requestParameters['userJsonldUserSendResetPassword']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint sends a reset password email to the user.
     * Send reset password email
     */
    async apiUserssendResetPasswordPost(requestParameters: ApiUserssendResetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiUserssendResetPasswordPostRaw(requestParameters, initOverrides);
    }

}
