/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiEntitiesGetCollection200Response,
  ApiEntitiesGetCollection200Response1,
  EntityEntityCreate,
  EntityEntityReadEntityReadParent,
  EntityEntityUpdate,
  EntityJsonapi,
  EntityJsonhalEntityCreate,
  EntityJsonhalEntityReadEntityReadParent,
  EntityJsonldEntityCreate,
  EntityJsonldEntityReadEntityReadParent,
} from '../models/index';
import {
    ApiEntitiesGetCollection200ResponseFromJSON,
    ApiEntitiesGetCollection200ResponseToJSON,
    ApiEntitiesGetCollection200Response1FromJSON,
    ApiEntitiesGetCollection200Response1ToJSON,
    EntityEntityCreateFromJSON,
    EntityEntityCreateToJSON,
    EntityEntityReadEntityReadParentFromJSON,
    EntityEntityReadEntityReadParentToJSON,
    EntityEntityUpdateFromJSON,
    EntityEntityUpdateToJSON,
    EntityJsonapiFromJSON,
    EntityJsonapiToJSON,
    EntityJsonhalEntityCreateFromJSON,
    EntityJsonhalEntityCreateToJSON,
    EntityJsonhalEntityReadEntityReadParentFromJSON,
    EntityJsonhalEntityReadEntityReadParentToJSON,
    EntityJsonldEntityCreateFromJSON,
    EntityJsonldEntityCreateToJSON,
    EntityJsonldEntityReadEntityReadParentFromJSON,
    EntityJsonldEntityReadEntityReadParentToJSON,
} from '../models/index';

export interface ApiEntitiesGetCollectionRequest {
    qid?: string;
    _private?: boolean;
    owned?: boolean;
    page?: number;
    limit?: number;
    properties?: Array<string>;
    definition?: string;
    parent?: string;
}

export interface ApiEntitiesIdDeleteRequest {
    id: string;
}

export interface ApiEntitiesIdGetRequest {
    id: string;
}

export interface ApiEntitiesIdPatchRequest {
    id: string;
    entityEntityUpdate: EntityEntityUpdate;
}

export interface ApiEntitiesPostRequest {
    entityJsonldEntityCreate: EntityJsonldEntityCreate;
}

/**
 * 
 */
export class EntityApi extends runtime.BaseAPI {

    /**
     * Retrieves the collection of entity resources.
     * Retrieves the collection of entity resources.
     */
    async apiEntitiesGetCollectionRaw(requestParameters: ApiEntitiesGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEntitiesGetCollection200Response>> {
        const queryParameters: any = {};

        if (requestParameters['qid'] != null) {
            queryParameters['qid'] = requestParameters['qid'];
        }

        if (requestParameters['_private'] != null) {
            queryParameters['private'] = requestParameters['_private'];
        }

        if (requestParameters['owned'] != null) {
            queryParameters['owned'] = requestParameters['owned'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['properties'] != null) {
            queryParameters['properties[]'] = requestParameters['properties'];
        }

        if (requestParameters['definition'] != null) {
            queryParameters['definition'] = requestParameters['definition'];
        }

        if (requestParameters['parent'] != null) {
            queryParameters['parent'] = requestParameters['parent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entities`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiEntitiesGetCollection200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the collection of entity resources.
     * Retrieves the collection of entity resources.
     */
    async apiEntitiesGetCollection(requestParameters: ApiEntitiesGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEntitiesGetCollection200Response> {
        const response = await this.apiEntitiesGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the entity resource.
     * Removes the entity resource.
     */
    async apiEntitiesIdDeleteRaw(requestParameters: ApiEntitiesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiEntitiesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entities/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the entity resource.
     * Removes the entity resource.
     */
    async apiEntitiesIdDelete(requestParameters: ApiEntitiesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiEntitiesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a entity resource.
     * Retrieves a entity resource.
     */
    async apiEntitiesIdGetRaw(requestParameters: ApiEntitiesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityJsonldEntityReadEntityReadParent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiEntitiesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entities/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityJsonldEntityReadEntityReadParentFromJSON(jsonValue));
    }

    /**
     * Retrieves a entity resource.
     * Retrieves a entity resource.
     */
    async apiEntitiesIdGet(requestParameters: ApiEntitiesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityJsonldEntityReadEntityReadParent> {
        const response = await this.apiEntitiesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the entity resource.
     * Updates the entity resource.
     */
    async apiEntitiesIdPatchRaw(requestParameters: ApiEntitiesIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityJsonldEntityReadEntityReadParent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiEntitiesIdPatch().'
            );
        }

        if (requestParameters['entityEntityUpdate'] == null) {
            throw new runtime.RequiredError(
                'entityEntityUpdate',
                'Required parameter "entityEntityUpdate" was null or undefined when calling apiEntitiesIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entities/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EntityEntityUpdateToJSON(requestParameters['entityEntityUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityJsonldEntityReadEntityReadParentFromJSON(jsonValue));
    }

    /**
     * Updates the entity resource.
     * Updates the entity resource.
     */
    async apiEntitiesIdPatch(requestParameters: ApiEntitiesIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityJsonldEntityReadEntityReadParent> {
        const response = await this.apiEntitiesIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a entity resource.
     * Creates a entity resource.
     */
    async apiEntitiesPostRaw(requestParameters: ApiEntitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityJsonldEntityReadEntityReadParent>> {
        if (requestParameters['entityJsonldEntityCreate'] == null) {
            throw new runtime.RequiredError(
                'entityJsonldEntityCreate',
                'Required parameter "entityJsonldEntityCreate" was null or undefined when calling apiEntitiesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/ld+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entities`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EntityJsonldEntityCreateToJSON(requestParameters['entityJsonldEntityCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityJsonldEntityReadEntityReadParentFromJSON(jsonValue));
    }

    /**
     * Creates a entity resource.
     * Creates a entity resource.
     */
    async apiEntitiesPost(requestParameters: ApiEntitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityJsonldEntityReadEntityReadParent> {
        const response = await this.apiEntitiesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
