/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JsonHubApi);
  }
}(this, function(expect, JsonHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JsonHubApi.ApiDefinitionsGetCollection200ResponseHydraSearch();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiDefinitionsGetCollection200ResponseHydraSearch', function() {
    it('should create an instance of ApiDefinitionsGetCollection200ResponseHydraSearch', function() {
      // uncomment below and update the code to test ApiDefinitionsGetCollection200ResponseHydraSearch
      //var instance = new JsonHubApi.ApiDefinitionsGetCollection200ResponseHydraSearch();
      //expect(instance).to.be.a(JsonHubApi.ApiDefinitionsGetCollection200ResponseHydraSearch);
    });

    it('should have the property type (base name: "@type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new JsonHubApi.ApiDefinitionsGetCollection200ResponseHydraSearch();
      //expect(instance).to.be();
    });

    it('should have the property hydraTemplate (base name: "hydra:template")', function() {
      // uncomment below and update the code to test the property hydraTemplate
      //var instance = new JsonHubApi.ApiDefinitionsGetCollection200ResponseHydraSearch();
      //expect(instance).to.be();
    });

    it('should have the property hydraVariableRepresentation (base name: "hydra:variableRepresentation")', function() {
      // uncomment below and update the code to test the property hydraVariableRepresentation
      //var instance = new JsonHubApi.ApiDefinitionsGetCollection200ResponseHydraSearch();
      //expect(instance).to.be();
    });

    it('should have the property hydraMapping (base name: "hydra:mapping")', function() {
      // uncomment below and update the code to test the property hydraMapping
      //var instance = new JsonHubApi.ApiDefinitionsGetCollection200ResponseHydraSearch();
      //expect(instance).to.be();
    });

  });

}));
