/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JsonHubApi);
  }
}(this, function(expect, JsonHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefinitionJsonldDefinitionRead', function() {
    it('should create an instance of DefinitionJsonldDefinitionRead', function() {
      // uncomment below and update the code to test DefinitionJsonldDefinitionRead
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be.a(JsonHubApi.DefinitionJsonldDefinitionRead);
    });

    it('should have the property context (base name: "@context")', function() {
      // uncomment below and update the code to test the property context
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "@id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "@type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be();
    });

    it('should have the property jsonSchema (base name: "jsonSchema")', function() {
      // uncomment below and update the code to test the property jsonSchema
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be();
    });

    it('should have the property parentEntity (base name: "parentEntity")', function() {
      // uncomment below and update the code to test the property parentEntity
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be();
    });

    it('should have the property isOwnedByCurrentUser (base name: "isOwnedByCurrentUser")', function() {
      // uncomment below and update the code to test the property isOwnedByCurrentUser
      //var instance = new JsonHubApi.DefinitionJsonldDefinitionRead();
      //expect(instance).to.be();
    });

  });

}));
