/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JsonHubApi);
  }
}(this, function(expect, JsonHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JsonHubApi.Oauth2Oauth2Write();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Oauth2Oauth2Write', function() {
    it('should create an instance of Oauth2Oauth2Write', function() {
      // uncomment below and update the code to test Oauth2Oauth2Write
      //var instance = new JsonHubApi.Oauth2Oauth2Write();
      //expect(instance).to.be.a(JsonHubApi.Oauth2Oauth2Write);
    });

    it('should have the property grantType (base name: "grantType")', function() {
      // uncomment below and update the code to test the property grantType
      //var instance = new JsonHubApi.Oauth2Oauth2Write();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "clientId")', function() {
      // uncomment below and update the code to test the property clientId
      //var instance = new JsonHubApi.Oauth2Oauth2Write();
      //expect(instance).to.be();
    });

    it('should have the property clientSecret (base name: "clientSecret")', function() {
      // uncomment below and update the code to test the property clientSecret
      //var instance = new JsonHubApi.Oauth2Oauth2Write();
      //expect(instance).to.be();
    });

  });

}));
