/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JsonHubApi);
  }
}(this, function(expect, JsonHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JsonHubApi.UserJsonld();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserJsonld', function() {
    it('should create an instance of UserJsonld', function() {
      // uncomment below and update the code to test UserJsonld
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be.a(JsonHubApi.UserJsonld);
    });

    it('should have the property context (base name: "@context")', function() {
      // uncomment below and update the code to test the property context
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "@id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "@type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property oldPassword (base name: "oldPassword")', function() {
      // uncomment below and update the code to test the property oldPassword
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property resetPasswordLink (base name: "resetPasswordLink")', function() {
      // uncomment below and update the code to test the property resetPasswordLink
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

    it('should have the property activationUrl (base name: "activationUrl")', function() {
      // uncomment below and update the code to test the property activationUrl
      //var instance = new JsonHubApi.UserJsonld();
      //expect(instance).to.be();
    });

  });

}));
