/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionRead } from './DefinitionJsonhalDefinitionRead';
import {
    DefinitionJsonhalDefinitionReadFromJSON,
    DefinitionJsonhalDefinitionReadFromJSONTyped,
    DefinitionJsonhalDefinitionReadToJSON,
    DefinitionJsonhalDefinitionReadToJSONTyped,
} from './DefinitionJsonhalDefinitionRead';
import type { ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf } from './ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf';
import {
    ApiDefinitionsGetCollection200ResponseEmbeddedAnyOfFromJSON,
    ApiDefinitionsGetCollection200ResponseEmbeddedAnyOfFromJSONTyped,
    ApiDefinitionsGetCollection200ResponseEmbeddedAnyOfToJSON,
    ApiDefinitionsGetCollection200ResponseEmbeddedAnyOfToJSONTyped,
} from './ApiDefinitionsGetCollection200ResponseEmbeddedAnyOf';

/**
 * 
 * @export
 * @interface ApiDefinitionsGetCollection200ResponseEmbedded
 */
export interface ApiDefinitionsGetCollection200ResponseEmbedded {
    /**
     * 
     * @type {Array<DefinitionJsonhalDefinitionRead>}
     * @memberof ApiDefinitionsGetCollection200ResponseEmbedded
     */
    item?: Array<DefinitionJsonhalDefinitionRead>;
}

/**
 * Check if a given object implements the ApiDefinitionsGetCollection200ResponseEmbedded interface.
 */
export function instanceOfApiDefinitionsGetCollection200ResponseEmbedded(value: object): value is ApiDefinitionsGetCollection200ResponseEmbedded {
    return true;
}

export function ApiDefinitionsGetCollection200ResponseEmbeddedFromJSON(json: any): ApiDefinitionsGetCollection200ResponseEmbedded {
    return ApiDefinitionsGetCollection200ResponseEmbeddedFromJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDefinitionsGetCollection200ResponseEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'item': json['item'] == null ? undefined : ((json['item'] as Array<any>).map(DefinitionJsonhalDefinitionReadFromJSON)),
    };
}

export function ApiDefinitionsGetCollection200ResponseEmbeddedToJSON(json: any): ApiDefinitionsGetCollection200ResponseEmbedded {
    return ApiDefinitionsGetCollection200ResponseEmbeddedToJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseEmbeddedToJSONTyped(value?: ApiDefinitionsGetCollection200ResponseEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': value['item'] == null ? undefined : ((value['item'] as Array<any>).map(DefinitionJsonhalDefinitionReadToJSON)),
    };
}

