/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDefinitionsGetCollection200Response1LinksSelf
 */
export interface ApiDefinitionsGetCollection200Response1LinksSelf {
    /**
     * 
     * @type {string}
     * @memberof ApiDefinitionsGetCollection200Response1LinksSelf
     */
    href?: string;
}

/**
 * Check if a given object implements the ApiDefinitionsGetCollection200Response1LinksSelf interface.
 */
export function instanceOfApiDefinitionsGetCollection200Response1LinksSelf(value: object): value is ApiDefinitionsGetCollection200Response1LinksSelf {
    return true;
}

export function ApiDefinitionsGetCollection200Response1LinksSelfFromJSON(json: any): ApiDefinitionsGetCollection200Response1LinksSelf {
    return ApiDefinitionsGetCollection200Response1LinksSelfFromJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200Response1LinksSelfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDefinitionsGetCollection200Response1LinksSelf {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'] == null ? undefined : json['href'],
    };
}

export function ApiDefinitionsGetCollection200Response1LinksSelfToJSON(json: any): ApiDefinitionsGetCollection200Response1LinksSelf {
    return ApiDefinitionsGetCollection200Response1LinksSelfToJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200Response1LinksSelfToJSONTyped(value?: ApiDefinitionsGetCollection200Response1LinksSelf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'href': value['href'],
    };
}

