/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDefinitionsGetCollection200ResponseLinksSelf
 */
export interface ApiDefinitionsGetCollection200ResponseLinksSelf {
    /**
     * 
     * @type {string}
     * @memberof ApiDefinitionsGetCollection200ResponseLinksSelf
     */
    href?: string;
}

/**
 * Check if a given object implements the ApiDefinitionsGetCollection200ResponseLinksSelf interface.
 */
export function instanceOfApiDefinitionsGetCollection200ResponseLinksSelf(value: object): value is ApiDefinitionsGetCollection200ResponseLinksSelf {
    return true;
}

export function ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON(json: any): ApiDefinitionsGetCollection200ResponseLinksSelf {
    return ApiDefinitionsGetCollection200ResponseLinksSelfFromJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseLinksSelfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDefinitionsGetCollection200ResponseLinksSelf {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'] == null ? undefined : json['href'],
    };
}

export function ApiDefinitionsGetCollection200ResponseLinksSelfToJSON(json: any): ApiDefinitionsGetCollection200ResponseLinksSelf {
    return ApiDefinitionsGetCollection200ResponseLinksSelfToJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseLinksSelfToJSONTyped(value?: ApiDefinitionsGetCollection200ResponseLinksSelf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'href': value['href'],
    };
}

