/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionRead } from './DefinitionJsonhalDefinitionRead';
import {
    DefinitionJsonhalDefinitionReadFromJSON,
    DefinitionJsonhalDefinitionReadFromJSONTyped,
    DefinitionJsonhalDefinitionReadToJSON,
    DefinitionJsonhalDefinitionReadToJSONTyped,
} from './DefinitionJsonhalDefinitionRead';

/**
 * 
 * @export
 * @interface ApiDefinitionsGetCollection200Response1EmbeddedAnyOf
 */
export interface ApiDefinitionsGetCollection200Response1EmbeddedAnyOf {
    /**
     * 
     * @type {Array<DefinitionJsonhalDefinitionRead>}
     * @memberof ApiDefinitionsGetCollection200Response1EmbeddedAnyOf
     */
    item?: Array<DefinitionJsonhalDefinitionRead>;
}

/**
 * Check if a given object implements the ApiDefinitionsGetCollection200Response1EmbeddedAnyOf interface.
 */
export function instanceOfApiDefinitionsGetCollection200Response1EmbeddedAnyOf(value: object): value is ApiDefinitionsGetCollection200Response1EmbeddedAnyOf {
    return true;
}

export function ApiDefinitionsGetCollection200Response1EmbeddedAnyOfFromJSON(json: any): ApiDefinitionsGetCollection200Response1EmbeddedAnyOf {
    return ApiDefinitionsGetCollection200Response1EmbeddedAnyOfFromJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200Response1EmbeddedAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDefinitionsGetCollection200Response1EmbeddedAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'item': json['item'] == null ? undefined : ((json['item'] as Array<any>).map(DefinitionJsonhalDefinitionReadFromJSON)),
    };
}

export function ApiDefinitionsGetCollection200Response1EmbeddedAnyOfToJSON(json: any): ApiDefinitionsGetCollection200Response1EmbeddedAnyOf {
    return ApiDefinitionsGetCollection200Response1EmbeddedAnyOfToJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200Response1EmbeddedAnyOfToJSONTyped(value?: ApiDefinitionsGetCollection200Response1EmbeddedAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': value['item'] == null ? undefined : ((value['item'] as Array<any>).map(DefinitionJsonhalDefinitionReadToJSON)),
    };
}

