/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDefinitionsGetCollection200ResponseLinksSelf } from './ApiDefinitionsGetCollection200ResponseLinksSelf';
import {
    ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON,
    ApiDefinitionsGetCollection200ResponseLinksSelfFromJSONTyped,
    ApiDefinitionsGetCollection200ResponseLinksSelfToJSON,
    ApiDefinitionsGetCollection200ResponseLinksSelfToJSONTyped,
} from './ApiDefinitionsGetCollection200ResponseLinksSelf';

/**
 * 
 * @export
 * @interface ApiDefinitionsGetCollection200ResponseLinks
 */
export interface ApiDefinitionsGetCollection200ResponseLinks {
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseLinksSelf}
     * @memberof ApiDefinitionsGetCollection200ResponseLinks
     */
    self?: ApiDefinitionsGetCollection200ResponseLinksSelf;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseLinksSelf}
     * @memberof ApiDefinitionsGetCollection200ResponseLinks
     */
    first?: ApiDefinitionsGetCollection200ResponseLinksSelf;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseLinksSelf}
     * @memberof ApiDefinitionsGetCollection200ResponseLinks
     */
    last?: ApiDefinitionsGetCollection200ResponseLinksSelf;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseLinksSelf}
     * @memberof ApiDefinitionsGetCollection200ResponseLinks
     */
    next?: ApiDefinitionsGetCollection200ResponseLinksSelf;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseLinksSelf}
     * @memberof ApiDefinitionsGetCollection200ResponseLinks
     */
    previous?: ApiDefinitionsGetCollection200ResponseLinksSelf;
}

/**
 * Check if a given object implements the ApiDefinitionsGetCollection200ResponseLinks interface.
 */
export function instanceOfApiDefinitionsGetCollection200ResponseLinks(value: object): value is ApiDefinitionsGetCollection200ResponseLinks {
    return true;
}

export function ApiDefinitionsGetCollection200ResponseLinksFromJSON(json: any): ApiDefinitionsGetCollection200ResponseLinks {
    return ApiDefinitionsGetCollection200ResponseLinksFromJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDefinitionsGetCollection200ResponseLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON(json['self']),
        'first': json['first'] == null ? undefined : ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON(json['first']),
        'last': json['last'] == null ? undefined : ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON(json['last']),
        'next': json['next'] == null ? undefined : ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON(json['next']),
        'previous': json['previous'] == null ? undefined : ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON(json['previous']),
    };
}

export function ApiDefinitionsGetCollection200ResponseLinksToJSON(json: any): ApiDefinitionsGetCollection200ResponseLinks {
    return ApiDefinitionsGetCollection200ResponseLinksToJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseLinksToJSONTyped(value?: ApiDefinitionsGetCollection200ResponseLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': ApiDefinitionsGetCollection200ResponseLinksSelfToJSON(value['self']),
        'first': ApiDefinitionsGetCollection200ResponseLinksSelfToJSON(value['first']),
        'last': ApiDefinitionsGetCollection200ResponseLinksSelfToJSON(value['last']),
        'next': ApiDefinitionsGetCollection200ResponseLinksSelfToJSON(value['next']),
        'previous': ApiDefinitionsGetCollection200ResponseLinksSelfToJSON(value['previous']),
    };
}

