/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDefinitionsGetCollection200ResponseLinks } from './ApiDefinitionsGetCollection200ResponseLinks';
import {
    ApiDefinitionsGetCollection200ResponseLinksFromJSON,
    ApiDefinitionsGetCollection200ResponseLinksFromJSONTyped,
    ApiDefinitionsGetCollection200ResponseLinksToJSON,
    ApiDefinitionsGetCollection200ResponseLinksToJSONTyped,
} from './ApiDefinitionsGetCollection200ResponseLinks';
import type { ApiDefinitionsGetCollection200ResponseEmbedded } from './ApiDefinitionsGetCollection200ResponseEmbedded';
import {
    ApiDefinitionsGetCollection200ResponseEmbeddedFromJSON,
    ApiDefinitionsGetCollection200ResponseEmbeddedFromJSONTyped,
    ApiDefinitionsGetCollection200ResponseEmbeddedToJSON,
    ApiDefinitionsGetCollection200ResponseEmbeddedToJSONTyped,
} from './ApiDefinitionsGetCollection200ResponseEmbedded';

/**
 * 
 * @export
 * @interface ApiDefinitionsGetCollection200Response
 */
export interface ApiDefinitionsGetCollection200Response {
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseEmbedded}
     * @memberof ApiDefinitionsGetCollection200Response
     */
    embedded: ApiDefinitionsGetCollection200ResponseEmbedded;
    /**
     * 
     * @type {number}
     * @memberof ApiDefinitionsGetCollection200Response
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDefinitionsGetCollection200Response
     */
    itemsPerPage?: number;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseLinks}
     * @memberof ApiDefinitionsGetCollection200Response
     */
    links: ApiDefinitionsGetCollection200ResponseLinks;
}

/**
 * Check if a given object implements the ApiDefinitionsGetCollection200Response interface.
 */
export function instanceOfApiDefinitionsGetCollection200Response(value: object): value is ApiDefinitionsGetCollection200Response {
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function ApiDefinitionsGetCollection200ResponseFromJSON(json: any): ApiDefinitionsGetCollection200Response {
    return ApiDefinitionsGetCollection200ResponseFromJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDefinitionsGetCollection200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': ApiDefinitionsGetCollection200ResponseEmbeddedFromJSON(json['_embedded']),
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'itemsPerPage': json['itemsPerPage'] == null ? undefined : json['itemsPerPage'],
        'links': ApiDefinitionsGetCollection200ResponseLinksFromJSON(json['_links']),
    };
}

export function ApiDefinitionsGetCollection200ResponseToJSON(json: any): ApiDefinitionsGetCollection200Response {
    return ApiDefinitionsGetCollection200ResponseToJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseToJSONTyped(value?: ApiDefinitionsGetCollection200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': ApiDefinitionsGetCollection200ResponseEmbeddedToJSON(value['embedded']),
        'totalItems': value['totalItems'],
        'itemsPerPage': value['itemsPerPage'],
        '_links': ApiDefinitionsGetCollection200ResponseLinksToJSON(value['links']),
    };
}

