/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityJsonhalEntityReadEntityReadParent } from './EntityJsonhalEntityReadEntityReadParent';
import {
    EntityJsonhalEntityReadEntityReadParentFromJSON,
    EntityJsonhalEntityReadEntityReadParentFromJSONTyped,
    EntityJsonhalEntityReadEntityReadParentToJSON,
    EntityJsonhalEntityReadEntityReadParentToJSONTyped,
} from './EntityJsonhalEntityReadEntityReadParent';

/**
 * 
 * @export
 * @interface ApiEntitiesGetCollection200Response1EmbeddedAnyOf
 */
export interface ApiEntitiesGetCollection200Response1EmbeddedAnyOf {
    /**
     * 
     * @type {Array<EntityJsonhalEntityReadEntityReadParent>}
     * @memberof ApiEntitiesGetCollection200Response1EmbeddedAnyOf
     */
    item?: Array<EntityJsonhalEntityReadEntityReadParent>;
}

/**
 * Check if a given object implements the ApiEntitiesGetCollection200Response1EmbeddedAnyOf interface.
 */
export function instanceOfApiEntitiesGetCollection200Response1EmbeddedAnyOf(value: object): value is ApiEntitiesGetCollection200Response1EmbeddedAnyOf {
    return true;
}

export function ApiEntitiesGetCollection200Response1EmbeddedAnyOfFromJSON(json: any): ApiEntitiesGetCollection200Response1EmbeddedAnyOf {
    return ApiEntitiesGetCollection200Response1EmbeddedAnyOfFromJSONTyped(json, false);
}

export function ApiEntitiesGetCollection200Response1EmbeddedAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEntitiesGetCollection200Response1EmbeddedAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'item': json['item'] == null ? undefined : ((json['item'] as Array<any>).map(EntityJsonhalEntityReadEntityReadParentFromJSON)),
    };
}

export function ApiEntitiesGetCollection200Response1EmbeddedAnyOfToJSON(json: any): ApiEntitiesGetCollection200Response1EmbeddedAnyOf {
    return ApiEntitiesGetCollection200Response1EmbeddedAnyOfToJSONTyped(json, false);
}

export function ApiEntitiesGetCollection200Response1EmbeddedAnyOfToJSONTyped(value?: ApiEntitiesGetCollection200Response1EmbeddedAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': value['item'] == null ? undefined : ((value['item'] as Array<any>).map(EntityJsonhalEntityReadEntityReadParentToJSON)),
    };
}

