/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiEntitiesGetCollection200ResponseEmbedded } from './ApiEntitiesGetCollection200ResponseEmbedded';
import {
    ApiEntitiesGetCollection200ResponseEmbeddedFromJSON,
    ApiEntitiesGetCollection200ResponseEmbeddedFromJSONTyped,
    ApiEntitiesGetCollection200ResponseEmbeddedToJSON,
    ApiEntitiesGetCollection200ResponseEmbeddedToJSONTyped,
} from './ApiEntitiesGetCollection200ResponseEmbedded';
import type { ApiDefinitionsGetCollection200ResponseLinks } from './ApiDefinitionsGetCollection200ResponseLinks';
import {
    ApiDefinitionsGetCollection200ResponseLinksFromJSON,
    ApiDefinitionsGetCollection200ResponseLinksFromJSONTyped,
    ApiDefinitionsGetCollection200ResponseLinksToJSON,
    ApiDefinitionsGetCollection200ResponseLinksToJSONTyped,
} from './ApiDefinitionsGetCollection200ResponseLinks';

/**
 * 
 * @export
 * @interface ApiEntitiesGetCollection200Response
 */
export interface ApiEntitiesGetCollection200Response {
    /**
     * 
     * @type {ApiEntitiesGetCollection200ResponseEmbedded}
     * @memberof ApiEntitiesGetCollection200Response
     */
    embedded: ApiEntitiesGetCollection200ResponseEmbedded;
    /**
     * 
     * @type {number}
     * @memberof ApiEntitiesGetCollection200Response
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiEntitiesGetCollection200Response
     */
    itemsPerPage?: number;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseLinks}
     * @memberof ApiEntitiesGetCollection200Response
     */
    links: ApiDefinitionsGetCollection200ResponseLinks;
}

/**
 * Check if a given object implements the ApiEntitiesGetCollection200Response interface.
 */
export function instanceOfApiEntitiesGetCollection200Response(value: object): value is ApiEntitiesGetCollection200Response {
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function ApiEntitiesGetCollection200ResponseFromJSON(json: any): ApiEntitiesGetCollection200Response {
    return ApiEntitiesGetCollection200ResponseFromJSONTyped(json, false);
}

export function ApiEntitiesGetCollection200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEntitiesGetCollection200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': ApiEntitiesGetCollection200ResponseEmbeddedFromJSON(json['_embedded']),
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'itemsPerPage': json['itemsPerPage'] == null ? undefined : json['itemsPerPage'],
        'links': ApiDefinitionsGetCollection200ResponseLinksFromJSON(json['_links']),
    };
}

export function ApiEntitiesGetCollection200ResponseToJSON(json: any): ApiEntitiesGetCollection200Response {
    return ApiEntitiesGetCollection200ResponseToJSONTyped(json, false);
}

export function ApiEntitiesGetCollection200ResponseToJSONTyped(value?: ApiEntitiesGetCollection200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': ApiEntitiesGetCollection200ResponseEmbeddedToJSON(value['embedded']),
        'totalItems': value['totalItems'],
        'itemsPerPage': value['itemsPerPage'],
        '_links': ApiDefinitionsGetCollection200ResponseLinksToJSON(value['links']),
    };
}

