/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityJsonhalEntityReadEntityReadParent } from './EntityJsonhalEntityReadEntityReadParent';
import {
    EntityJsonhalEntityReadEntityReadParentFromJSON,
    EntityJsonhalEntityReadEntityReadParentFromJSONTyped,
    EntityJsonhalEntityReadEntityReadParentToJSON,
    EntityJsonhalEntityReadEntityReadParentToJSONTyped,
} from './EntityJsonhalEntityReadEntityReadParent';
import type { HalCollectionBaseSchemaAllOfLinks } from './HalCollectionBaseSchemaAllOfLinks';
import {
    HalCollectionBaseSchemaAllOfLinksFromJSON,
    HalCollectionBaseSchemaAllOfLinksFromJSONTyped,
    HalCollectionBaseSchemaAllOfLinksToJSON,
    HalCollectionBaseSchemaAllOfLinksToJSONTyped,
} from './HalCollectionBaseSchemaAllOfLinks';

/**
 * entity.jsonhal-entity.read_entity.read.parent collection.
 * @export
 * @interface ApiEntitiesGetCollection200Response
 */
export interface ApiEntitiesGetCollection200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiEntitiesGetCollection200Response
     */
    totalItems?: number;
    /**
     * 
     * @type {{ [key: string]: Array<EntityJsonhalEntityReadEntityReadParent>; }}
     * @memberof ApiEntitiesGetCollection200Response
     */
    embedded: { [key: string]: Array<EntityJsonhalEntityReadEntityReadParent>; } | null;
    /**
     * 
     * @type {HalCollectionBaseSchemaAllOfLinks}
     * @memberof ApiEntitiesGetCollection200Response
     */
    links: HalCollectionBaseSchemaAllOfLinks;
    /**
     * 
     * @type {number}
     * @memberof ApiEntitiesGetCollection200Response
     */
    itemsPerPage?: number;
}

/**
 * Check if a given object implements the ApiEntitiesGetCollection200Response interface.
 */
export function instanceOfApiEntitiesGetCollection200Response(value: object): value is ApiEntitiesGetCollection200Response {
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function ApiEntitiesGetCollection200ResponseFromJSON(json: any): ApiEntitiesGetCollection200Response {
    return ApiEntitiesGetCollection200ResponseFromJSONTyped(json, false);
}

export function ApiEntitiesGetCollection200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEntitiesGetCollection200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'embedded': json['_embedded'],
        'links': HalCollectionBaseSchemaAllOfLinksFromJSON(json['_links']),
        'itemsPerPage': json['itemsPerPage'] == null ? undefined : json['itemsPerPage'],
    };
}

export function ApiEntitiesGetCollection200ResponseToJSON(json: any): ApiEntitiesGetCollection200Response {
    return ApiEntitiesGetCollection200ResponseToJSONTyped(json, false);
}

export function ApiEntitiesGetCollection200ResponseToJSONTyped(value?: ApiEntitiesGetCollection200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalItems': value['totalItems'],
        '_embedded': value['embedded'],
        '_links': HalCollectionBaseSchemaAllOfLinksToJSON(value['links']),
        'itemsPerPage': value['itemsPerPage'],
    };
}

