/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiUsersmeGet200ResponseLimits } from './ApiUsersmeGet200ResponseLimits';
import {
    ApiUsersmeGet200ResponseLimitsFromJSON,
    ApiUsersmeGet200ResponseLimitsFromJSONTyped,
    ApiUsersmeGet200ResponseLimitsToJSON,
    ApiUsersmeGet200ResponseLimitsToJSONTyped,
} from './ApiUsersmeGet200ResponseLimits';

/**
 * 
 * @export
 * @interface ApiUsersmeGet200Response
 */
export interface ApiUsersmeGet200Response {
    /**
     * 
     * @type {ApiUsersmeGet200ResponseLimits}
     * @memberof ApiUsersmeGet200Response
     */
    limits: ApiUsersmeGet200ResponseLimits;
}

/**
 * Check if a given object implements the ApiUsersmeGet200Response interface.
 */
export function instanceOfApiUsersmeGet200Response(value: object): value is ApiUsersmeGet200Response {
    if (!('limits' in value) || value['limits'] === undefined) return false;
    return true;
}

export function ApiUsersmeGet200ResponseFromJSON(json: any): ApiUsersmeGet200Response {
    return ApiUsersmeGet200ResponseFromJSONTyped(json, false);
}

export function ApiUsersmeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUsersmeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'limits': ApiUsersmeGet200ResponseLimitsFromJSON(json['limits']),
    };
}

export function ApiUsersmeGet200ResponseToJSON(json: any): ApiUsersmeGet200Response {
    return ApiUsersmeGet200ResponseToJSONTyped(json, false);
}

export function ApiUsersmeGet200ResponseToJSONTyped(value?: ApiUsersmeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limits': ApiUsersmeGet200ResponseLimitsToJSON(value['limits']),
    };
}

