/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiUsersmeGet200ResponseLimitsEntities
 */
export interface ApiUsersmeGet200ResponseLimitsEntities {
    /**
     * 
     * @type {number}
     * @memberof ApiUsersmeGet200ResponseLimitsEntities
     */
    used: number;
    /**
     * 
     * @type {number}
     * @memberof ApiUsersmeGet200ResponseLimitsEntities
     */
    limit: number;
}

/**
 * Check if a given object implements the ApiUsersmeGet200ResponseLimitsEntities interface.
 */
export function instanceOfApiUsersmeGet200ResponseLimitsEntities(value: object): value is ApiUsersmeGet200ResponseLimitsEntities {
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ApiUsersmeGet200ResponseLimitsEntitiesFromJSON(json: any): ApiUsersmeGet200ResponseLimitsEntities {
    return ApiUsersmeGet200ResponseLimitsEntitiesFromJSONTyped(json, false);
}

export function ApiUsersmeGet200ResponseLimitsEntitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUsersmeGet200ResponseLimitsEntities {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'],
        'limit': json['limit'],
    };
}

export function ApiUsersmeGet200ResponseLimitsEntitiesToJSON(json: any): ApiUsersmeGet200ResponseLimitsEntities {
    return ApiUsersmeGet200ResponseLimitsEntitiesToJSONTyped(json, false);
}

export function ApiUsersmeGet200ResponseLimitsEntitiesToJSONTyped(value?: ApiUsersmeGet200ResponseLimitsEntities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'used': value['used'],
        'limit': value['limit'],
    };
}

