/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiUsersmeGet200ResponseLimitsDefinitions
 */
export interface ApiUsersmeGet200ResponseLimitsDefinitions {
    /**
     * 
     * @type {number}
     * @memberof ApiUsersmeGet200ResponseLimitsDefinitions
     */
    used: number;
    /**
     * 
     * @type {number}
     * @memberof ApiUsersmeGet200ResponseLimitsDefinitions
     */
    limit: number;
}

/**
 * Check if a given object implements the ApiUsersmeGet200ResponseLimitsDefinitions interface.
 */
export function instanceOfApiUsersmeGet200ResponseLimitsDefinitions(value: object): value is ApiUsersmeGet200ResponseLimitsDefinitions {
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ApiUsersmeGet200ResponseLimitsDefinitionsFromJSON(json: any): ApiUsersmeGet200ResponseLimitsDefinitions {
    return ApiUsersmeGet200ResponseLimitsDefinitionsFromJSONTyped(json, false);
}

export function ApiUsersmeGet200ResponseLimitsDefinitionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUsersmeGet200ResponseLimitsDefinitions {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'],
        'limit': json['limit'],
    };
}

export function ApiUsersmeGet200ResponseLimitsDefinitionsToJSON(json: any): ApiUsersmeGet200ResponseLimitsDefinitions {
    return ApiUsersmeGet200ResponseLimitsDefinitionsToJSONTyped(json, false);
}

export function ApiUsersmeGet200ResponseLimitsDefinitionsToJSONTyped(value?: ApiUsersmeGet200ResponseLimitsDefinitions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'used': value['used'],
        'limit': value['limit'],
    };
}

