/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConstraintViolationViolationsInner } from './ConstraintViolationViolationsInner';
import {
    ConstraintViolationViolationsInnerFromJSON,
    ConstraintViolationViolationsInnerFromJSONTyped,
    ConstraintViolationViolationsInnerToJSON,
    ConstraintViolationViolationsInnerToJSONTyped,
} from './ConstraintViolationViolationsInner';
import type { HydraItemBaseSchemaContext } from './HydraItemBaseSchemaContext';
import {
    HydraItemBaseSchemaContextFromJSON,
    HydraItemBaseSchemaContextFromJSONTyped,
    HydraItemBaseSchemaContextToJSON,
    HydraItemBaseSchemaContextToJSONTyped,
} from './HydraItemBaseSchemaContext';

/**
 * Unprocessable entity
 * @export
 * @interface ConstraintViolationJsonld
 */
export interface ConstraintViolationJsonld {
    /**
     * 
     * @type {HydraItemBaseSchemaContext}
     * @memberof ConstraintViolationJsonld
     */
    context?: HydraItemBaseSchemaContext;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJsonld
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJsonld
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof ConstraintViolationJsonld
     */
    status?: number;
    /**
     * 
     * @type {Array<ConstraintViolationViolationsInner>}
     * @memberof ConstraintViolationJsonld
     */
    violations?: Array<ConstraintViolationViolationsInner>;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJsonld
     */
    readonly detail?: string;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJsonld
     */
    readonly description?: string;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJsonld
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJsonld
     */
    readonly title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJsonld
     */
    readonly instance?: string | null;
}

/**
 * Check if a given object implements the ConstraintViolationJsonld interface.
 */
export function instanceOfConstraintViolationJsonld(value: object): value is ConstraintViolationJsonld {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ConstraintViolationJsonldFromJSON(json: any): ConstraintViolationJsonld {
    return ConstraintViolationJsonldFromJSONTyped(json, false);
}

export function ConstraintViolationJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstraintViolationJsonld {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : HydraItemBaseSchemaContextFromJSON(json['@context']),
        'id': json['@id'],
        'type': json['@type'],
        'status': json['status'] == null ? undefined : json['status'],
        'violations': json['violations'] == null ? undefined : ((json['violations'] as Array<any>).map(ConstraintViolationViolationsInnerFromJSON)),
        'detail': json['detail'] == null ? undefined : json['detail'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'instance': json['instance'] == null ? undefined : json['instance'],
    };
}

export function ConstraintViolationJsonldToJSON(json: any): ConstraintViolationJsonld {
    return ConstraintViolationJsonldToJSONTyped(json, false);
}

export function ConstraintViolationJsonldToJSONTyped(value?: Omit<ConstraintViolationJsonld, 'detail'|'description'|'type'|'title'|'instance'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': HydraItemBaseSchemaContextToJSON(value['context']),
        '@id': value['id'],
        '@type': value['type'],
        'status': value['status'],
        'violations': value['violations'] == null ? undefined : ((value['violations'] as Array<any>).map(ConstraintViolationViolationsInnerToJSON)),
    };
}

