/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentUserLimitUsage } from './CurrentUserLimitUsage';
import {
    CurrentUserLimitUsageFromJSON,
    CurrentUserLimitUsageFromJSONTyped,
    CurrentUserLimitUsageToJSON,
    CurrentUserLimitUsageToJSONTyped,
} from './CurrentUserLimitUsage';

/**
 * 
 * @export
 * @interface CurrentUserLimits
 */
export interface CurrentUserLimits {
    /**
     * 
     * @type {CurrentUserLimitUsage}
     * @memberof CurrentUserLimits
     */
    entities: CurrentUserLimitUsage;
    /**
     * 
     * @type {CurrentUserLimitUsage}
     * @memberof CurrentUserLimits
     */
    privateEntities: CurrentUserLimitUsage;
    /**
     * 
     * @type {CurrentUserLimitUsage}
     * @memberof CurrentUserLimits
     */
    definitions: CurrentUserLimitUsage;
}

/**
 * Check if a given object implements the CurrentUserLimits interface.
 */
export function instanceOfCurrentUserLimits(value: object): value is CurrentUserLimits {
    if (!('entities' in value) || value['entities'] === undefined) return false;
    if (!('privateEntities' in value) || value['privateEntities'] === undefined) return false;
    if (!('definitions' in value) || value['definitions'] === undefined) return false;
    return true;
}

export function CurrentUserLimitsFromJSON(json: any): CurrentUserLimits {
    return CurrentUserLimitsFromJSONTyped(json, false);
}

export function CurrentUserLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'entities': CurrentUserLimitUsageFromJSON(json['entities']),
        'privateEntities': CurrentUserLimitUsageFromJSON(json['privateEntities']),
        'definitions': CurrentUserLimitUsageFromJSON(json['definitions']),
    };
}

export function CurrentUserLimitsToJSON(json: any): CurrentUserLimits {
    return CurrentUserLimitsToJSONTyped(json, false);
}

export function CurrentUserLimitsToJSONTyped(value?: CurrentUserLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entities': CurrentUserLimitUsageToJSON(value['entities']),
        'privateEntities': CurrentUserLimitUsageToJSON(value['privateEntities']),
        'definitions': CurrentUserLimitUsageToJSON(value['definitions']),
    };
}

