/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDefinitionsGetCollection200ResponseLinksSelf } from './ApiDefinitionsGetCollection200ResponseLinksSelf';
import {
    ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON,
    ApiDefinitionsGetCollection200ResponseLinksSelfFromJSONTyped,
    ApiDefinitionsGetCollection200ResponseLinksSelfToJSON,
    ApiDefinitionsGetCollection200ResponseLinksSelfToJSONTyped,
} from './ApiDefinitionsGetCollection200ResponseLinksSelf';

/**
 * 
 * @export
 * @interface DefinitionJsonhalDefinitionReadLinks
 */
export interface DefinitionJsonhalDefinitionReadLinks {
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseLinksSelf}
     * @memberof DefinitionJsonhalDefinitionReadLinks
     */
    self?: ApiDefinitionsGetCollection200ResponseLinksSelf;
}

/**
 * Check if a given object implements the DefinitionJsonhalDefinitionReadLinks interface.
 */
export function instanceOfDefinitionJsonhalDefinitionReadLinks(value: object): value is DefinitionJsonhalDefinitionReadLinks {
    return true;
}

export function DefinitionJsonhalDefinitionReadLinksFromJSON(json: any): DefinitionJsonhalDefinitionReadLinks {
    return DefinitionJsonhalDefinitionReadLinksFromJSONTyped(json, false);
}

export function DefinitionJsonhalDefinitionReadLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionJsonhalDefinitionReadLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : ApiDefinitionsGetCollection200ResponseLinksSelfFromJSON(json['self']),
    };
}

export function DefinitionJsonhalDefinitionReadLinksToJSON(json: any): DefinitionJsonhalDefinitionReadLinks {
    return DefinitionJsonhalDefinitionReadLinksToJSONTyped(json, false);
}

export function DefinitionJsonhalDefinitionReadLinksToJSONTyped(value?: DefinitionJsonhalDefinitionReadLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': ApiDefinitionsGetCollection200ResponseLinksSelfToJSON(value['self']),
    };
}

