/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefinitionJsonapiDataAttributes
 */
export interface DefinitionJsonapiDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonapiDataAttributes
     */
    readonly id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonapiDataAttributes
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof DefinitionJsonapiDataAttributes
     */
    jsonSchema: object;
}

/**
 * Check if a given object implements the DefinitionJsonapiDataAttributes interface.
 */
export function instanceOfDefinitionJsonapiDataAttributes(value: object): value is DefinitionJsonapiDataAttributes {
    if (!('jsonSchema' in value) || value['jsonSchema'] === undefined) return false;
    return true;
}

export function DefinitionJsonapiDataAttributesFromJSON(json: any): DefinitionJsonapiDataAttributes {
    return DefinitionJsonapiDataAttributesFromJSONTyped(json, false);
}

export function DefinitionJsonapiDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionJsonapiDataAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'] == null ? undefined : json['_id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'jsonSchema': json['jsonSchema'],
    };
}

export function DefinitionJsonapiDataAttributesToJSON(json: any): DefinitionJsonapiDataAttributes {
    return DefinitionJsonapiDataAttributesToJSONTyped(json, false);
}

export function DefinitionJsonapiDataAttributesToJSONTyped(value?: Omit<DefinitionJsonapiDataAttributes, '_id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'jsonSchema': value['jsonSchema'],
    };
}

