/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionReadLinks } from './DefinitionJsonhalDefinitionReadLinks';
import {
    DefinitionJsonhalDefinitionReadLinksFromJSON,
    DefinitionJsonhalDefinitionReadLinksFromJSONTyped,
    DefinitionJsonhalDefinitionReadLinksToJSON,
    DefinitionJsonhalDefinitionReadLinksToJSONTyped,
} from './DefinitionJsonhalDefinitionReadLinks';

/**
 * 
 * @export
 * @interface DefinitionJsonhalDefinitionWrite
 */
export interface DefinitionJsonhalDefinitionWrite {
    /**
     * 
     * @type {DefinitionJsonhalDefinitionReadLinks}
     * @memberof DefinitionJsonhalDefinitionWrite
     */
    links?: DefinitionJsonhalDefinitionReadLinks;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonhalDefinitionWrite
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof DefinitionJsonhalDefinitionWrite
     */
    jsonSchema: object;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonhalDefinitionWrite
     */
    parentEntity?: string | null;
}

/**
 * Check if a given object implements the DefinitionJsonhalDefinitionWrite interface.
 */
export function instanceOfDefinitionJsonhalDefinitionWrite(value: object): value is DefinitionJsonhalDefinitionWrite {
    if (!('jsonSchema' in value) || value['jsonSchema'] === undefined) return false;
    return true;
}

export function DefinitionJsonhalDefinitionWriteFromJSON(json: any): DefinitionJsonhalDefinitionWrite {
    return DefinitionJsonhalDefinitionWriteFromJSONTyped(json, false);
}

export function DefinitionJsonhalDefinitionWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionJsonhalDefinitionWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : DefinitionJsonhalDefinitionReadLinksFromJSON(json['_links']),
        'slug': json['slug'] == null ? undefined : json['slug'],
        'jsonSchema': json['jsonSchema'],
        'parentEntity': json['parentEntity'] == null ? undefined : json['parentEntity'],
    };
}

export function DefinitionJsonhalDefinitionWriteToJSON(json: any): DefinitionJsonhalDefinitionWrite {
    return DefinitionJsonhalDefinitionWriteToJSONTyped(json, false);
}

export function DefinitionJsonhalDefinitionWriteToJSONTyped(value?: DefinitionJsonhalDefinitionWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': DefinitionJsonhalDefinitionReadLinksToJSON(value['links']),
        'slug': value['slug'],
        'jsonSchema': value['jsonSchema'],
        'parentEntity': value['parentEntity'],
    };
}

