/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefinitionEntityReadEntityReadParent
 */
export interface DefinitionEntityReadEntityReadParent {
    /**
     * 
     * @type {string}
     * @memberof DefinitionEntityReadEntityReadParent
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinitionEntityReadEntityReadParent
     */
    slug?: string | null;
}

/**
 * Check if a given object implements the DefinitionEntityReadEntityReadParent interface.
 */
export function instanceOfDefinitionEntityReadEntityReadParent(value: object): value is DefinitionEntityReadEntityReadParent {
    return true;
}

export function DefinitionEntityReadEntityReadParentFromJSON(json: any): DefinitionEntityReadEntityReadParent {
    return DefinitionEntityReadEntityReadParentFromJSONTyped(json, false);
}

export function DefinitionEntityReadEntityReadParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionEntityReadEntityReadParent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function DefinitionEntityReadEntityReadParentToJSON(json: any): DefinitionEntityReadEntityReadParent {
    return DefinitionEntityReadEntityReadParentToJSONTyped(json, false);
}

export function DefinitionEntityReadEntityReadParentToJSONTyped(value?: DefinitionEntityReadEntityReadParent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
    };
}

