/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefinitionDefinitionWriteJsonMergePatch
 */
export interface DefinitionDefinitionWriteJsonMergePatch {
    /**
     * 
     * @type {string}
     * @memberof DefinitionDefinitionWriteJsonMergePatch
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof DefinitionDefinitionWriteJsonMergePatch
     */
    jsonSchema?: object;
    /**
     * 
     * @type {string}
     * @memberof DefinitionDefinitionWriteJsonMergePatch
     */
    parentEntity?: string | null;
}

/**
 * Check if a given object implements the DefinitionDefinitionWriteJsonMergePatch interface.
 */
export function instanceOfDefinitionDefinitionWriteJsonMergePatch(value: object): value is DefinitionDefinitionWriteJsonMergePatch {
    return true;
}

export function DefinitionDefinitionWriteJsonMergePatchFromJSON(json: any): DefinitionDefinitionWriteJsonMergePatch {
    return DefinitionDefinitionWriteJsonMergePatchFromJSONTyped(json, false);
}

export function DefinitionDefinitionWriteJsonMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionDefinitionWriteJsonMergePatch {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'jsonSchema': json['jsonSchema'] == null ? undefined : json['jsonSchema'],
        'parentEntity': json['parentEntity'] == null ? undefined : json['parentEntity'],
    };
}

export function DefinitionDefinitionWriteJsonMergePatchToJSON(json: any): DefinitionDefinitionWriteJsonMergePatch {
    return DefinitionDefinitionWriteJsonMergePatchToJSONTyped(json, false);
}

export function DefinitionDefinitionWriteJsonMergePatchToJSONTyped(value?: DefinitionDefinitionWriteJsonMergePatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'jsonSchema': value['jsonSchema'],
        'parentEntity': value['parentEntity'],
    };
}

