/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DefinitionJsonldDefinitionReadContextOneOf } from './DefinitionJsonldDefinitionReadContextOneOf';
import {
    instanceOfDefinitionJsonldDefinitionReadContextOneOf,
    DefinitionJsonldDefinitionReadContextOneOfFromJSON,
    DefinitionJsonldDefinitionReadContextOneOfFromJSONTyped,
    DefinitionJsonldDefinitionReadContextOneOfToJSON,
} from './DefinitionJsonldDefinitionReadContextOneOf';

/**
 * @type DefinitionJsonldDefinitionReadContext
 * 
 * @export
 */
export type DefinitionJsonldDefinitionReadContext = DefinitionJsonldDefinitionReadContextOneOf | string;

export function DefinitionJsonldDefinitionReadContextFromJSON(json: any): DefinitionJsonldDefinitionReadContext {
    return DefinitionJsonldDefinitionReadContextFromJSONTyped(json, false);
}

export function DefinitionJsonldDefinitionReadContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionJsonldDefinitionReadContext {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDefinitionJsonldDefinitionReadContextOneOf(json)) {
        return DefinitionJsonldDefinitionReadContextOneOfFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function DefinitionJsonldDefinitionReadContextToJSON(json: any): any {
    return DefinitionJsonldDefinitionReadContextToJSONTyped(json, false);
}

export function DefinitionJsonldDefinitionReadContextToJSONTyped(value?: DefinitionJsonldDefinitionReadContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDefinitionJsonldDefinitionReadContextOneOf(value)) {
        return DefinitionJsonldDefinitionReadContextOneOfToJSON(value as DefinitionJsonldDefinitionReadContextOneOf);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

