/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityEntityUpdateJsonMergePatch
 */
export interface EntityEntityUpdateJsonMergePatch {
    /**
     * 
     * @type {string}
     * @memberof EntityEntityUpdateJsonMergePatch
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof EntityEntityUpdateJsonMergePatch
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof EntityEntityUpdateJsonMergePatch
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityEntityUpdateJsonMergePatch
     */
    _private?: boolean;
}

/**
 * Check if a given object implements the EntityEntityUpdateJsonMergePatch interface.
 */
export function instanceOfEntityEntityUpdateJsonMergePatch(value: object): value is EntityEntityUpdateJsonMergePatch {
    return true;
}

export function EntityEntityUpdateJsonMergePatchFromJSON(json: any): EntityEntityUpdateJsonMergePatch {
    return EntityEntityUpdateJsonMergePatchFromJSONTyped(json, false);
}

export function EntityEntityUpdateJsonMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityEntityUpdateJsonMergePatch {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'data': json['data'] == null ? undefined : json['data'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        '_private': json['private'] == null ? undefined : json['private'],
    };
}

export function EntityEntityUpdateJsonMergePatchToJSON(json: any): EntityEntityUpdateJsonMergePatch {
    return EntityEntityUpdateJsonMergePatchToJSONTyped(json, false);
}

export function EntityEntityUpdateJsonMergePatchToJSONTyped(value?: EntityEntityUpdateJsonMergePatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'data': value['data'],
        'parent': value['parent'],
        'private': value['_private'],
    };
}

