/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityJsonldEntityCreate
 */
export interface EntityJsonldEntityCreate {
    /**
     * 
     * @type {string}
     * @memberof EntityJsonldEntityCreate
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof EntityJsonldEntityCreate
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonldEntityCreate
     */
    definition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonldEntityCreate
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonldEntityCreate
     */
    _private?: boolean;
}

/**
 * Check if a given object implements the EntityJsonldEntityCreate interface.
 */
export function instanceOfEntityJsonldEntityCreate(value: object): value is EntityJsonldEntityCreate {
    return true;
}

export function EntityJsonldEntityCreateFromJSON(json: any): EntityJsonldEntityCreate {
    return EntityJsonldEntityCreateFromJSONTyped(json, false);
}

export function EntityJsonldEntityCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityJsonldEntityCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'data': json['data'] == null ? undefined : json['data'],
        'definition': json['definition'] == null ? undefined : json['definition'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        '_private': json['private'] == null ? undefined : json['private'],
    };
}

export function EntityJsonldEntityCreateToJSON(json: any): EntityJsonldEntityCreate {
    return EntityJsonldEntityCreateToJSONTyped(json, false);
}

export function EntityJsonldEntityCreateToJSONTyped(value?: EntityJsonldEntityCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'data': value['data'],
        'definition': value['definition'],
        'parent': value['parent'],
        'private': value['_private'],
    };
}

