/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionEntityReadEntityReadParent } from './DefinitionEntityReadEntityReadParent';
import {
    DefinitionEntityReadEntityReadParentFromJSON,
    DefinitionEntityReadEntityReadParentFromJSONTyped,
    DefinitionEntityReadEntityReadParentToJSON,
    DefinitionEntityReadEntityReadParentToJSONTyped,
} from './DefinitionEntityReadEntityReadParent';

/**
 * 
 * @export
 * @interface EntityEntityReadEntityReadParent
 */
export interface EntityEntityReadEntityReadParent {
    /**
     * 
     * @type {string}
     * @memberof EntityEntityReadEntityReadParent
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityEntityReadEntityReadParent
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof EntityEntityReadEntityReadParent
     */
    data?: object;
    /**
     * 
     * @type {DefinitionEntityReadEntityReadParent}
     * @memberof EntityEntityReadEntityReadParent
     */
    definition?: DefinitionEntityReadEntityReadParent | null;
    /**
     * 
     * @type {string}
     * @memberof EntityEntityReadEntityReadParent
     */
    parent?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EntityEntityReadEntityReadParent
     */
    _private?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityEntityReadEntityReadParent
     */
    isOwnedByCurrentUser?: boolean;
}

/**
 * Check if a given object implements the EntityEntityReadEntityReadParent interface.
 */
export function instanceOfEntityEntityReadEntityReadParent(value: object): value is EntityEntityReadEntityReadParent {
    return true;
}

export function EntityEntityReadEntityReadParentFromJSON(json: any): EntityEntityReadEntityReadParent {
    return EntityEntityReadEntityReadParentFromJSONTyped(json, false);
}

export function EntityEntityReadEntityReadParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityEntityReadEntityReadParent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'data': json['data'] == null ? undefined : json['data'],
        'definition': json['definition'] == null ? undefined : DefinitionEntityReadEntityReadParentFromJSON(json['definition']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        '_private': json['private'] == null ? undefined : json['private'],
        'isOwnedByCurrentUser': json['isOwnedByCurrentUser'] == null ? undefined : json['isOwnedByCurrentUser'],
    };
}

export function EntityEntityReadEntityReadParentToJSON(json: any): EntityEntityReadEntityReadParent {
    return EntityEntityReadEntityReadParentToJSONTyped(json, false);
}

export function EntityEntityReadEntityReadParentToJSONTyped(value?: EntityEntityReadEntityReadParent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'data': value['data'],
        'definition': DefinitionEntityReadEntityReadParentToJSON(value['definition']),
        'parent': value['parent'],
        'private': value['_private'],
        'isOwnedByCurrentUser': value['isOwnedByCurrentUser'],
    };
}

