/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HalCollectionBaseSchemaNoPaginationLinks } from './HalCollectionBaseSchemaNoPaginationLinks';
import {
    HalCollectionBaseSchemaNoPaginationLinksFromJSON,
    HalCollectionBaseSchemaNoPaginationLinksFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationLinksToJSON,
    HalCollectionBaseSchemaNoPaginationLinksToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationLinks';

/**
 * 
 * @export
 * @interface EntityJsonhalEntityCreate
 */
export interface EntityJsonhalEntityCreate {
    /**
     * 
     * @type {string}
     * @memberof EntityJsonhalEntityCreate
     */
    slug?: string;
    /**
     * 
     * @type {object}
     * @memberof EntityJsonhalEntityCreate
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonhalEntityCreate
     */
    definition?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonhalEntityCreate
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonhalEntityCreate
     */
    _private?: boolean;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationLinks}
     * @memberof EntityJsonhalEntityCreate
     */
    links?: HalCollectionBaseSchemaNoPaginationLinks;
}

/**
 * Check if a given object implements the EntityJsonhalEntityCreate interface.
 */
export function instanceOfEntityJsonhalEntityCreate(value: object): value is EntityJsonhalEntityCreate {
    return true;
}

export function EntityJsonhalEntityCreateFromJSON(json: any): EntityJsonhalEntityCreate {
    return EntityJsonhalEntityCreateFromJSONTyped(json, false);
}

export function EntityJsonhalEntityCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityJsonhalEntityCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'data': json['data'] == null ? undefined : json['data'],
        'definition': json['definition'] == null ? undefined : json['definition'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        '_private': json['private'] == null ? undefined : json['private'],
        'links': json['_links'] == null ? undefined : HalCollectionBaseSchemaNoPaginationLinksFromJSON(json['_links']),
    };
}

export function EntityJsonhalEntityCreateToJSON(json: any): EntityJsonhalEntityCreate {
    return EntityJsonhalEntityCreateToJSONTyped(json, false);
}

export function EntityJsonhalEntityCreateToJSONTyped(value?: EntityJsonhalEntityCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'data': value['data'],
        'definition': value['definition'],
        'parent': value['parent'],
        'private': value['_private'],
        '_links': HalCollectionBaseSchemaNoPaginationLinksToJSON(value['links']),
    };
}

