/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionEntityReadEntityReadParent } from './DefinitionEntityReadEntityReadParent';
import {
    DefinitionEntityReadEntityReadParentFromJSON,
    DefinitionEntityReadEntityReadParentFromJSONTyped,
    DefinitionEntityReadEntityReadParentToJSON,
    DefinitionEntityReadEntityReadParentToJSONTyped,
} from './DefinitionEntityReadEntityReadParent';
import type { HalCollectionBaseSchemaNoPaginationLinks } from './HalCollectionBaseSchemaNoPaginationLinks';
import {
    HalCollectionBaseSchemaNoPaginationLinksFromJSON,
    HalCollectionBaseSchemaNoPaginationLinksFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationLinksToJSON,
    HalCollectionBaseSchemaNoPaginationLinksToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationLinks';

/**
 * 
 * @export
 * @interface EntityJsonhalEntityReadEntityReadParent
 */
export interface EntityJsonhalEntityReadEntityReadParent {
    /**
     * 
     * @type {string}
     * @memberof EntityJsonhalEntityReadEntityReadParent
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonhalEntityReadEntityReadParent
     */
    slug?: string;
    /**
     * 
     * @type {object}
     * @memberof EntityJsonhalEntityReadEntityReadParent
     */
    data?: object;
    /**
     * 
     * @type {DefinitionEntityReadEntityReadParent}
     * @memberof EntityJsonhalEntityReadEntityReadParent
     */
    definition?: DefinitionEntityReadEntityReadParent;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonhalEntityReadEntityReadParent
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonhalEntityReadEntityReadParent
     */
    _private?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonhalEntityReadEntityReadParent
     */
    isOwnedByCurrentUser?: boolean;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationLinks}
     * @memberof EntityJsonhalEntityReadEntityReadParent
     */
    links?: HalCollectionBaseSchemaNoPaginationLinks;
}

/**
 * Check if a given object implements the EntityJsonhalEntityReadEntityReadParent interface.
 */
export function instanceOfEntityJsonhalEntityReadEntityReadParent(value: object): value is EntityJsonhalEntityReadEntityReadParent {
    return true;
}

export function EntityJsonhalEntityReadEntityReadParentFromJSON(json: any): EntityJsonhalEntityReadEntityReadParent {
    return EntityJsonhalEntityReadEntityReadParentFromJSONTyped(json, false);
}

export function EntityJsonhalEntityReadEntityReadParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityJsonhalEntityReadEntityReadParent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'data': json['data'] == null ? undefined : json['data'],
        'definition': json['definition'] == null ? undefined : DefinitionEntityReadEntityReadParentFromJSON(json['definition']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        '_private': json['private'] == null ? undefined : json['private'],
        'isOwnedByCurrentUser': json['isOwnedByCurrentUser'] == null ? undefined : json['isOwnedByCurrentUser'],
        'links': json['_links'] == null ? undefined : HalCollectionBaseSchemaNoPaginationLinksFromJSON(json['_links']),
    };
}

export function EntityJsonhalEntityReadEntityReadParentToJSON(json: any): EntityJsonhalEntityReadEntityReadParent {
    return EntityJsonhalEntityReadEntityReadParentToJSONTyped(json, false);
}

export function EntityJsonhalEntityReadEntityReadParentToJSONTyped(value?: EntityJsonhalEntityReadEntityReadParent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'data': value['data'],
        'definition': DefinitionEntityReadEntityReadParentToJSON(value['definition']),
        'parent': value['parent'],
        'private': value['_private'],
        'isOwnedByCurrentUser': value['isOwnedByCurrentUser'],
        '_links': HalCollectionBaseSchemaNoPaginationLinksToJSON(value['links']),
    };
}

