/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonapi } from './DefinitionJsonapi';
import {
    DefinitionJsonapiFromJSON,
    DefinitionJsonapiFromJSONTyped,
    DefinitionJsonapiToJSON,
    DefinitionJsonapiToJSONTyped,
} from './DefinitionJsonapi';

/**
 * 
 * @export
 * @interface EntityJsonapi
 */
export interface EntityJsonapi {
    /**
     * 
     * @type {string}
     * @memberof EntityJsonapi
     */
    readonly id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonapi
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof EntityJsonapi
     */
    data?: object;
    /**
     * 
     * @type {DefinitionJsonapi}
     * @memberof EntityJsonapi
     */
    readonly definition?: DefinitionJsonapi | null;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonapi
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonapi
     */
    _private?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonapi
     */
    readonly isOwnedByCurrentUser?: boolean;
}

/**
 * Check if a given object implements the EntityJsonapi interface.
 */
export function instanceOfEntityJsonapi(value: object): value is EntityJsonapi {
    return true;
}

export function EntityJsonapiFromJSON(json: any): EntityJsonapi {
    return EntityJsonapiFromJSONTyped(json, false);
}

export function EntityJsonapiFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityJsonapi {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'data': json['data'] == null ? undefined : json['data'],
        'definition': json['definition'] == null ? undefined : DefinitionJsonapiFromJSON(json['definition']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        '_private': json['private'] == null ? undefined : json['private'],
        'isOwnedByCurrentUser': json['isOwnedByCurrentUser'] == null ? undefined : json['isOwnedByCurrentUser'],
    };
}

export function EntityJsonapiToJSON(json: any): EntityJsonapi {
    return EntityJsonapiToJSONTyped(json, false);
}

export function EntityJsonapiToJSONTyped(value?: Omit<EntityJsonapi, 'id'|'definition'|'isOwnedByCurrentUser'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'data': value['data'],
        'parent': value['parent'],
        'private': value['_private'],
    };
}

