/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonldEntityReadEntityReadParent } from './DefinitionJsonldEntityReadEntityReadParent';
import {
    DefinitionJsonldEntityReadEntityReadParentFromJSON,
    DefinitionJsonldEntityReadEntityReadParentFromJSONTyped,
    DefinitionJsonldEntityReadEntityReadParentToJSON,
    DefinitionJsonldEntityReadEntityReadParentToJSONTyped,
} from './DefinitionJsonldEntityReadEntityReadParent';
import type { DefinitionJsonldDefinitionReadContext } from './DefinitionJsonldDefinitionReadContext';
import {
    DefinitionJsonldDefinitionReadContextFromJSON,
    DefinitionJsonldDefinitionReadContextFromJSONTyped,
    DefinitionJsonldDefinitionReadContextToJSON,
    DefinitionJsonldDefinitionReadContextToJSONTyped,
} from './DefinitionJsonldDefinitionReadContext';

/**
 * 
 * @export
 * @interface EntityJsonldEntityReadEntityReadParent
 */
export interface EntityJsonldEntityReadEntityReadParent {
    /**
     * 
     * @type {DefinitionJsonldDefinitionReadContext}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    context?: DefinitionJsonldDefinitionReadContext;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    data?: object;
    /**
     * 
     * @type {DefinitionJsonldEntityReadEntityReadParent}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    definition?: DefinitionJsonldEntityReadEntityReadParent | null;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    _private?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonldEntityReadEntityReadParent
     */
    isOwnedByCurrentUser?: boolean;
}

/**
 * Check if a given object implements the EntityJsonldEntityReadEntityReadParent interface.
 */
export function instanceOfEntityJsonldEntityReadEntityReadParent(value: object): value is EntityJsonldEntityReadEntityReadParent {
    return true;
}

export function EntityJsonldEntityReadEntityReadParentFromJSON(json: any): EntityJsonldEntityReadEntityReadParent {
    return EntityJsonldEntityReadEntityReadParentFromJSONTyped(json, false);
}

export function EntityJsonldEntityReadEntityReadParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityJsonldEntityReadEntityReadParent {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : DefinitionJsonldDefinitionReadContextFromJSON(json['@context']),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'data': json['data'] == null ? undefined : json['data'],
        'definition': json['definition'] == null ? undefined : DefinitionJsonldEntityReadEntityReadParentFromJSON(json['definition']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        '_private': json['private'] == null ? undefined : json['private'],
        'isOwnedByCurrentUser': json['isOwnedByCurrentUser'] == null ? undefined : json['isOwnedByCurrentUser'],
    };
}

export function EntityJsonldEntityReadEntityReadParentToJSON(json: any): EntityJsonldEntityReadEntityReadParent {
    return EntityJsonldEntityReadEntityReadParentToJSONTyped(json, false);
}

export function EntityJsonldEntityReadEntityReadParentToJSONTyped(value?: Omit<EntityJsonldEntityReadEntityReadParent, '@id'|'@type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': DefinitionJsonldDefinitionReadContextToJSON(value['context']),
        'id': value['id'],
        'slug': value['slug'],
        'data': value['data'],
        'definition': DefinitionJsonldEntityReadEntityReadParentToJSON(value['definition']),
        'parent': value['parent'],
        'private': value['_private'],
        'isOwnedByCurrentUser': value['isOwnedByCurrentUser'],
    };
}

