/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HydraItemBaseSchemaContext } from './HydraItemBaseSchemaContext';
import {
    HydraItemBaseSchemaContextFromJSON,
    HydraItemBaseSchemaContextFromJSONTyped,
    HydraItemBaseSchemaContextToJSON,
    HydraItemBaseSchemaContextToJSONTyped,
} from './HydraItemBaseSchemaContext';

/**
 * A representation of common errors.
 * @export
 * @interface ErrorJsonld
 */
export interface ErrorJsonld {
    /**
     * 
     * @type {HydraItemBaseSchemaContext}
     * @memberof ErrorJsonld
     */
    context?: HydraItemBaseSchemaContext;
    /**
     * 
     * @type {string}
     * @memberof ErrorJsonld
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorJsonld
     */
    type: string;
    /**
     * A short, human-readable summary of the problem.
     * @type {string}
     * @memberof ErrorJsonld
     */
    readonly title?: string | null;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof ErrorJsonld
     */
    readonly detail?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ErrorJsonld
     */
    status?: number | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     * @type {string}
     * @memberof ErrorJsonld
     */
    readonly instance?: string | null;
    /**
     * A URI reference that identifies the problem type
     * @type {string}
     * @memberof ErrorJsonld
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorJsonld
     */
    readonly description?: string | null;
}

/**
 * Check if a given object implements the ErrorJsonld interface.
 */
export function instanceOfErrorJsonld(value: object): value is ErrorJsonld {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ErrorJsonldFromJSON(json: any): ErrorJsonld {
    return ErrorJsonldFromJSONTyped(json, false);
}

export function ErrorJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorJsonld {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : HydraItemBaseSchemaContextFromJSON(json['@context']),
        'id': json['@id'],
        'type': json['@type'],
        'title': json['title'] == null ? undefined : json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'status': json['status'] == null ? undefined : json['status'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ErrorJsonldToJSON(json: any): ErrorJsonld {
    return ErrorJsonldToJSONTyped(json, false);
}

export function ErrorJsonldToJSONTyped(value?: Omit<ErrorJsonld, 'title'|'detail'|'instance'|'type'|'description'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': HydraItemBaseSchemaContextToJSON(value['context']),
        '@id': value['id'],
        '@type': value['type'],
        'status': value['status'],
    };
}

