/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HalCollectionBaseSchemaAllOfLinksFirst
 */
export interface HalCollectionBaseSchemaAllOfLinksFirst {
    /**
     * 
     * @type {string}
     * @memberof HalCollectionBaseSchemaAllOfLinksFirst
     */
    href?: string;
}

/**
 * Check if a given object implements the HalCollectionBaseSchemaAllOfLinksFirst interface.
 */
export function instanceOfHalCollectionBaseSchemaAllOfLinksFirst(value: object): value is HalCollectionBaseSchemaAllOfLinksFirst {
    return true;
}

export function HalCollectionBaseSchemaAllOfLinksFirstFromJSON(json: any): HalCollectionBaseSchemaAllOfLinksFirst {
    return HalCollectionBaseSchemaAllOfLinksFirstFromJSONTyped(json, false);
}

export function HalCollectionBaseSchemaAllOfLinksFirstFromJSONTyped(json: any, ignoreDiscriminator: boolean): HalCollectionBaseSchemaAllOfLinksFirst {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'] == null ? undefined : json['href'],
    };
}

export function HalCollectionBaseSchemaAllOfLinksFirstToJSON(json: any): HalCollectionBaseSchemaAllOfLinksFirst {
    return HalCollectionBaseSchemaAllOfLinksFirstToJSONTyped(json, false);
}

export function HalCollectionBaseSchemaAllOfLinksFirstToJSONTyped(value?: HalCollectionBaseSchemaAllOfLinksFirst | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'href': value['href'],
    };
}

