/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HalCollectionBaseSchemaNoPaginationEmbedded } from './HalCollectionBaseSchemaNoPaginationEmbedded';
import {
    HalCollectionBaseSchemaNoPaginationEmbeddedFromJSON,
    HalCollectionBaseSchemaNoPaginationEmbeddedFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationEmbeddedToJSON,
    HalCollectionBaseSchemaNoPaginationEmbeddedToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationEmbedded';
import type { HalCollectionBaseSchemaNoPaginationLinks } from './HalCollectionBaseSchemaNoPaginationLinks';
import {
    HalCollectionBaseSchemaNoPaginationLinksFromJSON,
    HalCollectionBaseSchemaNoPaginationLinksFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationLinksToJSON,
    HalCollectionBaseSchemaNoPaginationLinksToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationLinks';

/**
 * 
 * @export
 * @interface HalCollectionBaseSchemaNoPagination
 */
export interface HalCollectionBaseSchemaNoPagination {
    /**
     * 
     * @type {number}
     * @memberof HalCollectionBaseSchemaNoPagination
     */
    totalItems?: number;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationEmbedded}
     * @memberof HalCollectionBaseSchemaNoPagination
     */
    embedded: HalCollectionBaseSchemaNoPaginationEmbedded;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationLinks}
     * @memberof HalCollectionBaseSchemaNoPagination
     */
    links: HalCollectionBaseSchemaNoPaginationLinks;
}

/**
 * Check if a given object implements the HalCollectionBaseSchemaNoPagination interface.
 */
export function instanceOfHalCollectionBaseSchemaNoPagination(value: object): value is HalCollectionBaseSchemaNoPagination {
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function HalCollectionBaseSchemaNoPaginationFromJSON(json: any): HalCollectionBaseSchemaNoPagination {
    return HalCollectionBaseSchemaNoPaginationFromJSONTyped(json, false);
}

export function HalCollectionBaseSchemaNoPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): HalCollectionBaseSchemaNoPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'embedded': HalCollectionBaseSchemaNoPaginationEmbeddedFromJSON(json['_embedded']),
        'links': HalCollectionBaseSchemaNoPaginationLinksFromJSON(json['_links']),
    };
}

export function HalCollectionBaseSchemaNoPaginationToJSON(json: any): HalCollectionBaseSchemaNoPagination {
    return HalCollectionBaseSchemaNoPaginationToJSONTyped(json, false);
}

export function HalCollectionBaseSchemaNoPaginationToJSONTyped(value?: HalCollectionBaseSchemaNoPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalItems': value['totalItems'],
        '_embedded': HalCollectionBaseSchemaNoPaginationEmbeddedToJSON(value['embedded']),
        '_links': HalCollectionBaseSchemaNoPaginationLinksToJSON(value['links']),
    };
}

