/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf
 */
export interface HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf {
    /**
     * 
     * @type {Array<any>}
     * @memberof HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf
     */
    item?: Array<any>;
}

/**
 * Check if a given object implements the HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf interface.
 */
export function instanceOfHalCollectionBaseSchemaNoPaginationEmbeddedAnyOf(value: object): value is HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf {
    return true;
}

export function HalCollectionBaseSchemaNoPaginationEmbeddedAnyOfFromJSON(json: any): HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf {
    return HalCollectionBaseSchemaNoPaginationEmbeddedAnyOfFromJSONTyped(json, false);
}

export function HalCollectionBaseSchemaNoPaginationEmbeddedAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'item': json['item'] == null ? undefined : json['item'],
    };
}

export function HalCollectionBaseSchemaNoPaginationEmbeddedAnyOfToJSON(json: any): HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf {
    return HalCollectionBaseSchemaNoPaginationEmbeddedAnyOfToJSONTyped(json, false);
}

export function HalCollectionBaseSchemaNoPaginationEmbeddedAnyOfToJSONTyped(value?: HalCollectionBaseSchemaNoPaginationEmbeddedAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': value['item'],
    };
}

