/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Oauth2Jwks200ResponseKeysInner
 */
export interface Oauth2Jwks200ResponseKeysInner {
    /**
     * 
     * @type {string}
     * @memberof Oauth2Jwks200ResponseKeysInner
     */
    kty?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2Jwks200ResponseKeysInner
     */
    use?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2Jwks200ResponseKeysInner
     */
    kid?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2Jwks200ResponseKeysInner
     */
    alg?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2Jwks200ResponseKeysInner
     */
    n?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2Jwks200ResponseKeysInner
     */
    e?: string;
}

/**
 * Check if a given object implements the Oauth2Jwks200ResponseKeysInner interface.
 */
export function instanceOfOauth2Jwks200ResponseKeysInner(value: object): value is Oauth2Jwks200ResponseKeysInner {
    return true;
}

export function Oauth2Jwks200ResponseKeysInnerFromJSON(json: any): Oauth2Jwks200ResponseKeysInner {
    return Oauth2Jwks200ResponseKeysInnerFromJSONTyped(json, false);
}

export function Oauth2Jwks200ResponseKeysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oauth2Jwks200ResponseKeysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'kty': json['kty'] == null ? undefined : json['kty'],
        'use': json['use'] == null ? undefined : json['use'],
        'kid': json['kid'] == null ? undefined : json['kid'],
        'alg': json['alg'] == null ? undefined : json['alg'],
        'n': json['n'] == null ? undefined : json['n'],
        'e': json['e'] == null ? undefined : json['e'],
    };
}

export function Oauth2Jwks200ResponseKeysInnerToJSON(json: any): Oauth2Jwks200ResponseKeysInner {
    return Oauth2Jwks200ResponseKeysInnerToJSONTyped(json, false);
}

export function Oauth2Jwks200ResponseKeysInnerToJSONTyped(value?: Oauth2Jwks200ResponseKeysInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kty': value['kty'],
        'use': value['use'],
        'kid': value['kid'],
        'alg': value['alg'],
        'n': value['n'],
        'e': value['e'],
    };
}

