/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Oauth2TokenExchange200Response
 */
export interface Oauth2TokenExchange200Response {
    /**
     * 
     * @type {string}
     * @memberof Oauth2TokenExchange200Response
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2TokenExchange200Response
     */
    tokenType?: string;
    /**
     * 
     * @type {number}
     * @memberof Oauth2TokenExchange200Response
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof Oauth2TokenExchange200Response
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2TokenExchange200Response
     */
    issuedTokenType?: string;
}

/**
 * Check if a given object implements the Oauth2TokenExchange200Response interface.
 */
export function instanceOfOauth2TokenExchange200Response(value: object): value is Oauth2TokenExchange200Response {
    return true;
}

export function Oauth2TokenExchange200ResponseFromJSON(json: any): Oauth2TokenExchange200Response {
    return Oauth2TokenExchange200ResponseFromJSONTyped(json, false);
}

export function Oauth2TokenExchange200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oauth2TokenExchange200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'issuedTokenType': json['issued_token_type'] == null ? undefined : json['issued_token_type'],
    };
}

export function Oauth2TokenExchange200ResponseToJSON(json: any): Oauth2TokenExchange200Response {
    return Oauth2TokenExchange200ResponseToJSONTyped(json, false);
}

export function Oauth2TokenExchange200ResponseToJSONTyped(value?: Oauth2TokenExchange200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
        'scope': value['scope'],
        'issued_token_type': value['issuedTokenType'],
    };
}

