/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Oauth2RegisterRequest
 */
export interface Oauth2RegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof Oauth2RegisterRequest
     */
    clientName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Oauth2RegisterRequest
     */
    redirectUris: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Oauth2RegisterRequest
     */
    grantTypes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Oauth2RegisterRequest
     */
    responseTypes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Oauth2RegisterRequest
     */
    scope?: string;
    /**
     * 
     * @type {Oauth2RegisterRequestTokenEndpointAuthMethodEnum}
     * @memberof Oauth2RegisterRequest
     */
    tokenEndpointAuthMethod?: Oauth2RegisterRequestTokenEndpointAuthMethodEnum;
}


/**
 * @export
 */
export const Oauth2RegisterRequestTokenEndpointAuthMethodEnum = {
    None: 'none',
    ClientSecretPost: 'client_secret_post',
    ClientSecretBasic: 'client_secret_basic'
} as const;
export type Oauth2RegisterRequestTokenEndpointAuthMethodEnum = typeof Oauth2RegisterRequestTokenEndpointAuthMethodEnum[keyof typeof Oauth2RegisterRequestTokenEndpointAuthMethodEnum];


/**
 * Check if a given object implements the Oauth2RegisterRequest interface.
 */
export function instanceOfOauth2RegisterRequest(value: object): value is Oauth2RegisterRequest {
    if (!('redirectUris' in value) || value['redirectUris'] === undefined) return false;
    return true;
}

export function Oauth2RegisterRequestFromJSON(json: any): Oauth2RegisterRequest {
    return Oauth2RegisterRequestFromJSONTyped(json, false);
}

export function Oauth2RegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oauth2RegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientName': json['client_name'] == null ? undefined : json['client_name'],
        'redirectUris': json['redirect_uris'],
        'grantTypes': json['grant_types'] == null ? undefined : json['grant_types'],
        'responseTypes': json['response_types'] == null ? undefined : json['response_types'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'tokenEndpointAuthMethod': json['token_endpoint_auth_method'] == null ? undefined : json['token_endpoint_auth_method'],
    };
}

export function Oauth2RegisterRequestToJSON(json: any): Oauth2RegisterRequest {
    return Oauth2RegisterRequestToJSONTyped(json, false);
}

export function Oauth2RegisterRequestToJSONTyped(value?: Oauth2RegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_name': value['clientName'],
        'redirect_uris': value['redirectUris'],
        'grant_types': value['grantTypes'],
        'response_types': value['responseTypes'],
        'scope': value['scope'],
        'token_endpoint_auth_method': value['tokenEndpointAuthMethod'],
    };
}

