/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Oauth2Oauth2Write
 */
export interface Oauth2Oauth2Write {
    /**
     * 
     * @type {string}
     * @memberof Oauth2Oauth2Write
     */
    grantType?: Oauth2Oauth2WriteGrantTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Oauth2Oauth2Write
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2Oauth2Write
     */
    clientSecret?: string;
}


/**
 * @export
 */
export const Oauth2Oauth2WriteGrantTypeEnum = {
    ClientCredentials: 'client_credentials'
} as const;
export type Oauth2Oauth2WriteGrantTypeEnum = typeof Oauth2Oauth2WriteGrantTypeEnum[keyof typeof Oauth2Oauth2WriteGrantTypeEnum];


/**
 * Check if a given object implements the Oauth2Oauth2Write interface.
 */
export function instanceOfOauth2Oauth2Write(value: object): value is Oauth2Oauth2Write {
    return true;
}

export function Oauth2Oauth2WriteFromJSON(json: any): Oauth2Oauth2Write {
    return Oauth2Oauth2WriteFromJSONTyped(json, false);
}

export function Oauth2Oauth2WriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oauth2Oauth2Write {
    if (json == null) {
        return json;
    }
    return {
        
        'grantType': json['grantType'] == null ? undefined : json['grantType'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'clientSecret': json['clientSecret'] == null ? undefined : json['clientSecret'],
    };
}

export function Oauth2Oauth2WriteToJSON(json: any): Oauth2Oauth2Write {
    return Oauth2Oauth2WriteToJSONTyped(json, false);
}

export function Oauth2Oauth2WriteToJSONTyped(value?: Oauth2Oauth2Write | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grantType': value['grantType'],
        'clientId': value['clientId'],
        'clientSecret': value['clientSecret'],
    };
}

