/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HalCollectionBaseSchemaNoPaginationLinks } from './HalCollectionBaseSchemaNoPaginationLinks';
import {
    HalCollectionBaseSchemaNoPaginationLinksFromJSON,
    HalCollectionBaseSchemaNoPaginationLinksFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationLinksToJSON,
    HalCollectionBaseSchemaNoPaginationLinksToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationLinks';

/**
 * 
 * @export
 * @interface PersonalAccessTokenJsonhalPersonalAccessTokenRead
 */
export interface PersonalAccessTokenJsonhalPersonalAccessTokenRead {
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenRead
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenRead
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenRead
     */
    tokenPreview?: string;
    /**
     * 
     * @type {Date}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenRead
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationLinks}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenRead
     */
    links?: HalCollectionBaseSchemaNoPaginationLinks;
}

/**
 * Check if a given object implements the PersonalAccessTokenJsonhalPersonalAccessTokenRead interface.
 */
export function instanceOfPersonalAccessTokenJsonhalPersonalAccessTokenRead(value: object): value is PersonalAccessTokenJsonhalPersonalAccessTokenRead {
    return true;
}

export function PersonalAccessTokenJsonhalPersonalAccessTokenReadFromJSON(json: any): PersonalAccessTokenJsonhalPersonalAccessTokenRead {
    return PersonalAccessTokenJsonhalPersonalAccessTokenReadFromJSONTyped(json, false);
}

export function PersonalAccessTokenJsonhalPersonalAccessTokenReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalAccessTokenJsonhalPersonalAccessTokenRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tokenPreview': json['tokenPreview'] == null ? undefined : json['tokenPreview'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'links': json['_links'] == null ? undefined : HalCollectionBaseSchemaNoPaginationLinksFromJSON(json['_links']),
    };
}

export function PersonalAccessTokenJsonhalPersonalAccessTokenReadToJSON(json: any): PersonalAccessTokenJsonhalPersonalAccessTokenRead {
    return PersonalAccessTokenJsonhalPersonalAccessTokenReadToJSONTyped(json, false);
}

export function PersonalAccessTokenJsonhalPersonalAccessTokenReadToJSONTyped(value?: PersonalAccessTokenJsonhalPersonalAccessTokenRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'tokenPreview': value['tokenPreview'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        '_links': HalCollectionBaseSchemaNoPaginationLinksToJSON(value['links']),
    };
}

