/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead
 */
export interface PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead {
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead
     */
    tokenPreview: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead
     */
    token: string;
    /**
     * 
     * @type {Date}
     * @memberof PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead interface.
 */
export function instanceOfPersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead(value: object): value is PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tokenPreview' in value) || value['tokenPreview'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateReadFromJSON(json: any): PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead {
    return PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateReadFromJSONTyped(json, false);
}

export function PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tokenPreview': json['tokenPreview'],
        'token': json['token'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateReadToJSON(json: any): PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead {
    return PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateReadToJSONTyped(json, false);
}

export function PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateReadToJSONTyped(value?: PersonalAccessTokenPersonalAccessTokenReadPersonalAccessTokenCreateRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'tokenPreview': value['tokenPreview'],
        'token': value['token'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
    };
}

