/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HalCollectionBaseSchemaNoPaginationLinks } from './HalCollectionBaseSchemaNoPaginationLinks';
import {
    HalCollectionBaseSchemaNoPaginationLinksFromJSON,
    HalCollectionBaseSchemaNoPaginationLinksFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationLinksToJSON,
    HalCollectionBaseSchemaNoPaginationLinksToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationLinks';

/**
 * 
 * @export
 * @interface PersonalAccessTokenJsonhalPersonalAccessTokenWrite
 */
export interface PersonalAccessTokenJsonhalPersonalAccessTokenWrite {
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenWrite
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenWrite
     */
    expiresAt?: Date;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationLinks}
     * @memberof PersonalAccessTokenJsonhalPersonalAccessTokenWrite
     */
    links?: HalCollectionBaseSchemaNoPaginationLinks;
}

/**
 * Check if a given object implements the PersonalAccessTokenJsonhalPersonalAccessTokenWrite interface.
 */
export function instanceOfPersonalAccessTokenJsonhalPersonalAccessTokenWrite(value: object): value is PersonalAccessTokenJsonhalPersonalAccessTokenWrite {
    return true;
}

export function PersonalAccessTokenJsonhalPersonalAccessTokenWriteFromJSON(json: any): PersonalAccessTokenJsonhalPersonalAccessTokenWrite {
    return PersonalAccessTokenJsonhalPersonalAccessTokenWriteFromJSONTyped(json, false);
}

export function PersonalAccessTokenJsonhalPersonalAccessTokenWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalAccessTokenJsonhalPersonalAccessTokenWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'links': json['_links'] == null ? undefined : HalCollectionBaseSchemaNoPaginationLinksFromJSON(json['_links']),
    };
}

export function PersonalAccessTokenJsonhalPersonalAccessTokenWriteToJSON(json: any): PersonalAccessTokenJsonhalPersonalAccessTokenWrite {
    return PersonalAccessTokenJsonhalPersonalAccessTokenWriteToJSONTyped(json, false);
}

export function PersonalAccessTokenJsonhalPersonalAccessTokenWriteToJSONTyped(value?: PersonalAccessTokenJsonhalPersonalAccessTokenWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        '_links': HalCollectionBaseSchemaNoPaginationLinksToJSON(value['links']),
    };
}

