/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Change user password
 * @export
 * @interface UserUserUpdate
 */
export interface UserUserUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserUserUpdate
     */
    password: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserUpdate
     */
    oldPassword?: string | null;
}

/**
 * Check if a given object implements the UserUserUpdate interface.
 */
export function instanceOfUserUserUpdate(value: object): value is UserUserUpdate {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserUserUpdateFromJSON(json: any): UserUserUpdate {
    return UserUserUpdateFromJSONTyped(json, false);
}

export function UserUserUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUserUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
    };
}

export function UserUserUpdateToJSON(json: any): UserUserUpdate {
    return UserUserUpdateToJSONTyped(json, false);
}

export function UserUserUpdateToJSONTyped(value?: UserUserUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'oldPassword': value['oldPassword'],
    };
}

