/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create user
 * @export
 * @interface UserJsonldUserCreate
 */
export interface UserJsonldUserCreate {
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserCreate
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserCreate
     */
    password: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserCreate
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the UserJsonldUserCreate interface.
 */
export function instanceOfUserJsonldUserCreate(value: object): value is UserJsonldUserCreate {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserJsonldUserCreateFromJSON(json: any): UserJsonldUserCreate {
    return UserJsonldUserCreateFromJSONTyped(json, false);
}

export function UserJsonldUserCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonldUserCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserJsonldUserCreateToJSON(json: any): UserJsonldUserCreate {
    return UserJsonldUserCreateToJSONTyped(json, false);
}

export function UserJsonldUserCreateToJSONTyped(value?: UserJsonldUserCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'activationUrl': value['activationUrl'],
    };
}

