/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserJsonapiDataAttributes
 */
export interface UserJsonapiDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiDataAttributes
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiDataAttributes
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiDataAttributes
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiDataAttributes
     */
    oldPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiDataAttributes
     */
    token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiDataAttributes
     */
    resetPasswordLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiDataAttributes
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the UserJsonapiDataAttributes interface.
 */
export function instanceOfUserJsonapiDataAttributes(value: object): value is UserJsonapiDataAttributes {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserJsonapiDataAttributesFromJSON(json: any): UserJsonapiDataAttributes {
    return UserJsonapiDataAttributesFromJSONTyped(json, false);
}

export function UserJsonapiDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonapiDataAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'] == null ? undefined : json['_id'],
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
        'token': json['token'] == null ? undefined : json['token'],
        'resetPasswordLink': json['resetPasswordLink'] == null ? undefined : json['resetPasswordLink'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserJsonapiDataAttributesToJSON(json: any): UserJsonapiDataAttributes {
    return UserJsonapiDataAttributesToJSONTyped(json, false);
}

export function UserJsonapiDataAttributesToJSONTyped(value?: UserJsonapiDataAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'email': value['email'],
        'password': value['password'],
        'oldPassword': value['oldPassword'],
        'token': value['token'],
        'resetPasswordLink': value['resetPasswordLink'],
        'activationUrl': value['activationUrl'],
    };
}

