/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionReadLinks } from './DefinitionJsonhalDefinitionReadLinks';
import {
    DefinitionJsonhalDefinitionReadLinksFromJSON,
    DefinitionJsonhalDefinitionReadLinksFromJSONTyped,
    DefinitionJsonhalDefinitionReadLinksToJSON,
    DefinitionJsonhalDefinitionReadLinksToJSONTyped,
} from './DefinitionJsonhalDefinitionReadLinks';

/**
 * Create user
 * @export
 * @interface UserJsonhalUserCreate
 */
export interface UserJsonhalUserCreate {
    /**
     * 
     * @type {DefinitionJsonhalDefinitionReadLinks}
     * @memberof UserJsonhalUserCreate
     */
    links?: DefinitionJsonhalDefinitionReadLinks;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserCreate
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserCreate
     */
    password: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserCreate
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the UserJsonhalUserCreate interface.
 */
export function instanceOfUserJsonhalUserCreate(value: object): value is UserJsonhalUserCreate {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserJsonhalUserCreateFromJSON(json: any): UserJsonhalUserCreate {
    return UserJsonhalUserCreateFromJSONTyped(json, false);
}

export function UserJsonhalUserCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonhalUserCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : DefinitionJsonhalDefinitionReadLinksFromJSON(json['_links']),
        'email': json['email'],
        'password': json['password'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserJsonhalUserCreateToJSON(json: any): UserJsonhalUserCreate {
    return UserJsonhalUserCreateToJSONTyped(json, false);
}

export function UserJsonhalUserCreateToJSONTyped(value?: UserJsonhalUserCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': DefinitionJsonhalDefinitionReadLinksToJSON(value['links']),
        'email': value['email'],
        'password': value['password'],
        'activationUrl': value['activationUrl'],
    };
}

