/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentUserLimits } from './CurrentUserLimits';
import {
    CurrentUserLimitsFromJSON,
    CurrentUserLimitsFromJSONTyped,
    CurrentUserLimitsToJSON,
    CurrentUserLimitsToJSONTyped,
} from './CurrentUserLimits';
import type { HalCollectionBaseSchemaNoPaginationLinks } from './HalCollectionBaseSchemaNoPaginationLinks';
import {
    HalCollectionBaseSchemaNoPaginationLinksFromJSON,
    HalCollectionBaseSchemaNoPaginationLinksFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationLinksToJSON,
    HalCollectionBaseSchemaNoPaginationLinksToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationLinks';

/**
 * 
 * @export
 * @interface UserJsonhal
 */
export interface UserJsonhal {
    /**
     * 
     * @type {CurrentUserLimits}
     * @memberof UserJsonhal
     */
    limits?: CurrentUserLimits;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationLinks}
     * @memberof UserJsonhal
     */
    links?: HalCollectionBaseSchemaNoPaginationLinks;
}

/**
 * Check if a given object implements the UserJsonhal interface.
 */
export function instanceOfUserJsonhal(value: object): value is UserJsonhal {
    return true;
}

export function UserJsonhalFromJSON(json: any): UserJsonhal {
    return UserJsonhalFromJSONTyped(json, false);
}

export function UserJsonhalFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonhal {
    if (json == null) {
        return json;
    }
    return {
        
        'limits': json['limits'] == null ? undefined : CurrentUserLimitsFromJSON(json['limits']),
        'links': json['_links'] == null ? undefined : HalCollectionBaseSchemaNoPaginationLinksFromJSON(json['_links']),
    };
}

export function UserJsonhalToJSON(json: any): UserJsonhal {
    return UserJsonhalToJSONTyped(json, false);
}

export function UserJsonhalToJSONTyped(value?: UserJsonhal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limits': CurrentUserLimitsToJSON(value['limits']),
        '_links': HalCollectionBaseSchemaNoPaginationLinksToJSON(value['links']),
    };
}

