/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create user
 * @export
 * @interface UserUserCreate
 */
export interface UserUserCreate {
    /**
     * 
     * @type {string}
     * @memberof UserUserCreate
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserCreate
     */
    password: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserCreate
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the UserUserCreate interface.
 */
export function instanceOfUserUserCreate(value: object): value is UserUserCreate {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserUserCreateFromJSON(json: any): UserUserCreate {
    return UserUserCreateFromJSONTyped(json, false);
}

export function UserUserCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUserCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserUserCreateToJSON(json: any): UserUserCreate {
    return UserUserCreateToJSONTyped(json, false);
}

export function UserUserCreateToJSONTyped(value?: UserUserCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'activationUrl': value['activationUrl'],
    };
}

