/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserJsonldUserSendResetPassword
 */
export interface UserJsonldUserSendResetPassword {
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserSendResetPassword
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserSendResetPassword
     */
    resetPasswordLink: string | null;
}

/**
 * Check if a given object implements the UserJsonldUserSendResetPassword interface.
 */
export function instanceOfUserJsonldUserSendResetPassword(value: object): value is UserJsonldUserSendResetPassword {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('resetPasswordLink' in value) || value['resetPasswordLink'] === undefined) return false;
    return true;
}

export function UserJsonldUserSendResetPasswordFromJSON(json: any): UserJsonldUserSendResetPassword {
    return UserJsonldUserSendResetPasswordFromJSONTyped(json, false);
}

export function UserJsonldUserSendResetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonldUserSendResetPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'resetPasswordLink': json['resetPasswordLink'],
    };
}

export function UserJsonldUserSendResetPasswordToJSON(json: any): UserJsonldUserSendResetPassword {
    return UserJsonldUserSendResetPasswordToJSONTyped(json, false);
}

export function UserJsonldUserSendResetPasswordToJSONTyped(value?: UserJsonldUserSendResetPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'resetPasswordLink': value['resetPasswordLink'],
    };
}

