/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    oldPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    resetPasswordLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
        'token': json['token'] == null ? undefined : json['token'],
        'resetPasswordLink': json['resetPasswordLink'] == null ? undefined : json['resetPasswordLink'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'password': value['password'],
        'oldPassword': value['oldPassword'],
        'token': value['token'],
        'resetPasswordLink': value['resetPasswordLink'],
        'activationUrl': value['activationUrl'],
    };
}

