/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserJsonapiDataAttributes } from './UserJsonapiDataAttributes';
import {
    UserJsonapiDataAttributesFromJSON,
    UserJsonapiDataAttributesFromJSONTyped,
    UserJsonapiDataAttributesToJSON,
    UserJsonapiDataAttributesToJSONTyped,
} from './UserJsonapiDataAttributes';

/**
 * 
 * @export
 * @interface UserJsonapiData
 */
export interface UserJsonapiData {
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonapiData
     */
    type: string;
    /**
     * 
     * @type {UserJsonapiDataAttributes}
     * @memberof UserJsonapiData
     */
    attributes?: UserJsonapiDataAttributes;
}

/**
 * Check if a given object implements the UserJsonapiData interface.
 */
export function instanceOfUserJsonapiData(value: object): value is UserJsonapiData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function UserJsonapiDataFromJSON(json: any): UserJsonapiData {
    return UserJsonapiDataFromJSONTyped(json, false);
}

export function UserJsonapiDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonapiData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'attributes': json['attributes'] == null ? undefined : UserJsonapiDataAttributesFromJSON(json['attributes']),
    };
}

export function UserJsonapiDataToJSON(json: any): UserJsonapiData {
    return UserJsonapiDataToJSONTyped(json, false);
}

export function UserJsonapiDataToJSONTyped(value?: UserJsonapiData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': UserJsonapiDataAttributesToJSON(value['attributes']),
    };
}

