/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HalCollectionBaseSchemaNoPaginationLinks } from './HalCollectionBaseSchemaNoPaginationLinks';
import {
    HalCollectionBaseSchemaNoPaginationLinksFromJSON,
    HalCollectionBaseSchemaNoPaginationLinksFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationLinksToJSON,
    HalCollectionBaseSchemaNoPaginationLinksToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationLinks';

/**
 * 
 * @export
 * @interface UserJsonhalUserSendResetPassword
 */
export interface UserJsonhalUserSendResetPassword {
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserSendResetPassword
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserSendResetPassword
     */
    resetPasswordLink: string;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationLinks}
     * @memberof UserJsonhalUserSendResetPassword
     */
    links?: HalCollectionBaseSchemaNoPaginationLinks;
}

/**
 * Check if a given object implements the UserJsonhalUserSendResetPassword interface.
 */
export function instanceOfUserJsonhalUserSendResetPassword(value: object): value is UserJsonhalUserSendResetPassword {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('resetPasswordLink' in value) || value['resetPasswordLink'] === undefined) return false;
    return true;
}

export function UserJsonhalUserSendResetPasswordFromJSON(json: any): UserJsonhalUserSendResetPassword {
    return UserJsonhalUserSendResetPasswordFromJSONTyped(json, false);
}

export function UserJsonhalUserSendResetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonhalUserSendResetPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'resetPasswordLink': json['resetPasswordLink'],
        'links': json['_links'] == null ? undefined : HalCollectionBaseSchemaNoPaginationLinksFromJSON(json['_links']),
    };
}

export function UserJsonhalUserSendResetPasswordToJSON(json: any): UserJsonhalUserSendResetPassword {
    return UserJsonhalUserSendResetPasswordToJSONTyped(json, false);
}

export function UserJsonhalUserSendResetPasswordToJSONTyped(value?: UserJsonhalUserSendResetPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'resetPasswordLink': value['resetPasswordLink'],
        '_links': HalCollectionBaseSchemaNoPaginationLinksToJSON(value['links']),
    };
}

