/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HalCollectionBaseSchemaNoPaginationLinks } from './HalCollectionBaseSchemaNoPaginationLinks';
import {
    HalCollectionBaseSchemaNoPaginationLinksFromJSON,
    HalCollectionBaseSchemaNoPaginationLinksFromJSONTyped,
    HalCollectionBaseSchemaNoPaginationLinksToJSON,
    HalCollectionBaseSchemaNoPaginationLinksToJSONTyped,
} from './HalCollectionBaseSchemaNoPaginationLinks';

/**
 * 
 * @export
 * @interface UserJsonhal
 */
export interface UserJsonhal {
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    oldPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    resetPasswordLink?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    activationUrl?: string;
    /**
     * 
     * @type {HalCollectionBaseSchemaNoPaginationLinks}
     * @memberof UserJsonhal
     */
    links?: HalCollectionBaseSchemaNoPaginationLinks;
}

/**
 * Check if a given object implements the UserJsonhal interface.
 */
export function instanceOfUserJsonhal(value: object): value is UserJsonhal {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserJsonhalFromJSON(json: any): UserJsonhal {
    return UserJsonhalFromJSONTyped(json, false);
}

export function UserJsonhalFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonhal {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
        'token': json['token'] == null ? undefined : json['token'],
        'resetPasswordLink': json['resetPasswordLink'] == null ? undefined : json['resetPasswordLink'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
        'links': json['_links'] == null ? undefined : HalCollectionBaseSchemaNoPaginationLinksFromJSON(json['_links']),
    };
}

export function UserJsonhalToJSON(json: any): UserJsonhal {
    return UserJsonhalToJSONTyped(json, false);
}

export function UserJsonhalToJSONTyped(value?: UserJsonhal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'password': value['password'],
        'oldPassword': value['oldPassword'],
        'token': value['token'],
        'resetPasswordLink': value['resetPasswordLink'],
        'activationUrl': value['activationUrl'],
        '_links': HalCollectionBaseSchemaNoPaginationLinksToJSON(value['links']),
    };
}

