/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create user
 * @export
 * @interface UserUserRead
 */
export interface UserUserRead {
    /**
     * 
     * @type {string}
     * @memberof UserUserRead
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserRead
     */
    email: string | null;
}

/**
 * Check if a given object implements the UserUserRead interface.
 */
export function instanceOfUserUserRead(value: object): value is UserUserRead {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserUserReadFromJSON(json: any): UserUserRead {
    return UserUserReadFromJSONTyped(json, false);
}

export function UserUserReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUserRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'],
    };
}

export function UserUserReadToJSON(json: any): UserUserRead {
    return UserUserReadToJSONTyped(json, false);
}

export function UserUserReadToJSONTyped(value?: UserUserRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
    };
}

