/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Change user password
 * @export
 * @interface UserUserUpdateJsonMergePatch
 */
export interface UserUserUpdateJsonMergePatch {
    /**
     * 
     * @type {string}
     * @memberof UserUserUpdateJsonMergePatch
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserUpdateJsonMergePatch
     */
    oldPassword?: string | null;
}

/**
 * Check if a given object implements the UserUserUpdateJsonMergePatch interface.
 */
export function instanceOfUserUserUpdateJsonMergePatch(value: object): value is UserUserUpdateJsonMergePatch {
    return true;
}

export function UserUserUpdateJsonMergePatchFromJSON(json: any): UserUserUpdateJsonMergePatch {
    return UserUserUpdateJsonMergePatchFromJSONTyped(json, false);
}

export function UserUserUpdateJsonMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUserUpdateJsonMergePatch {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
    };
}

export function UserUserUpdateJsonMergePatchToJSON(json: any): UserUserUpdateJsonMergePatch {
    return UserUserUpdateJsonMergePatchToJSONTyped(json, false);
}

export function UserUserUpdateJsonMergePatchToJSONTyped(value?: UserUserUpdateJsonMergePatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'oldPassword': value['oldPassword'],
    };
}

