/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionReadLinks } from './DefinitionJsonhalDefinitionReadLinks';
import {
    DefinitionJsonhalDefinitionReadLinksFromJSON,
    DefinitionJsonhalDefinitionReadLinksFromJSONTyped,
    DefinitionJsonhalDefinitionReadLinksToJSON,
    DefinitionJsonhalDefinitionReadLinksToJSONTyped,
} from './DefinitionJsonhalDefinitionReadLinks';

/**
 * 
 * @export
 * @interface UserJsonhalUserResetPassword
 */
export interface UserJsonhalUserResetPassword {
    /**
     * 
     * @type {DefinitionJsonhalDefinitionReadLinks}
     * @memberof UserJsonhalUserResetPassword
     */
    links?: DefinitionJsonhalDefinitionReadLinks;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserResetPassword
     */
    password: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserResetPassword
     */
    token: string | null;
}

/**
 * Check if a given object implements the UserJsonhalUserResetPassword interface.
 */
export function instanceOfUserJsonhalUserResetPassword(value: object): value is UserJsonhalUserResetPassword {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function UserJsonhalUserResetPasswordFromJSON(json: any): UserJsonhalUserResetPassword {
    return UserJsonhalUserResetPasswordFromJSONTyped(json, false);
}

export function UserJsonhalUserResetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonhalUserResetPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : DefinitionJsonhalDefinitionReadLinksFromJSON(json['_links']),
        'password': json['password'],
        'token': json['token'],
    };
}

export function UserJsonhalUserResetPasswordToJSON(json: any): UserJsonhalUserResetPassword {
    return UserJsonhalUserResetPasswordToJSONTyped(json, false);
}

export function UserJsonhalUserResetPasswordToJSONTyped(value?: UserJsonhalUserResetPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': DefinitionJsonhalDefinitionReadLinksToJSON(value['links']),
        'password': value['password'],
        'token': value['token'],
    };
}

