/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonldDefinitionReadContext } from './DefinitionJsonldDefinitionReadContext';
import {
    DefinitionJsonldDefinitionReadContextFromJSON,
    DefinitionJsonldDefinitionReadContextFromJSONTyped,
    DefinitionJsonldDefinitionReadContextToJSON,
    DefinitionJsonldDefinitionReadContextToJSONTyped,
} from './DefinitionJsonldDefinitionReadContext';

/**
 * Create user
 * @export
 * @interface UserJsonldUserRead
 */
export interface UserJsonldUserRead {
    /**
     * 
     * @type {DefinitionJsonldDefinitionReadContext}
     * @memberof UserJsonldUserRead
     */
    context?: DefinitionJsonldDefinitionReadContext;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserRead
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserRead
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserRead
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserRead
     */
    email: string | null;
}

/**
 * Check if a given object implements the UserJsonldUserRead interface.
 */
export function instanceOfUserJsonldUserRead(value: object): value is UserJsonldUserRead {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserJsonldUserReadFromJSON(json: any): UserJsonldUserRead {
    return UserJsonldUserReadFromJSONTyped(json, false);
}

export function UserJsonldUserReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonldUserRead {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : DefinitionJsonldDefinitionReadContextFromJSON(json['@context']),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'],
    };
}

export function UserJsonldUserReadToJSON(json: any): UserJsonldUserRead {
    return UserJsonldUserReadToJSONTyped(json, false);
}

export function UserJsonldUserReadToJSONTyped(value?: Omit<UserJsonldUserRead, '@id'|'@type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': DefinitionJsonldDefinitionReadContextToJSON(value['context']),
        'id': value['id'],
        'email': value['email'],
    };
}

