/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JsonHubApi);
  }
}(this, function(expect, JsonHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JsonHubApi.EntityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EntityApi', function() {
    describe('apiEntitiesGetCollection', function() {
      it('should call apiEntitiesGetCollection successfully', function(done) {
        //uncomment below and update the code to test apiEntitiesGetCollection
        //instance.apiEntitiesGetCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiEntitiesIdDelete', function() {
      it('should call apiEntitiesIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiEntitiesIdDelete
        //instance.apiEntitiesIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiEntitiesIdGet', function() {
      it('should call apiEntitiesIdGet successfully', function(done) {
        //uncomment below and update the code to test apiEntitiesIdGet
        //instance.apiEntitiesIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiEntitiesIdPatch', function() {
      it('should call apiEntitiesIdPatch successfully', function(done) {
        //uncomment below and update the code to test apiEntitiesIdPatch
        //instance.apiEntitiesIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiEntitiesPost', function() {
      it('should call apiEntitiesPost successfully', function(done) {
        //uncomment below and update the code to test apiEntitiesPost
        //instance.apiEntitiesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
