/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonldDefinitionRead } from './DefinitionJsonldDefinitionRead';
import {
    DefinitionJsonldDefinitionReadFromJSON,
    DefinitionJsonldDefinitionReadFromJSONTyped,
    DefinitionJsonldDefinitionReadToJSON,
    DefinitionJsonldDefinitionReadToJSONTyped,
} from './DefinitionJsonldDefinitionRead';
import type { ApiDefinitionsGetCollection200ResponseHydraSearch } from './ApiDefinitionsGetCollection200ResponseHydraSearch';
import {
    ApiDefinitionsGetCollection200ResponseHydraSearchFromJSON,
    ApiDefinitionsGetCollection200ResponseHydraSearchFromJSONTyped,
    ApiDefinitionsGetCollection200ResponseHydraSearchToJSON,
    ApiDefinitionsGetCollection200ResponseHydraSearchToJSONTyped,
} from './ApiDefinitionsGetCollection200ResponseHydraSearch';
import type { ApiDefinitionsGetCollection200ResponseHydraView } from './ApiDefinitionsGetCollection200ResponseHydraView';
import {
    ApiDefinitionsGetCollection200ResponseHydraViewFromJSON,
    ApiDefinitionsGetCollection200ResponseHydraViewFromJSONTyped,
    ApiDefinitionsGetCollection200ResponseHydraViewToJSON,
    ApiDefinitionsGetCollection200ResponseHydraViewToJSONTyped,
} from './ApiDefinitionsGetCollection200ResponseHydraView';

/**
 * 
 * @export
 * @interface ApiDefinitionsGetCollection200Response
 */
export interface ApiDefinitionsGetCollection200Response {
    /**
     * 
     * @type {Array<DefinitionJsonldDefinitionRead>}
     * @memberof ApiDefinitionsGetCollection200Response
     */
    hydraMember: Array<DefinitionJsonldDefinitionRead>;
    /**
     * 
     * @type {number}
     * @memberof ApiDefinitionsGetCollection200Response
     */
    hydraTotalItems?: number;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseHydraView}
     * @memberof ApiDefinitionsGetCollection200Response
     */
    hydraView?: ApiDefinitionsGetCollection200ResponseHydraView;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200ResponseHydraSearch}
     * @memberof ApiDefinitionsGetCollection200Response
     */
    hydraSearch?: ApiDefinitionsGetCollection200ResponseHydraSearch;
}

/**
 * Check if a given object implements the ApiDefinitionsGetCollection200Response interface.
 */
export function instanceOfApiDefinitionsGetCollection200Response(value: object): value is ApiDefinitionsGetCollection200Response {
    if (!('hydraMember' in value) || value['hydraMember'] === undefined) return false;
    return true;
}

export function ApiDefinitionsGetCollection200ResponseFromJSON(json: any): ApiDefinitionsGetCollection200Response {
    return ApiDefinitionsGetCollection200ResponseFromJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDefinitionsGetCollection200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'hydraMember': ((json['hydra:member'] as Array<any>).map(DefinitionJsonldDefinitionReadFromJSON)),
        'hydraTotalItems': json['hydra:totalItems'] == null ? undefined : json['hydra:totalItems'],
        'hydraView': json['hydra:view'] == null ? undefined : ApiDefinitionsGetCollection200ResponseHydraViewFromJSON(json['hydra:view']),
        'hydraSearch': json['hydra:search'] == null ? undefined : ApiDefinitionsGetCollection200ResponseHydraSearchFromJSON(json['hydra:search']),
    };
}

export function ApiDefinitionsGetCollection200ResponseToJSON(json: any): ApiDefinitionsGetCollection200Response {
    return ApiDefinitionsGetCollection200ResponseToJSONTyped(json, false);
}

export function ApiDefinitionsGetCollection200ResponseToJSONTyped(value?: ApiDefinitionsGetCollection200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hydra:member': ((value['hydraMember'] as Array<any>).map(DefinitionJsonldDefinitionReadToJSON)),
        'hydra:totalItems': value['hydraTotalItems'],
        'hydra:view': ApiDefinitionsGetCollection200ResponseHydraViewToJSON(value['hydraView']),
        'hydra:search': ApiDefinitionsGetCollection200ResponseHydraSearchToJSON(value['hydraSearch']),
    };
}

