/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiEntitiesGetCollection200Response1Embedded } from './ApiEntitiesGetCollection200Response1Embedded';
import {
    ApiEntitiesGetCollection200Response1EmbeddedFromJSON,
    ApiEntitiesGetCollection200Response1EmbeddedFromJSONTyped,
    ApiEntitiesGetCollection200Response1EmbeddedToJSON,
    ApiEntitiesGetCollection200Response1EmbeddedToJSONTyped,
} from './ApiEntitiesGetCollection200Response1Embedded';
import type { ApiDefinitionsGetCollection200Response1Links } from './ApiDefinitionsGetCollection200Response1Links';
import {
    ApiDefinitionsGetCollection200Response1LinksFromJSON,
    ApiDefinitionsGetCollection200Response1LinksFromJSONTyped,
    ApiDefinitionsGetCollection200Response1LinksToJSON,
    ApiDefinitionsGetCollection200Response1LinksToJSONTyped,
} from './ApiDefinitionsGetCollection200Response1Links';

/**
 * 
 * @export
 * @interface ApiEntitiesGetCollection200Response1
 */
export interface ApiEntitiesGetCollection200Response1 {
    /**
     * 
     * @type {ApiEntitiesGetCollection200Response1Embedded}
     * @memberof ApiEntitiesGetCollection200Response1
     */
    embedded: ApiEntitiesGetCollection200Response1Embedded;
    /**
     * 
     * @type {number}
     * @memberof ApiEntitiesGetCollection200Response1
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiEntitiesGetCollection200Response1
     */
    itemsPerPage?: number;
    /**
     * 
     * @type {ApiDefinitionsGetCollection200Response1Links}
     * @memberof ApiEntitiesGetCollection200Response1
     */
    links: ApiDefinitionsGetCollection200Response1Links;
}

/**
 * Check if a given object implements the ApiEntitiesGetCollection200Response1 interface.
 */
export function instanceOfApiEntitiesGetCollection200Response1(value: object): value is ApiEntitiesGetCollection200Response1 {
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function ApiEntitiesGetCollection200Response1FromJSON(json: any): ApiEntitiesGetCollection200Response1 {
    return ApiEntitiesGetCollection200Response1FromJSONTyped(json, false);
}

export function ApiEntitiesGetCollection200Response1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEntitiesGetCollection200Response1 {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': ApiEntitiesGetCollection200Response1EmbeddedFromJSON(json['_embedded']),
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'itemsPerPage': json['itemsPerPage'] == null ? undefined : json['itemsPerPage'],
        'links': ApiDefinitionsGetCollection200Response1LinksFromJSON(json['_links']),
    };
}

export function ApiEntitiesGetCollection200Response1ToJSON(json: any): ApiEntitiesGetCollection200Response1 {
    return ApiEntitiesGetCollection200Response1ToJSONTyped(json, false);
}

export function ApiEntitiesGetCollection200Response1ToJSONTyped(value?: ApiEntitiesGetCollection200Response1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': ApiEntitiesGetCollection200Response1EmbeddedToJSON(value['embedded']),
        'totalItems': value['totalItems'],
        'itemsPerPage': value['itemsPerPage'],
        '_links': ApiDefinitionsGetCollection200Response1LinksToJSON(value['links']),
    };
}

