/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityDefinitionRead } from './EntityDefinitionRead';
import {
    EntityDefinitionReadFromJSON,
    EntityDefinitionReadFromJSONTyped,
    EntityDefinitionReadToJSON,
    EntityDefinitionReadToJSONTyped,
} from './EntityDefinitionRead';

/**
 * 
 * @export
 * @interface DefinitionDefinitionRead
 */
export interface DefinitionDefinitionRead {
    /**
     * 
     * @type {string}
     * @memberof DefinitionDefinitionRead
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinitionDefinitionRead
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof DefinitionDefinitionRead
     */
    jsonSchema: object;
    /**
     * 
     * @type {EntityDefinitionRead}
     * @memberof DefinitionDefinitionRead
     */
    parentEntity?: EntityDefinitionRead | null;
    /**
     * 
     * @type {boolean}
     * @memberof DefinitionDefinitionRead
     */
    isOwnedByCurrentUser?: boolean;
}

/**
 * Check if a given object implements the DefinitionDefinitionRead interface.
 */
export function instanceOfDefinitionDefinitionRead(value: object): value is DefinitionDefinitionRead {
    if (!('jsonSchema' in value) || value['jsonSchema'] === undefined) return false;
    return true;
}

export function DefinitionDefinitionReadFromJSON(json: any): DefinitionDefinitionRead {
    return DefinitionDefinitionReadFromJSONTyped(json, false);
}

export function DefinitionDefinitionReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionDefinitionRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'jsonSchema': json['jsonSchema'],
        'parentEntity': json['parentEntity'] == null ? undefined : EntityDefinitionReadFromJSON(json['parentEntity']),
        'isOwnedByCurrentUser': json['isOwnedByCurrentUser'] == null ? undefined : json['isOwnedByCurrentUser'],
    };
}

export function DefinitionDefinitionReadToJSON(json: any): DefinitionDefinitionRead {
    return DefinitionDefinitionReadToJSONTyped(json, false);
}

export function DefinitionDefinitionReadToJSONTyped(value?: DefinitionDefinitionRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'jsonSchema': value['jsonSchema'],
        'parentEntity': EntityDefinitionReadToJSON(value['parentEntity']),
        'isOwnedByCurrentUser': value['isOwnedByCurrentUser'],
    };
}

