/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityJsonldDefinitionRead } from './EntityJsonldDefinitionRead';
import {
    EntityJsonldDefinitionReadFromJSON,
    EntityJsonldDefinitionReadFromJSONTyped,
    EntityJsonldDefinitionReadToJSON,
    EntityJsonldDefinitionReadToJSONTyped,
} from './EntityJsonldDefinitionRead';
import type { DefinitionJsonldDefinitionReadContext } from './DefinitionJsonldDefinitionReadContext';
import {
    DefinitionJsonldDefinitionReadContextFromJSON,
    DefinitionJsonldDefinitionReadContextFromJSONTyped,
    DefinitionJsonldDefinitionReadContextToJSON,
    DefinitionJsonldDefinitionReadContextToJSONTyped,
} from './DefinitionJsonldDefinitionReadContext';

/**
 * 
 * @export
 * @interface DefinitionJsonldDefinitionRead
 */
export interface DefinitionJsonldDefinitionRead {
    /**
     * 
     * @type {DefinitionJsonldDefinitionReadContext}
     * @memberof DefinitionJsonldDefinitionRead
     */
    context?: DefinitionJsonldDefinitionReadContext;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonldDefinitionRead
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonldDefinitionRead
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonldDefinitionRead
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonldDefinitionRead
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof DefinitionJsonldDefinitionRead
     */
    jsonSchema: object;
    /**
     * 
     * @type {EntityJsonldDefinitionRead}
     * @memberof DefinitionJsonldDefinitionRead
     */
    parentEntity?: EntityJsonldDefinitionRead | null;
    /**
     * 
     * @type {boolean}
     * @memberof DefinitionJsonldDefinitionRead
     */
    isOwnedByCurrentUser?: boolean;
}

/**
 * Check if a given object implements the DefinitionJsonldDefinitionRead interface.
 */
export function instanceOfDefinitionJsonldDefinitionRead(value: object): value is DefinitionJsonldDefinitionRead {
    if (!('jsonSchema' in value) || value['jsonSchema'] === undefined) return false;
    return true;
}

export function DefinitionJsonldDefinitionReadFromJSON(json: any): DefinitionJsonldDefinitionRead {
    return DefinitionJsonldDefinitionReadFromJSONTyped(json, false);
}

export function DefinitionJsonldDefinitionReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionJsonldDefinitionRead {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : DefinitionJsonldDefinitionReadContextFromJSON(json['@context']),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'jsonSchema': json['jsonSchema'],
        'parentEntity': json['parentEntity'] == null ? undefined : EntityJsonldDefinitionReadFromJSON(json['parentEntity']),
        'isOwnedByCurrentUser': json['isOwnedByCurrentUser'] == null ? undefined : json['isOwnedByCurrentUser'],
    };
}

export function DefinitionJsonldDefinitionReadToJSON(json: any): DefinitionJsonldDefinitionRead {
    return DefinitionJsonldDefinitionReadToJSONTyped(json, false);
}

export function DefinitionJsonldDefinitionReadToJSONTyped(value?: Omit<DefinitionJsonldDefinitionRead, '@id'|'@type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': DefinitionJsonldDefinitionReadContextToJSON(value['context']),
        'id': value['id'],
        'slug': value['slug'],
        'jsonSchema': value['jsonSchema'],
        'parentEntity': EntityJsonldDefinitionReadToJSON(value['parentEntity']),
        'isOwnedByCurrentUser': value['isOwnedByCurrentUser'],
    };
}

