/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonldDefinitionReadContext } from './DefinitionJsonldDefinitionReadContext';
import {
    DefinitionJsonldDefinitionReadContextFromJSON,
    DefinitionJsonldDefinitionReadContextFromJSONTyped,
    DefinitionJsonldDefinitionReadContextToJSON,
    DefinitionJsonldDefinitionReadContextToJSONTyped,
} from './DefinitionJsonldDefinitionReadContext';

/**
 * 
 * @export
 * @interface DefinitionJsonldEntityReadEntityReadParent
 */
export interface DefinitionJsonldEntityReadEntityReadParent {
    /**
     * 
     * @type {DefinitionJsonldDefinitionReadContext}
     * @memberof DefinitionJsonldEntityReadEntityReadParent
     */
    context?: DefinitionJsonldDefinitionReadContext;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonldEntityReadEntityReadParent
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonldEntityReadEntityReadParent
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonldEntityReadEntityReadParent
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinitionJsonldEntityReadEntityReadParent
     */
    slug?: string | null;
}

/**
 * Check if a given object implements the DefinitionJsonldEntityReadEntityReadParent interface.
 */
export function instanceOfDefinitionJsonldEntityReadEntityReadParent(value: object): value is DefinitionJsonldEntityReadEntityReadParent {
    return true;
}

export function DefinitionJsonldEntityReadEntityReadParentFromJSON(json: any): DefinitionJsonldEntityReadEntityReadParent {
    return DefinitionJsonldEntityReadEntityReadParentFromJSONTyped(json, false);
}

export function DefinitionJsonldEntityReadEntityReadParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinitionJsonldEntityReadEntityReadParent {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : DefinitionJsonldDefinitionReadContextFromJSON(json['@context']),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function DefinitionJsonldEntityReadEntityReadParentToJSON(json: any): DefinitionJsonldEntityReadEntityReadParent {
    return DefinitionJsonldEntityReadEntityReadParentToJSONTyped(json, false);
}

export function DefinitionJsonldEntityReadEntityReadParentToJSONTyped(value?: Omit<DefinitionJsonldEntityReadEntityReadParent, '@id'|'@type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': DefinitionJsonldDefinitionReadContextToJSON(value['context']),
        'id': value['id'],
        'slug': value['slug'],
    };
}

