/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionReadLinks } from './DefinitionJsonhalDefinitionReadLinks';
import {
    DefinitionJsonhalDefinitionReadLinksFromJSON,
    DefinitionJsonhalDefinitionReadLinksFromJSONTyped,
    DefinitionJsonhalDefinitionReadLinksToJSON,
    DefinitionJsonhalDefinitionReadLinksToJSONTyped,
} from './DefinitionJsonhalDefinitionReadLinks';

/**
 * 
 * @export
 * @interface EntityJsonhalEntityCreate
 */
export interface EntityJsonhalEntityCreate {
    /**
     * 
     * @type {DefinitionJsonhalDefinitionReadLinks}
     * @memberof EntityJsonhalEntityCreate
     */
    links?: DefinitionJsonhalDefinitionReadLinks;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonhalEntityCreate
     */
    slug?: string | null;
    /**
     * 
     * @type {object}
     * @memberof EntityJsonhalEntityCreate
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof EntityJsonhalEntityCreate
     */
    definition?: string | null;
    /**
     * 
     * @type {EntityJsonhalEntityCreate}
     * @memberof EntityJsonhalEntityCreate
     */
    parent?: EntityJsonhalEntityCreate | null;
    /**
     * 
     * @type {boolean}
     * @memberof EntityJsonhalEntityCreate
     */
    _private?: boolean;
}

/**
 * Check if a given object implements the EntityJsonhalEntityCreate interface.
 */
export function instanceOfEntityJsonhalEntityCreate(value: object): value is EntityJsonhalEntityCreate {
    return true;
}

export function EntityJsonhalEntityCreateFromJSON(json: any): EntityJsonhalEntityCreate {
    return EntityJsonhalEntityCreateFromJSONTyped(json, false);
}

export function EntityJsonhalEntityCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityJsonhalEntityCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : DefinitionJsonhalDefinitionReadLinksFromJSON(json['_links']),
        'slug': json['slug'] == null ? undefined : json['slug'],
        'data': json['data'] == null ? undefined : json['data'],
        'definition': json['definition'] == null ? undefined : json['definition'],
        'parent': json['parent'] == null ? undefined : EntityJsonhalEntityCreateFromJSON(json['parent']),
        '_private': json['private'] == null ? undefined : json['private'],
    };
}

export function EntityJsonhalEntityCreateToJSON(json: any): EntityJsonhalEntityCreate {
    return EntityJsonhalEntityCreateToJSONTyped(json, false);
}

export function EntityJsonhalEntityCreateToJSONTyped(value?: EntityJsonhalEntityCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': DefinitionJsonhalDefinitionReadLinksToJSON(value['links']),
        'slug': value['slug'],
        'data': value['data'],
        'definition': value['definition'],
        'parent': EntityJsonhalEntityCreateToJSON(value['parent']),
        'private': value['_private'],
    };
}

