/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Oauth2JsonapiDataAttributes
 */
export interface Oauth2JsonapiDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof Oauth2JsonapiDataAttributes
     */
    grantType?: Oauth2JsonapiDataAttributesGrantTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Oauth2JsonapiDataAttributes
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2JsonapiDataAttributes
     */
    clientSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2JsonapiDataAttributes
     */
    readonly accessToken?: string | null;
}


/**
 * @export
 */
export const Oauth2JsonapiDataAttributesGrantTypeEnum = {
    ClientCredentials: 'client_credentials'
} as const;
export type Oauth2JsonapiDataAttributesGrantTypeEnum = typeof Oauth2JsonapiDataAttributesGrantTypeEnum[keyof typeof Oauth2JsonapiDataAttributesGrantTypeEnum];


/**
 * Check if a given object implements the Oauth2JsonapiDataAttributes interface.
 */
export function instanceOfOauth2JsonapiDataAttributes(value: object): value is Oauth2JsonapiDataAttributes {
    return true;
}

export function Oauth2JsonapiDataAttributesFromJSON(json: any): Oauth2JsonapiDataAttributes {
    return Oauth2JsonapiDataAttributesFromJSONTyped(json, false);
}

export function Oauth2JsonapiDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oauth2JsonapiDataAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'grantType': json['grantType'] == null ? undefined : json['grantType'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'clientSecret': json['clientSecret'] == null ? undefined : json['clientSecret'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function Oauth2JsonapiDataAttributesToJSON(json: any): Oauth2JsonapiDataAttributes {
    return Oauth2JsonapiDataAttributesToJSONTyped(json, false);
}

export function Oauth2JsonapiDataAttributesToJSONTyped(value?: Omit<Oauth2JsonapiDataAttributes, 'accessToken'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grantType': value['grantType'],
        'clientId': value['clientId'],
        'clientSecret': value['clientSecret'],
    };
}

