/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Oauth2JsonapiData } from './Oauth2JsonapiData';
import {
    Oauth2JsonapiDataFromJSON,
    Oauth2JsonapiDataFromJSONTyped,
    Oauth2JsonapiDataToJSON,
    Oauth2JsonapiDataToJSONTyped,
} from './Oauth2JsonapiData';

/**
 * 
 * @export
 * @interface Oauth2Jsonapi
 */
export interface Oauth2Jsonapi {
    /**
     * 
     * @type {Oauth2JsonapiData}
     * @memberof Oauth2Jsonapi
     */
    data?: Oauth2JsonapiData;
}

/**
 * Check if a given object implements the Oauth2Jsonapi interface.
 */
export function instanceOfOauth2Jsonapi(value: object): value is Oauth2Jsonapi {
    return true;
}

export function Oauth2JsonapiFromJSON(json: any): Oauth2Jsonapi {
    return Oauth2JsonapiFromJSONTyped(json, false);
}

export function Oauth2JsonapiFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oauth2Jsonapi {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : Oauth2JsonapiDataFromJSON(json['data']),
    };
}

export function Oauth2JsonapiToJSON(json: any): Oauth2Jsonapi {
    return Oauth2JsonapiToJSONTyped(json, false);
}

export function Oauth2JsonapiToJSONTyped(value?: Oauth2Jsonapi | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': Oauth2JsonapiDataToJSON(value['data']),
    };
}

