/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Oauth2Oauth2Read
 */
export interface Oauth2Oauth2Read {
    /**
     * 
     * @type {string}
     * @memberof Oauth2Oauth2Read
     */
    accessToken?: string | null;
}

/**
 * Check if a given object implements the Oauth2Oauth2Read interface.
 */
export function instanceOfOauth2Oauth2Read(value: object): value is Oauth2Oauth2Read {
    return true;
}

export function Oauth2Oauth2ReadFromJSON(json: any): Oauth2Oauth2Read {
    return Oauth2Oauth2ReadFromJSONTyped(json, false);
}

export function Oauth2Oauth2ReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oauth2Oauth2Read {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function Oauth2Oauth2ReadToJSON(json: any): Oauth2Oauth2Read {
    return Oauth2Oauth2ReadToJSONTyped(json, false);
}

export function Oauth2Oauth2ReadToJSONTyped(value?: Oauth2Oauth2Read | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
    };
}

