/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonldDefinitionReadContext } from './DefinitionJsonldDefinitionReadContext';
import {
    DefinitionJsonldDefinitionReadContextFromJSON,
    DefinitionJsonldDefinitionReadContextFromJSONTyped,
    DefinitionJsonldDefinitionReadContextToJSON,
    DefinitionJsonldDefinitionReadContextToJSONTyped,
} from './DefinitionJsonldDefinitionReadContext';

/**
 * 
 * @export
 * @interface UserJsonld
 */
export interface UserJsonld {
    /**
     * 
     * @type {DefinitionJsonldDefinitionReadContext}
     * @memberof UserJsonld
     */
    context?: DefinitionJsonldDefinitionReadContext;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    oldPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    resetPasswordLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the UserJsonld interface.
 */
export function instanceOfUserJsonld(value: object): value is UserJsonld {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserJsonldFromJSON(json: any): UserJsonld {
    return UserJsonldFromJSONTyped(json, false);
}

export function UserJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonld {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : DefinitionJsonldDefinitionReadContextFromJSON(json['@context']),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
        'token': json['token'] == null ? undefined : json['token'],
        'resetPasswordLink': json['resetPasswordLink'] == null ? undefined : json['resetPasswordLink'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserJsonldToJSON(json: any): UserJsonld {
    return UserJsonldToJSONTyped(json, false);
}

export function UserJsonldToJSONTyped(value?: Omit<UserJsonld, '@id'|'@type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': DefinitionJsonldDefinitionReadContextToJSON(value['context']),
        'id': value['id'],
        'email': value['email'],
        'password': value['password'],
        'oldPassword': value['oldPassword'],
        'token': value['token'],
        'resetPasswordLink': value['resetPasswordLink'],
        'activationUrl': value['activationUrl'],
    };
}

