/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserJsonldUserResetPassword
 */
export interface UserJsonldUserResetPassword {
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserResetPassword
     */
    password: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserResetPassword
     */
    token: string | null;
}

/**
 * Check if a given object implements the UserJsonldUserResetPassword interface.
 */
export function instanceOfUserJsonldUserResetPassword(value: object): value is UserJsonldUserResetPassword {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function UserJsonldUserResetPasswordFromJSON(json: any): UserJsonldUserResetPassword {
    return UserJsonldUserResetPasswordFromJSONTyped(json, false);
}

export function UserJsonldUserResetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonldUserResetPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'token': json['token'],
    };
}

export function UserJsonldUserResetPasswordToJSON(json: any): UserJsonldUserResetPassword {
    return UserJsonldUserResetPasswordToJSONTyped(json, false);
}

export function UserJsonldUserResetPasswordToJSONTyped(value?: UserJsonldUserResetPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'token': value['token'],
    };
}

