/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserJsonldUserResendActivation
 */
export interface UserJsonldUserResendActivation {
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserResendActivation
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserResendActivation
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the UserJsonldUserResendActivation interface.
 */
export function instanceOfUserJsonldUserResendActivation(value: object): value is UserJsonldUserResendActivation {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserJsonldUserResendActivationFromJSON(json: any): UserJsonldUserResendActivation {
    return UserJsonldUserResendActivationFromJSONTyped(json, false);
}

export function UserJsonldUserResendActivationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonldUserResendActivation {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserJsonldUserResendActivationToJSON(json: any): UserJsonldUserResendActivation {
    return UserJsonldUserResendActivationToJSONTyped(json, false);
}

export function UserJsonldUserResendActivationToJSONTyped(value?: UserJsonldUserResendActivation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'activationUrl': value['activationUrl'],
    };
}

