/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonldDefinitionReadContext } from './DefinitionJsonldDefinitionReadContext';
import {
    DefinitionJsonldDefinitionReadContextFromJSON,
    DefinitionJsonldDefinitionReadContextFromJSONTyped,
    DefinitionJsonldDefinitionReadContextToJSON,
    DefinitionJsonldDefinitionReadContextToJSONTyped,
} from './DefinitionJsonldDefinitionReadContext';

/**
 * Change user password
 * @export
 * @interface UserJsonldUserEmpty
 */
export interface UserJsonldUserEmpty {
    /**
     * 
     * @type {DefinitionJsonldDefinitionReadContext}
     * @memberof UserJsonldUserEmpty
     */
    context?: DefinitionJsonldDefinitionReadContext;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserEmpty
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserEmpty
     */
    readonly type?: string;
}

/**
 * Check if a given object implements the UserJsonldUserEmpty interface.
 */
export function instanceOfUserJsonldUserEmpty(value: object): value is UserJsonldUserEmpty {
    return true;
}

export function UserJsonldUserEmptyFromJSON(json: any): UserJsonldUserEmpty {
    return UserJsonldUserEmptyFromJSONTyped(json, false);
}

export function UserJsonldUserEmptyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonldUserEmpty {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : DefinitionJsonldDefinitionReadContextFromJSON(json['@context']),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
    };
}

export function UserJsonldUserEmptyToJSON(json: any): UserJsonldUserEmpty {
    return UserJsonldUserEmptyToJSONTyped(json, false);
}

export function UserJsonldUserEmptyToJSONTyped(value?: Omit<UserJsonldUserEmpty, '@id'|'@type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': DefinitionJsonldDefinitionReadContextToJSON(value['context']),
    };
}

