/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionReadLinks } from './DefinitionJsonhalDefinitionReadLinks';
import {
    DefinitionJsonhalDefinitionReadLinksFromJSON,
    DefinitionJsonhalDefinitionReadLinksFromJSONTyped,
    DefinitionJsonhalDefinitionReadLinksToJSON,
    DefinitionJsonhalDefinitionReadLinksToJSONTyped,
} from './DefinitionJsonhalDefinitionReadLinks';

/**
 * 
 * @export
 * @interface UserJsonhalUserResendActivation
 */
export interface UserJsonhalUserResendActivation {
    /**
     * 
     * @type {DefinitionJsonhalDefinitionReadLinks}
     * @memberof UserJsonhalUserResendActivation
     */
    links?: DefinitionJsonhalDefinitionReadLinks;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserResendActivation
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhalUserResendActivation
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the UserJsonhalUserResendActivation interface.
 */
export function instanceOfUserJsonhalUserResendActivation(value: object): value is UserJsonhalUserResendActivation {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserJsonhalUserResendActivationFromJSON(json: any): UserJsonhalUserResendActivation {
    return UserJsonhalUserResendActivationFromJSONTyped(json, false);
}

export function UserJsonhalUserResendActivationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonhalUserResendActivation {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : DefinitionJsonhalDefinitionReadLinksFromJSON(json['_links']),
        'email': json['email'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserJsonhalUserResendActivationToJSON(json: any): UserJsonhalUserResendActivation {
    return UserJsonhalUserResendActivationToJSONTyped(json, false);
}

export function UserJsonhalUserResendActivationToJSONTyped(value?: UserJsonhalUserResendActivation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': DefinitionJsonhalDefinitionReadLinksToJSON(value['links']),
        'email': value['email'],
        'activationUrl': value['activationUrl'],
    };
}

