/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionReadLinks } from './DefinitionJsonhalDefinitionReadLinks';
import {
    DefinitionJsonhalDefinitionReadLinksFromJSON,
    DefinitionJsonhalDefinitionReadLinksFromJSONTyped,
    DefinitionJsonhalDefinitionReadLinksToJSON,
    DefinitionJsonhalDefinitionReadLinksToJSONTyped,
} from './DefinitionJsonhalDefinitionReadLinks';

/**
 * Change user password
 * @export
 * @interface UserJsonhalUserEmpty
 */
export interface UserJsonhalUserEmpty {
    /**
     * 
     * @type {DefinitionJsonhalDefinitionReadLinks}
     * @memberof UserJsonhalUserEmpty
     */
    links?: DefinitionJsonhalDefinitionReadLinks;
}

/**
 * Check if a given object implements the UserJsonhalUserEmpty interface.
 */
export function instanceOfUserJsonhalUserEmpty(value: object): value is UserJsonhalUserEmpty {
    return true;
}

export function UserJsonhalUserEmptyFromJSON(json: any): UserJsonhalUserEmpty {
    return UserJsonhalUserEmptyFromJSONTyped(json, false);
}

export function UserJsonhalUserEmptyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonhalUserEmpty {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : DefinitionJsonhalDefinitionReadLinksFromJSON(json['_links']),
    };
}

export function UserJsonhalUserEmptyToJSON(json: any): UserJsonhalUserEmpty {
    return UserJsonhalUserEmptyToJSONTyped(json, false);
}

export function UserJsonhalUserEmptyToJSONTyped(value?: UserJsonhalUserEmpty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': DefinitionJsonhalDefinitionReadLinksToJSON(value['links']),
    };
}

