/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserJsonapiData } from './UserJsonapiData';
import {
    UserJsonapiDataFromJSON,
    UserJsonapiDataFromJSONTyped,
    UserJsonapiDataToJSON,
    UserJsonapiDataToJSONTyped,
} from './UserJsonapiData';

/**
 * 
 * @export
 * @interface UserJsonapi
 */
export interface UserJsonapi {
    /**
     * 
     * @type {UserJsonapiData}
     * @memberof UserJsonapi
     */
    data?: UserJsonapiData;
}

/**
 * Check if a given object implements the UserJsonapi interface.
 */
export function instanceOfUserJsonapi(value: object): value is UserJsonapi {
    return true;
}

export function UserJsonapiFromJSON(json: any): UserJsonapi {
    return UserJsonapiFromJSONTyped(json, false);
}

export function UserJsonapiFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonapi {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : UserJsonapiDataFromJSON(json['data']),
    };
}

export function UserJsonapiToJSON(json: any): UserJsonapi {
    return UserJsonapiToJSONTyped(json, false);
}

export function UserJsonapiToJSONTyped(value?: UserJsonapi | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UserJsonapiDataToJSON(value['data']),
    };
}

