/* tslint:disable */
/* eslint-disable */
/**
 * JsonHub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.14.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinitionJsonhalDefinitionReadLinks } from './DefinitionJsonhalDefinitionReadLinks';
import {
    DefinitionJsonhalDefinitionReadLinksFromJSON,
    DefinitionJsonhalDefinitionReadLinksFromJSONTyped,
    DefinitionJsonhalDefinitionReadLinksToJSON,
    DefinitionJsonhalDefinitionReadLinksToJSONTyped,
} from './DefinitionJsonhalDefinitionReadLinks';

/**
 * 
 * @export
 * @interface UserJsonhal
 */
export interface UserJsonhal {
    /**
     * 
     * @type {DefinitionJsonhalDefinitionReadLinks}
     * @memberof UserJsonhal
     */
    links?: DefinitionJsonhalDefinitionReadLinks;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    oldPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    resetPasswordLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonhal
     */
    activationUrl?: string | null;
}

/**
 * Check if a given object implements the UserJsonhal interface.
 */
export function instanceOfUserJsonhal(value: object): value is UserJsonhal {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserJsonhalFromJSON(json: any): UserJsonhal {
    return UserJsonhalFromJSONTyped(json, false);
}

export function UserJsonhalFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonhal {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : DefinitionJsonhalDefinitionReadLinksFromJSON(json['_links']),
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
        'token': json['token'] == null ? undefined : json['token'],
        'resetPasswordLink': json['resetPasswordLink'] == null ? undefined : json['resetPasswordLink'],
        'activationUrl': json['activationUrl'] == null ? undefined : json['activationUrl'],
    };
}

export function UserJsonhalToJSON(json: any): UserJsonhal {
    return UserJsonhalToJSONTyped(json, false);
}

export function UserJsonhalToJSONTyped(value?: UserJsonhal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': DefinitionJsonhalDefinitionReadLinksToJSON(value['links']),
        'id': value['id'],
        'email': value['email'],
        'password': value['password'],
        'oldPassword': value['oldPassword'],
        'token': value['token'],
        'resetPasswordLink': value['resetPasswordLink'],
        'activationUrl': value['activationUrl'],
    };
}

